// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 04 - Autom Screen

#ifndef UI_AUTOM_SCREEN_H
#define UI_AUTOM_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_autom_screen
extern void ui_autom_screen_screen_init(void);
extern void ui_autom_screen_screen_destroy(void);
extern lv_obj_t * ui_autom_screen;
extern lv_obj_t * ui_autom_top_bar;
extern lv_obj_t * ui_autom_image_ce;
extern lv_obj_t * ui_autom_menu_bar;
extern lv_obj_t * ui_autom_screen_btn_img_autom;
extern lv_obj_t * ui_autom_menu_container;
extern lv_obj_t * ui_autom_btn_menu_home;
extern lv_obj_t * ui_autom_btn_menu_main;
extern lv_obj_t * ui_autom_btn_menu_settings;
extern void ui_event_btn_menu_autom(lv_event_t * e);
extern lv_obj_t * ui_autom_btn_menu_autom;
extern lv_obj_t * ui_autom_btn_menu_log;
extern lv_obj_t * ui_autom_btn_menu_aux;
extern lv_obj_t * ui_autom_btn_menu_debug;
extern lv_obj_t * ui_autom_buttons_container;
extern lv_obj_t * ui_autom_btn_feed_pump;
extern lv_obj_t * ui_autom_label_feed_pump;
extern lv_obj_t * ui_autom_btn_hp_pump;
extern lv_obj_t * ui_autom_label_hp_pump;
extern lv_obj_t * ui_autom_btn_flushing_cycle;
extern lv_obj_t * ui_autom_label_flushing_cycle;
extern lv_obj_t * ui_autom_btn_tank_test;
extern lv_obj_t * ui_autom_label_tank_test;
extern lv_obj_t * ui_autom_screen_container_target_mode;
extern lv_obj_t * ui_autom_screen_image_target_mode;
extern lv_obj_t * ui_autom_screen_roller_target_mode;
extern lv_obj_t * ui_autom_screen_label_target_mode_text;
extern lv_obj_t * ui_autom_screen_label_target_mode_output;
extern lv_obj_t * ui_autom_screen_container_countdown;
extern lv_obj_t * ui_autom_screen_label_countd_text;
extern lv_obj_t * ui_autom_screen_btn_countdown_plus;
extern lv_obj_t * ui_autom_screen_label_countdown_plus;
extern lv_obj_t * ui_autom_screen_btn_countdown_minus;
extern lv_obj_t * ui_autom_screen_label_countdown_minus;
extern lv_obj_t * ui_autom_screen_label_countdown_time_set;
extern lv_obj_t * ui_autom_screen_img_clock;
extern lv_obj_t * ui_autom_screen_countdown_ttg_ltg;
extern lv_obj_t * ui_autom_screen_label_countdown_ttg_text;
extern lv_obj_t * ui_autom_screen_container_auto_production;
extern lv_obj_t * ui_autom_screen_label_prod_text;
extern lv_obj_t * ui_autom_screen_btn_on_off;
extern lv_obj_t * ui_autom_screen_label_on_off;
extern lv_obj_t * ui_autom_screen_btn_start_auto;
extern lv_obj_t * ui_autom_screen_label_start_auto;
extern lv_obj_t * ui_autom_screen_label_auto_prod_set;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

