// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 06 - Aux Screen

#ifndef UI_AUX_SCREEN_H
#define UI_AUX_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_aux_screen
extern void ui_aux_screen_screen_init(void);
extern void ui_aux_screen_screen_destroy(void);
extern lv_obj_t * ui_aux_screen;
extern lv_obj_t * ui_aux_top_bar;
extern lv_obj_t * ui_aux_image_ce;
extern lv_obj_t * ui_aux_menu_bar;
extern lv_obj_t * ui_aux_screen_btn_img_aux;
extern lv_obj_t * ui_aux_menu_container;
extern lv_obj_t * ui_aux_btn_menu_home;
extern lv_obj_t * ui_aux_btn_menu_main;
extern lv_obj_t * ui_aux_btn_menu_settings;
extern lv_obj_t * ui_aux_btn_menu_autom;
extern lv_obj_t * ui_aux_btn_menu_log;
extern void ui_event_btn_menu_aux(lv_event_t * e);
extern lv_obj_t * ui_aux_btn_menu_aux;
extern lv_obj_t * ui_aux_btn_menu_debug;
extern lv_obj_t * ui_aux_buttons_container;
extern lv_obj_t * ui_aux_btn_feed_pump;
extern lv_obj_t * ui_aux_label_feed_pump;
extern lv_obj_t * ui_aux_btn_hp_pump;
extern lv_obj_t * ui_aux_label_hp_pump;
extern lv_obj_t * ui_aux_btn_flushing_cycle;
extern lv_obj_t * ui_aux_label_flushing_cycle;
extern lv_obj_t * ui_aux_btn_tank_test;
extern lv_obj_t * ui_aux_label_tank_test;
extern lv_obj_t * ui_aux_screen_container_1;
extern lv_obj_t * ui_aux_screen_label_inputs;
extern lv_obj_t * ui_aux_screen_container_2;
extern lv_obj_t * ui_aux_screen_label_outputs;
extern lv_obj_t * ui_aux_screen_btn_hp_fan;
extern lv_obj_t * ui_aux_screen_label_hp_fan;
extern lv_obj_t * ui_aux_screen_btn_aux;
extern lv_obj_t * ui_aux_screen_label_aux;
extern lv_obj_t * ui_aux_screen_btn_tank_diverting;
extern lv_obj_t * ui_aux_screen_label__tank_diverting;
extern lv_obj_t * ui_aux_screen_input_4;
extern lv_obj_t * ui_aux_screen_label_input_4;
extern lv_obj_t * ui_aux_screen_label_input_4_value;
extern lv_obj_t * ui_aux_screen_input_5;
extern lv_obj_t * ui_aux_screen_label_input_5;
extern lv_obj_t * ui_aux_screen_label_input_5_value;
extern lv_obj_t * ui_aux_screen_input_6;
extern lv_obj_t * ui_aux_screen_label_input_6;
extern lv_obj_t * ui_aux_screen_label_input_6_value;
extern lv_obj_t * ui_aux_screen_input_7;
extern lv_obj_t * ui_aux_screen_label_input_7;
extern lv_obj_t * ui_aux_screen_label_input_7_value;
extern lv_obj_t * ui_aux_screen_input_8;
extern lv_obj_t * ui_aux_screen_label_input_8;
extern lv_obj_t * ui_aux_screen_label_input_8_value;
extern lv_obj_t * ui_aux_screen_input_9;
extern lv_obj_t * ui_aux_screen_label_input_9;
extern lv_obj_t * ui_aux_screen_label_input_9_value;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

