// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 04 - Autom Screen

#include "../ui.h"

lv_obj_t * ui_autom_screen = NULL;
lv_obj_t * ui_autom_top_bar = NULL;
lv_obj_t * ui_autom_image_ce = NULL;
lv_obj_t * ui_autom_menu_bar = NULL;
lv_obj_t * ui_autom_screen_btn_img_autom = NULL;
lv_obj_t * ui_autom_menu_container = NULL;
lv_obj_t * ui_autom_btn_menu_home = NULL;
lv_obj_t * ui_autom_btn_menu_main = NULL;
lv_obj_t * ui_autom_btn_menu_settings = NULL;
lv_obj_t * ui_autom_btn_menu_autom = NULL;
lv_obj_t * ui_autom_btn_menu_log = NULL;
lv_obj_t * ui_autom_btn_menu_aux = NULL;
lv_obj_t * ui_autom_btn_menu_debug = NULL;
lv_obj_t * ui_autom_buttons_container = NULL;
lv_obj_t * ui_autom_btn_feed_pump = NULL;
lv_obj_t * ui_autom_label_feed_pump = NULL;
lv_obj_t * ui_autom_btn_hp_pump = NULL;
lv_obj_t * ui_autom_label_hp_pump = NULL;
lv_obj_t * ui_autom_btn_flushing_cycle = NULL;
lv_obj_t * ui_autom_label_flushing_cycle = NULL;
lv_obj_t * ui_autom_btn_tank_test = NULL;
lv_obj_t * ui_autom_label_tank_test = NULL;
lv_obj_t * ui_autom_screen_container_target_mode = NULL;
lv_obj_t * ui_autom_screen_image_target_mode = NULL;
lv_obj_t * ui_autom_screen_roller_target_mode = NULL;
lv_obj_t * ui_autom_screen_label_target_mode_text = NULL;
lv_obj_t * ui_autom_screen_label_target_mode_output = NULL;
lv_obj_t * ui_autom_screen_container_countdown = NULL;
lv_obj_t * ui_autom_screen_label_countd_text = NULL;
lv_obj_t * ui_autom_screen_btn_countdown_plus = NULL;
lv_obj_t * ui_autom_screen_label_countdown_plus = NULL;
lv_obj_t * ui_autom_screen_btn_countdown_minus = NULL;
lv_obj_t * ui_autom_screen_label_countdown_minus = NULL;
lv_obj_t * ui_autom_screen_label_countdown_time_set = NULL;
lv_obj_t * ui_autom_screen_img_clock = NULL;
lv_obj_t * ui_autom_screen_countdown_ttg_ltg = NULL;
lv_obj_t * ui_autom_screen_label_countdown_ttg_text = NULL;
lv_obj_t * ui_autom_screen_container_auto_production = NULL;
lv_obj_t * ui_autom_screen_label_prod_text = NULL;
lv_obj_t * ui_autom_screen_btn_on_off = NULL;
lv_obj_t * ui_autom_screen_label_on_off = NULL;
lv_obj_t * ui_autom_screen_btn_start_auto = NULL;
lv_obj_t * ui_autom_screen_label_start_auto = NULL;
lv_obj_t * ui_autom_screen_label_auto_prod_set = NULL;
// event funtions
void ui_event_btn_menu_autom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_autom_screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_autom_screen_screen_init);
    }
}

// build funtions

void ui_autom_screen_screen_init(void)
{
    ui_autom_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_autom_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_autom_screen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_autom_screen, lv_color_hex(0x596684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_autom_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_top_bar = lv_image_create(ui_autom_screen);
    lv_image_set_src(ui_autom_top_bar, &ui_img_top_bar_png);
    lv_obj_set_width(ui_autom_top_bar, LV_SIZE_CONTENT);   /// 681
    lv_obj_set_height(ui_autom_top_bar, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_autom_top_bar, 37);
    lv_obj_set_y(ui_autom_top_bar, -218);
    lv_obj_set_align(ui_autom_top_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_autom_top_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_autom_top_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autom_image_ce = lv_image_create(ui_autom_screen);
    lv_image_set_src(ui_autom_image_ce, &ui_img_625624875);
    lv_obj_set_width(ui_autom_image_ce, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_autom_image_ce, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_autom_image_ce, 350);
    lv_obj_set_y(ui_autom_image_ce, -221);
    lv_obj_set_align(ui_autom_image_ce, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_autom_image_ce, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_autom_image_ce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autom_menu_bar = lv_image_create(ui_autom_screen);
    lv_image_set_src(ui_autom_menu_bar, &ui_img_menu_bar_png);
    lv_obj_set_width(ui_autom_menu_bar, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_autom_menu_bar, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_autom_menu_bar, -363);
    lv_obj_set_y(ui_autom_menu_bar, 0);
    lv_obj_set_align(ui_autom_menu_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_autom_menu_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_autom_menu_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autom_screen_btn_img_autom = lv_image_create(ui_autom_screen);
    lv_image_set_src(ui_autom_screen_btn_img_autom, &ui_img_btn_autom_png);
    lv_obj_set_width(ui_autom_screen_btn_img_autom, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_autom_screen_btn_img_autom, LV_SIZE_CONTENT);    /// 66
    lv_obj_set_x(ui_autom_screen_btn_img_autom, -360);
    lv_obj_set_y(ui_autom_screen_btn_img_autom, 2);
    lv_obj_set_align(ui_autom_screen_btn_img_autom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_autom_screen_btn_img_autom, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_autom_screen_btn_img_autom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autom_menu_container = lv_obj_create(ui_autom_screen);
    lv_obj_remove_style_all(ui_autom_menu_container);
    lv_obj_set_width(ui_autom_menu_container, 83);
    lv_obj_set_height(ui_autom_menu_container, 488);
    lv_obj_set_x(ui_autom_menu_container, -2);
    lv_obj_set_y(ui_autom_menu_container, -2);
    lv_obj_remove_flag(ui_autom_menu_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autom_btn_menu_home = lv_image_create(ui_autom_menu_container);
    lv_obj_set_width(ui_autom_btn_menu_home, 74);
    lv_obj_set_height(ui_autom_btn_menu_home, 65);
    lv_obj_set_x(ui_autom_btn_menu_home, 5);
    lv_obj_set_y(ui_autom_btn_menu_home, -412);
    lv_obj_set_align(ui_autom_btn_menu_home, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_autom_btn_menu_home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_autom_btn_menu_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_autom_btn_menu_home, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_autom_btn_menu_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_btn_menu_main = lv_image_create(ui_autom_menu_container);
    lv_obj_set_width(ui_autom_btn_menu_main, 74);
    lv_obj_set_height(ui_autom_btn_menu_main, 59);
    lv_obj_set_x(ui_autom_btn_menu_main, 5);
    lv_obj_set_y(ui_autom_btn_menu_main, -345);
    lv_obj_set_align(ui_autom_btn_menu_main, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_autom_btn_menu_main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_autom_btn_menu_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_autom_btn_menu_main, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_autom_btn_menu_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_btn_menu_settings = lv_image_create(ui_autom_menu_container);
    lv_obj_set_width(ui_autom_btn_menu_settings, 74);
    lv_obj_set_height(ui_autom_btn_menu_settings, 59);
    lv_obj_set_x(ui_autom_btn_menu_settings, 5);
    lv_obj_set_y(ui_autom_btn_menu_settings, -278);
    lv_obj_set_align(ui_autom_btn_menu_settings, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_autom_btn_menu_settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_autom_btn_menu_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_autom_btn_menu_settings, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_autom_btn_menu_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_btn_menu_autom = lv_image_create(ui_autom_menu_container);
    lv_obj_set_width(ui_autom_btn_menu_autom, 74);
    lv_obj_set_height(ui_autom_btn_menu_autom, 59);
    lv_obj_set_x(ui_autom_btn_menu_autom, 5);
    lv_obj_set_y(ui_autom_btn_menu_autom, -212);
    lv_obj_set_align(ui_autom_btn_menu_autom, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_autom_btn_menu_autom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_autom_btn_menu_autom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_autom_btn_menu_autom, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_autom_btn_menu_autom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_btn_menu_log = lv_image_create(ui_autom_menu_container);
    lv_obj_set_width(ui_autom_btn_menu_log, 74);
    lv_obj_set_height(ui_autom_btn_menu_log, 59);
    lv_obj_set_x(ui_autom_btn_menu_log, 5);
    lv_obj_set_y(ui_autom_btn_menu_log, -146);
    lv_obj_set_align(ui_autom_btn_menu_log, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_autom_btn_menu_log, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_autom_btn_menu_log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_autom_btn_menu_log, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_autom_btn_menu_log, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_btn_menu_aux = lv_image_create(ui_autom_menu_container);
    lv_obj_set_width(ui_autom_btn_menu_aux, 74);
    lv_obj_set_height(ui_autom_btn_menu_aux, 59);
    lv_obj_set_x(ui_autom_btn_menu_aux, 5);
    lv_obj_set_y(ui_autom_btn_menu_aux, -80);
    lv_obj_set_align(ui_autom_btn_menu_aux, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_autom_btn_menu_aux, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_autom_btn_menu_aux, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_autom_btn_menu_aux, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_autom_btn_menu_aux, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_btn_menu_debug = lv_image_create(ui_autom_menu_container);
    lv_obj_set_width(ui_autom_btn_menu_debug, 74);
    lv_obj_set_height(ui_autom_btn_menu_debug, 59);
    lv_obj_set_x(ui_autom_btn_menu_debug, 5);
    lv_obj_set_y(ui_autom_btn_menu_debug, -12);
    lv_obj_set_align(ui_autom_btn_menu_debug, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_autom_btn_menu_debug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_autom_btn_menu_debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_autom_btn_menu_debug, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_autom_btn_menu_debug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_buttons_container = lv_obj_create(ui_autom_screen);
    lv_obj_remove_style_all(ui_autom_buttons_container);
    lv_obj_set_width(ui_autom_buttons_container, 684);
    lv_obj_set_height(ui_autom_buttons_container, 65);
    lv_obj_set_x(ui_autom_buttons_container, 32);
    lv_obj_set_y(ui_autom_buttons_container, 185);
    lv_obj_set_align(ui_autom_buttons_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_autom_buttons_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autom_btn_feed_pump = lv_imagebutton_create(ui_autom_buttons_container);
    lv_imagebutton_set_src(ui_autom_btn_feed_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_feed_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_autom_btn_feed_pump, 66);
    lv_obj_set_width(ui_autom_btn_feed_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_autom_btn_feed_pump, 7);
    lv_obj_set_y(ui_autom_btn_feed_pump, 0);
    lv_obj_set_align(ui_autom_btn_feed_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_autom_btn_feed_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_autom_btn_feed_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_autom_btn_feed_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_autom_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_autom_btn_feed_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_autom_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_autom_label_feed_pump = lv_label_create(ui_autom_btn_feed_pump);
    lv_obj_set_width(ui_autom_label_feed_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_label_feed_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_autom_label_feed_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autom_label_feed_pump, "FEED PUMP");
    lv_obj_set_style_text_align(ui_autom_label_feed_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_label_feed_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_btn_hp_pump = lv_imagebutton_create(ui_autom_buttons_container);
    lv_imagebutton_set_src(ui_autom_btn_hp_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_hp_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_autom_btn_hp_pump, 66);
    lv_obj_set_width(ui_autom_btn_hp_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_autom_btn_hp_pump, 176);
    lv_obj_set_y(ui_autom_btn_hp_pump, 0);
    lv_obj_set_align(ui_autom_btn_hp_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_autom_btn_hp_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_autom_btn_hp_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_autom_btn_hp_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_autom_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_autom_btn_hp_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_autom_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_autom_label_hp_pump = lv_label_create(ui_autom_btn_hp_pump);
    lv_obj_set_width(ui_autom_label_hp_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_label_hp_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_autom_label_hp_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autom_label_hp_pump, "H.P. PUMP");
    lv_obj_set_style_text_align(ui_autom_label_hp_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_label_hp_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_btn_flushing_cycle = lv_imagebutton_create(ui_autom_buttons_container);
    lv_imagebutton_set_src(ui_autom_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_autom_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_obj_set_height(ui_autom_btn_flushing_cycle, 66);
    lv_obj_set_width(ui_autom_btn_flushing_cycle, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_autom_btn_flushing_cycle, 351);
    lv_obj_set_y(ui_autom_btn_flushing_cycle, 0);
    lv_obj_set_align(ui_autom_btn_flushing_cycle, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_autom_btn_flushing_cycle, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_autom_btn_flushing_cycle, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_autom_btn_flushing_cycle, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_autom_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_autom_btn_flushing_cycle, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_autom_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_autom_label_flushing_cycle = lv_label_create(ui_autom_btn_flushing_cycle);
    lv_obj_set_width(ui_autom_label_flushing_cycle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_label_flushing_cycle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_autom_label_flushing_cycle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autom_label_flushing_cycle, "FLUSHING\nCYCLE");
    lv_obj_set_style_text_align(ui_autom_label_flushing_cycle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_label_flushing_cycle, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_btn_tank_test = lv_imagebutton_create(ui_autom_buttons_container);
    lv_imagebutton_set_src(ui_autom_btn_tank_test, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_tank_test, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_autom_btn_tank_test, 66);
    lv_obj_set_width(ui_autom_btn_tank_test, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_autom_btn_tank_test, 522);
    lv_obj_set_y(ui_autom_btn_tank_test, 0);
    lv_obj_set_align(ui_autom_btn_tank_test, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_autom_btn_tank_test, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_autom_btn_tank_test, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_autom_btn_tank_test, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_autom_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_autom_btn_tank_test, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_autom_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_autom_label_tank_test = lv_label_create(ui_autom_btn_tank_test);
    lv_obj_set_width(ui_autom_label_tank_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_label_tank_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_autom_label_tank_test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autom_label_tank_test, "WATER\nTO TANK");
    lv_obj_set_style_text_align(ui_autom_label_tank_test, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_label_tank_test, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_container_target_mode = lv_obj_create(ui_autom_screen);
    lv_obj_remove_style_all(ui_autom_screen_container_target_mode);
    lv_obj_set_width(ui_autom_screen_container_target_mode, 207);
    lv_obj_set_height(ui_autom_screen_container_target_mode, 309);
    lv_obj_set_x(ui_autom_screen_container_target_mode, -199);
    lv_obj_set_y(ui_autom_screen_container_target_mode, -18);
    lv_obj_set_align(ui_autom_screen_container_target_mode, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_autom_screen_container_target_mode,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_autom_screen_container_target_mode, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_autom_screen_container_target_mode, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_autom_screen_container_target_mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_image_target_mode = lv_image_create(ui_autom_screen_container_target_mode);
    lv_image_set_src(ui_autom_screen_image_target_mode, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_autom_screen_image_target_mode, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_autom_screen_image_target_mode, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_autom_screen_image_target_mode, 0);
    lv_obj_set_y(ui_autom_screen_image_target_mode, -26);
    lv_obj_set_align(ui_autom_screen_image_target_mode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_autom_screen_image_target_mode, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_autom_screen_roller_target_mode = lv_roller_create(ui_autom_screen_container_target_mode);
    lv_roller_set_options(ui_autom_screen_roller_target_mode, "TIME\nLITERS", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_autom_screen_roller_target_mode, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_autom_screen_roller_target_mode, 142);
    lv_obj_set_height(ui_autom_screen_roller_target_mode, 131);
    lv_obj_set_x(ui_autom_screen_roller_target_mode, 0);
    lv_obj_set_y(ui_autom_screen_roller_target_mode, -26);
    lv_obj_set_align(ui_autom_screen_roller_target_mode, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_autom_screen_roller_target_mode, lv_color_hex(0x3F475E),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_roller_target_mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_roller_target_mode, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_autom_screen_roller_target_mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_autom_screen_roller_target_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_autom_screen_roller_target_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_autom_screen_roller_target_mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_autom_screen_roller_target_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_autom_screen_roller_target_mode, lv_color_hex(0xDBE6FF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_roller_target_mode, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_roller_target_mode, &lv_font_montserrat_26,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_autom_screen_roller_target_mode, lv_color_hex(0x3A445C),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_autom_screen_roller_target_mode, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_autom_screen_label_target_mode_text = lv_label_create(ui_autom_screen_container_target_mode);
    lv_obj_set_width(ui_autom_screen_label_target_mode_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_target_mode_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_label_target_mode_text, -3);
    lv_obj_set_y(ui_autom_screen_label_target_mode_text, 16);
    lv_obj_set_align(ui_autom_screen_label_target_mode_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_autom_screen_label_target_mode_text, "TARGET MODE");
    lv_obj_set_style_text_color(ui_autom_screen_label_target_mode_text, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_label_target_mode_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_autom_screen_label_target_mode_text, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_target_mode_text, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_label_target_mode_output = lv_label_create(ui_autom_screen_container_target_mode);
    lv_obj_set_width(ui_autom_screen_label_target_mode_output, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_target_mode_output, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_label_target_mode_output, -1);
    lv_obj_set_y(ui_autom_screen_label_target_mode_output, 260);
    lv_obj_set_align(ui_autom_screen_label_target_mode_output, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_autom_screen_label_target_mode_output, "TIME MODE");
    lv_obj_set_style_text_color(ui_autom_screen_label_target_mode_output, lv_color_hex(0x1D47A5),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_label_target_mode_output, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_autom_screen_label_target_mode_output, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_target_mode_output, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_container_countdown = lv_obj_create(ui_autom_screen);
    lv_obj_remove_style_all(ui_autom_screen_container_countdown);
    lv_obj_set_width(ui_autom_screen_container_countdown, 207);
    lv_obj_set_height(ui_autom_screen_container_countdown, 309);
    lv_obj_set_x(ui_autom_screen_container_countdown, 33);
    lv_obj_set_y(ui_autom_screen_container_countdown, -18);
    lv_obj_set_align(ui_autom_screen_container_countdown, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_autom_screen_container_countdown, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_autom_screen_container_countdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_autom_screen_container_countdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_autom_screen_container_countdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_label_countd_text = lv_label_create(ui_autom_screen_container_countdown);
    lv_obj_set_width(ui_autom_screen_label_countd_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_countd_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_label_countd_text, 0);
    lv_obj_set_y(ui_autom_screen_label_countd_text, 16);
    lv_obj_set_align(ui_autom_screen_label_countd_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_autom_screen_label_countd_text, "TARGET/COUNTDOWN");
    lv_obj_set_style_text_color(ui_autom_screen_label_countd_text, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_label_countd_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_autom_screen_label_countd_text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_countd_text, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_btn_countdown_plus = lv_imagebutton_create(ui_autom_screen_container_countdown);
    lv_imagebutton_set_src(ui_autom_screen_btn_countdown_plus, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_countdown_plus, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_countdown_plus, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_countdown_plus, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_autom_screen_btn_countdown_plus, 66);
    lv_obj_set_width(ui_autom_screen_btn_countdown_plus, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_autom_screen_btn_countdown_plus, -18);
    lv_obj_set_y(ui_autom_screen_btn_countdown_plus, 47);
    lv_obj_set_align(ui_autom_screen_btn_countdown_plus, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_autom_screen_btn_countdown_plus, lv_color_hex(0xABC1ED),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_countdown_plus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_autom_screen_btn_countdown_plus, lv_color_hex(0x00B9FF),
                                LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_countdown_plus, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_autom_screen_btn_countdown_plus, lv_color_hex(0x06CEFB),
                                LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_countdown_plus, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_autom_screen_label_countdown_plus = lv_label_create(ui_autom_screen_btn_countdown_plus);
    lv_obj_set_width(ui_autom_screen_label_countdown_plus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_countdown_plus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_label_countdown_plus, -3);
    lv_obj_set_y(ui_autom_screen_label_countdown_plus, 0);
    lv_obj_set_align(ui_autom_screen_label_countdown_plus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autom_screen_label_countdown_plus, "+");
    lv_obj_set_style_text_align(ui_autom_screen_label_countdown_plus, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_countdown_plus, &lv_font_montserrat_48,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_btn_countdown_minus = lv_imagebutton_create(ui_autom_screen_container_countdown);
    lv_imagebutton_set_src(ui_autom_screen_btn_countdown_minus, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_countdown_minus, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_countdown_minus, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_countdown_minus, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_autom_screen_btn_countdown_minus, 66);
    lv_obj_set_width(ui_autom_screen_btn_countdown_minus, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_autom_screen_btn_countdown_minus, -19);
    lv_obj_set_y(ui_autom_screen_btn_countdown_minus, 123);
    lv_obj_set_align(ui_autom_screen_btn_countdown_minus, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_autom_screen_btn_countdown_minus, lv_color_hex(0xABC1ED),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_countdown_minus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_autom_screen_btn_countdown_minus, lv_color_hex(0x00B9FF),
                                LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_countdown_minus, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_autom_screen_btn_countdown_minus, lv_color_hex(0x06CEFB),
                                LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_countdown_minus, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_autom_screen_label_countdown_minus = lv_label_create(ui_autom_screen_btn_countdown_minus);
    lv_obj_set_width(ui_autom_screen_label_countdown_minus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_countdown_minus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_label_countdown_minus, -3);
    lv_obj_set_y(ui_autom_screen_label_countdown_minus, 0);
    lv_obj_set_align(ui_autom_screen_label_countdown_minus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autom_screen_label_countdown_minus, "-");
    lv_obj_set_style_text_align(ui_autom_screen_label_countdown_minus, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_countdown_minus, &lv_font_montserrat_48,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_label_countdown_time_set = lv_label_create(ui_autom_screen_container_countdown);
    lv_obj_set_width(ui_autom_screen_label_countdown_time_set, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_countdown_time_set, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_label_countdown_time_set, 0);
    lv_obj_set_y(ui_autom_screen_label_countdown_time_set, 204);
    lv_obj_set_align(ui_autom_screen_label_countdown_time_set, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_autom_screen_label_countdown_time_set, "2 HOURS");
    lv_obj_set_style_text_color(ui_autom_screen_label_countdown_time_set, lv_color_hex(0x1D47A5),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_label_countdown_time_set, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_autom_screen_label_countdown_time_set, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_countdown_time_set, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_img_clock = lv_image_create(ui_autom_screen_container_countdown);
    lv_image_set_src(ui_autom_screen_img_clock, &ui_img_icn_time_2_png);
    lv_obj_set_width(ui_autom_screen_img_clock, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_autom_screen_img_clock, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_autom_screen_img_clock, 46);
    lv_obj_set_y(ui_autom_screen_img_clock, 92);
    lv_obj_set_align(ui_autom_screen_img_clock, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_autom_screen_img_clock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_autom_screen_countdown_ttg_ltg = lv_label_create(ui_autom_screen_container_countdown);
    lv_obj_set_width(ui_autom_screen_countdown_ttg_ltg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_countdown_ttg_ltg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_countdown_ttg_ltg, 75);
    lv_obj_set_y(ui_autom_screen_countdown_ttg_ltg, 125);
    lv_obj_set_align(ui_autom_screen_countdown_ttg_ltg, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_autom_screen_countdown_ttg_ltg, "08:25");
    lv_obj_set_style_text_color(ui_autom_screen_countdown_ttg_ltg, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_countdown_ttg_ltg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_countdown_ttg_ltg, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_label_countdown_ttg_text = lv_label_create(ui_autom_screen_container_countdown);
    lv_obj_set_width(ui_autom_screen_label_countdown_ttg_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_countdown_ttg_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_label_countdown_ttg_text, 15);
    lv_obj_set_y(ui_autom_screen_label_countdown_ttg_text, 236);
    lv_obj_set_align(ui_autom_screen_label_countdown_ttg_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_autom_screen_label_countdown_ttg_text, "TTG - LTG");
    lv_obj_set_style_text_color(ui_autom_screen_label_countdown_ttg_text, lv_color_hex(0x9098AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_label_countdown_ttg_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_countdown_ttg_text, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_container_auto_production = lv_obj_create(ui_autom_screen);
    lv_obj_remove_style_all(ui_autom_screen_container_auto_production);
    lv_obj_set_width(ui_autom_screen_container_auto_production, 207);
    lv_obj_set_height(ui_autom_screen_container_auto_production, 309);
    lv_obj_set_x(ui_autom_screen_container_auto_production, 267);
    lv_obj_set_y(ui_autom_screen_container_auto_production, -18);
    lv_obj_set_align(ui_autom_screen_container_auto_production, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_autom_screen_container_auto_production,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_autom_screen_container_auto_production, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_autom_screen_container_auto_production, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_autom_screen_container_auto_production, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_label_prod_text = lv_label_create(ui_autom_screen_container_auto_production);
    lv_obj_set_width(ui_autom_screen_label_prod_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_prod_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_label_prod_text, 0);
    lv_obj_set_y(ui_autom_screen_label_prod_text, 16);
    lv_obj_set_align(ui_autom_screen_label_prod_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_autom_screen_label_prod_text, "AUTO PRODUCTION");
    lv_obj_set_style_text_color(ui_autom_screen_label_prod_text, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_label_prod_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_autom_screen_label_prod_text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_prod_text, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_btn_on_off = lv_imagebutton_create(ui_autom_screen_container_auto_production);
    lv_imagebutton_set_src(ui_autom_screen_btn_on_off, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_on_off, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_on_off, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_on_off, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_obj_set_height(ui_autom_screen_btn_on_off, 66);
    lv_obj_set_width(ui_autom_screen_btn_on_off, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_autom_screen_btn_on_off, 27);
    lv_obj_set_y(ui_autom_screen_btn_on_off, -73);
    lv_obj_set_align(ui_autom_screen_btn_on_off, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_autom_screen_btn_on_off, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_autom_screen_btn_on_off, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_on_off, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_autom_screen_btn_on_off, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_on_off, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_autom_screen_btn_on_off, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_on_off, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_autom_screen_label_on_off = lv_label_create(ui_autom_screen_btn_on_off);
    lv_obj_set_width(ui_autom_screen_label_on_off, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_on_off, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_autom_screen_label_on_off, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autom_screen_label_on_off, "ON/OFF");
    lv_obj_set_style_text_align(ui_autom_screen_label_on_off, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_on_off, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_btn_start_auto = lv_imagebutton_create(ui_autom_screen_container_auto_production);
    lv_imagebutton_set_src(ui_autom_screen_btn_start_auto, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png,
                           NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_start_auto, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_start_auto, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_autom_screen_btn_start_auto, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_autom_screen_btn_start_auto, 66);
    lv_obj_set_width(ui_autom_screen_btn_start_auto, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_autom_screen_btn_start_auto, 26);
    lv_obj_set_y(ui_autom_screen_btn_start_auto, 79);
    lv_obj_set_align(ui_autom_screen_btn_start_auto, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_autom_screen_btn_start_auto, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_autom_screen_btn_start_auto, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_start_auto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_autom_screen_btn_start_auto, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_start_auto, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_autom_screen_btn_start_auto, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_autom_screen_btn_start_auto, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_autom_screen_label_start_auto = lv_label_create(ui_autom_screen_btn_start_auto);
    lv_obj_set_width(ui_autom_screen_label_start_auto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_start_auto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_autom_screen_label_start_auto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autom_screen_label_start_auto, "START AUTO");
    lv_obj_set_style_text_align(ui_autom_screen_label_start_auto, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_start_auto, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autom_screen_label_auto_prod_set = lv_label_create(ui_autom_screen_container_auto_production);
    lv_obj_set_width(ui_autom_screen_label_auto_prod_set, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autom_screen_label_auto_prod_set, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autom_screen_label_auto_prod_set, 2);
    lv_obj_set_y(ui_autom_screen_label_auto_prod_set, 147);
    lv_obj_set_align(ui_autom_screen_label_auto_prod_set, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_autom_screen_label_auto_prod_set, "2 HOURS");
    lv_obj_set_style_text_color(ui_autom_screen_label_auto_prod_set, lv_color_hex(0x1D47A5),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autom_screen_label_auto_prod_set, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_autom_screen_label_auto_prod_set, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autom_screen_label_auto_prod_set, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_autom_btn_menu_autom, ui_event_btn_menu_autom, LV_EVENT_ALL, NULL);

}

void ui_autom_screen_screen_destroy(void)
{
    if(ui_autom_screen) lv_obj_del(ui_autom_screen);

    // NULL screen variables
    ui_autom_screen = NULL;
    ui_autom_top_bar = NULL;
    ui_autom_image_ce = NULL;
    ui_autom_menu_bar = NULL;
    ui_autom_screen_btn_img_autom = NULL;
    ui_autom_menu_container = NULL;
    ui_autom_btn_menu_home = NULL;
    ui_autom_btn_menu_main = NULL;
    ui_autom_btn_menu_settings = NULL;
    ui_autom_btn_menu_autom = NULL;
    ui_autom_btn_menu_log = NULL;
    ui_autom_btn_menu_aux = NULL;
    ui_autom_btn_menu_debug = NULL;
    ui_autom_buttons_container = NULL;
    ui_autom_btn_feed_pump = NULL;
    ui_autom_label_feed_pump = NULL;
    ui_autom_btn_hp_pump = NULL;
    ui_autom_label_hp_pump = NULL;
    ui_autom_btn_flushing_cycle = NULL;
    ui_autom_label_flushing_cycle = NULL;
    ui_autom_btn_tank_test = NULL;
    ui_autom_label_tank_test = NULL;
    ui_autom_screen_container_target_mode = NULL;
    ui_autom_screen_image_target_mode = NULL;
    ui_autom_screen_roller_target_mode = NULL;
    ui_autom_screen_label_target_mode_text = NULL;
    ui_autom_screen_label_target_mode_output = NULL;
    ui_autom_screen_container_countdown = NULL;
    ui_autom_screen_label_countd_text = NULL;
    ui_autom_screen_btn_countdown_plus = NULL;
    ui_autom_screen_label_countdown_plus = NULL;
    ui_autom_screen_btn_countdown_minus = NULL;
    ui_autom_screen_label_countdown_minus = NULL;
    ui_autom_screen_label_countdown_time_set = NULL;
    ui_autom_screen_img_clock = NULL;
    ui_autom_screen_countdown_ttg_ltg = NULL;
    ui_autom_screen_label_countdown_ttg_text = NULL;
    ui_autom_screen_container_auto_production = NULL;
    ui_autom_screen_label_prod_text = NULL;
    ui_autom_screen_btn_on_off = NULL;
    ui_autom_screen_label_on_off = NULL;
    ui_autom_screen_btn_start_auto = NULL;
    ui_autom_screen_label_start_auto = NULL;
    ui_autom_screen_label_auto_prod_set = NULL;

}
