// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 06 - Aux Screen

#include "../ui.h"

lv_obj_t * ui_aux_screen = NULL;
lv_obj_t * ui_aux_top_bar = NULL;
lv_obj_t * ui_aux_image_ce = NULL;
lv_obj_t * ui_aux_menu_bar = NULL;
lv_obj_t * ui_aux_screen_btn_img_aux = NULL;
lv_obj_t * ui_aux_menu_container = NULL;
lv_obj_t * ui_aux_btn_menu_home = NULL;
lv_obj_t * ui_aux_btn_menu_main = NULL;
lv_obj_t * ui_aux_btn_menu_settings = NULL;
lv_obj_t * ui_aux_btn_menu_autom = NULL;
lv_obj_t * ui_aux_btn_menu_log = NULL;
lv_obj_t * ui_aux_btn_menu_aux = NULL;
lv_obj_t * ui_aux_btn_menu_debug = NULL;
lv_obj_t * ui_aux_buttons_container = NULL;
lv_obj_t * ui_aux_btn_feed_pump = NULL;
lv_obj_t * ui_aux_label_feed_pump = NULL;
lv_obj_t * ui_aux_btn_hp_pump = NULL;
lv_obj_t * ui_aux_label_hp_pump = NULL;
lv_obj_t * ui_aux_btn_flushing_cycle = NULL;
lv_obj_t * ui_aux_label_flushing_cycle = NULL;
lv_obj_t * ui_aux_btn_tank_test = NULL;
lv_obj_t * ui_aux_label_tank_test = NULL;
lv_obj_t * ui_aux_screen_container_1 = NULL;
lv_obj_t * ui_aux_screen_label_inputs = NULL;
lv_obj_t * ui_aux_screen_container_2 = NULL;
lv_obj_t * ui_aux_screen_label_outputs = NULL;
lv_obj_t * ui_aux_screen_btn_hp_fan = NULL;
lv_obj_t * ui_aux_screen_label_hp_fan = NULL;
lv_obj_t * ui_aux_screen_btn_aux = NULL;
lv_obj_t * ui_aux_screen_label_aux = NULL;
lv_obj_t * ui_aux_screen_btn_tank_diverting = NULL;
lv_obj_t * ui_aux_screen_label__tank_diverting = NULL;
lv_obj_t * ui_aux_screen_input_4 = NULL;
lv_obj_t * ui_aux_screen_label_input_4 = NULL;
lv_obj_t * ui_aux_screen_label_input_4_value = NULL;
lv_obj_t * ui_aux_screen_input_5 = NULL;
lv_obj_t * ui_aux_screen_label_input_5 = NULL;
lv_obj_t * ui_aux_screen_label_input_5_value = NULL;
lv_obj_t * ui_aux_screen_input_6 = NULL;
lv_obj_t * ui_aux_screen_label_input_6 = NULL;
lv_obj_t * ui_aux_screen_label_input_6_value = NULL;
lv_obj_t * ui_aux_screen_input_7 = NULL;
lv_obj_t * ui_aux_screen_label_input_7 = NULL;
lv_obj_t * ui_aux_screen_label_input_7_value = NULL;
lv_obj_t * ui_aux_screen_input_8 = NULL;
lv_obj_t * ui_aux_screen_label_input_8 = NULL;
lv_obj_t * ui_aux_screen_label_input_8_value = NULL;
lv_obj_t * ui_aux_screen_input_9 = NULL;
lv_obj_t * ui_aux_screen_label_input_9 = NULL;
lv_obj_t * ui_aux_screen_label_input_9_value = NULL;
// event funtions
void ui_event_btn_menu_aux(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_aux_screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_aux_screen_screen_init);
    }
}

// build funtions

void ui_aux_screen_screen_init(void)
{
    ui_aux_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_aux_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_aux_screen, lv_color_hex(0x596684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_top_bar = lv_image_create(ui_aux_screen);
    lv_image_set_src(ui_aux_top_bar, &ui_img_top_bar_png);
    lv_obj_set_width(ui_aux_top_bar, LV_SIZE_CONTENT);   /// 681
    lv_obj_set_height(ui_aux_top_bar, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_aux_top_bar, 37);
    lv_obj_set_y(ui_aux_top_bar, -218);
    lv_obj_set_align(ui_aux_top_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aux_top_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_aux_top_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aux_image_ce = lv_image_create(ui_aux_screen);
    lv_image_set_src(ui_aux_image_ce, &ui_img_625624875);
    lv_obj_set_width(ui_aux_image_ce, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_aux_image_ce, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_aux_image_ce, 350);
    lv_obj_set_y(ui_aux_image_ce, -221);
    lv_obj_set_align(ui_aux_image_ce, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aux_image_ce, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_aux_image_ce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aux_menu_bar = lv_image_create(ui_aux_screen);
    lv_image_set_src(ui_aux_menu_bar, &ui_img_menu_bar_png);
    lv_obj_set_width(ui_aux_menu_bar, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_aux_menu_bar, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_aux_menu_bar, -363);
    lv_obj_set_y(ui_aux_menu_bar, 0);
    lv_obj_set_align(ui_aux_menu_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aux_menu_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_aux_menu_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aux_screen_btn_img_aux = lv_image_create(ui_aux_screen);
    lv_image_set_src(ui_aux_screen_btn_img_aux, &ui_img_btn_aux_png);
    lv_obj_set_width(ui_aux_screen_btn_img_aux, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_aux_screen_btn_img_aux, LV_SIZE_CONTENT);    /// 66
    lv_obj_set_x(ui_aux_screen_btn_img_aux, -360);
    lv_obj_set_y(ui_aux_screen_btn_img_aux, 138);
    lv_obj_set_align(ui_aux_screen_btn_img_aux, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aux_screen_btn_img_aux, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_aux_screen_btn_img_aux, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aux_menu_container = lv_obj_create(ui_aux_screen);
    lv_obj_remove_style_all(ui_aux_menu_container);
    lv_obj_set_width(ui_aux_menu_container, 83);
    lv_obj_set_height(ui_aux_menu_container, 488);
    lv_obj_set_x(ui_aux_menu_container, -2);
    lv_obj_set_y(ui_aux_menu_container, -2);
    lv_obj_remove_flag(ui_aux_menu_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aux_btn_menu_home = lv_image_create(ui_aux_menu_container);
    lv_obj_set_width(ui_aux_btn_menu_home, 74);
    lv_obj_set_height(ui_aux_btn_menu_home, 65);
    lv_obj_set_x(ui_aux_btn_menu_home, 5);
    lv_obj_set_y(ui_aux_btn_menu_home, -412);
    lv_obj_set_align(ui_aux_btn_menu_home, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_aux_btn_menu_home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_aux_btn_menu_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_aux_btn_menu_home, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_aux_btn_menu_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_btn_menu_main = lv_image_create(ui_aux_menu_container);
    lv_obj_set_width(ui_aux_btn_menu_main, 74);
    lv_obj_set_height(ui_aux_btn_menu_main, 59);
    lv_obj_set_x(ui_aux_btn_menu_main, 5);
    lv_obj_set_y(ui_aux_btn_menu_main, -345);
    lv_obj_set_align(ui_aux_btn_menu_main, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_aux_btn_menu_main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_aux_btn_menu_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_aux_btn_menu_main, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_aux_btn_menu_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_btn_menu_settings = lv_image_create(ui_aux_menu_container);
    lv_obj_set_width(ui_aux_btn_menu_settings, 74);
    lv_obj_set_height(ui_aux_btn_menu_settings, 59);
    lv_obj_set_x(ui_aux_btn_menu_settings, 5);
    lv_obj_set_y(ui_aux_btn_menu_settings, -278);
    lv_obj_set_align(ui_aux_btn_menu_settings, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_aux_btn_menu_settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_aux_btn_menu_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_aux_btn_menu_settings, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_aux_btn_menu_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_btn_menu_autom = lv_image_create(ui_aux_menu_container);
    lv_obj_set_width(ui_aux_btn_menu_autom, 74);
    lv_obj_set_height(ui_aux_btn_menu_autom, 59);
    lv_obj_set_x(ui_aux_btn_menu_autom, 5);
    lv_obj_set_y(ui_aux_btn_menu_autom, -212);
    lv_obj_set_align(ui_aux_btn_menu_autom, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_aux_btn_menu_autom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_aux_btn_menu_autom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_aux_btn_menu_autom, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_aux_btn_menu_autom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_btn_menu_log = lv_image_create(ui_aux_menu_container);
    lv_obj_set_width(ui_aux_btn_menu_log, 74);
    lv_obj_set_height(ui_aux_btn_menu_log, 59);
    lv_obj_set_x(ui_aux_btn_menu_log, 5);
    lv_obj_set_y(ui_aux_btn_menu_log, -146);
    lv_obj_set_align(ui_aux_btn_menu_log, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_aux_btn_menu_log, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_aux_btn_menu_log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_aux_btn_menu_log, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_aux_btn_menu_log, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_btn_menu_aux = lv_image_create(ui_aux_menu_container);
    lv_obj_set_width(ui_aux_btn_menu_aux, 74);
    lv_obj_set_height(ui_aux_btn_menu_aux, 59);
    lv_obj_set_x(ui_aux_btn_menu_aux, 5);
    lv_obj_set_y(ui_aux_btn_menu_aux, -80);
    lv_obj_set_align(ui_aux_btn_menu_aux, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_aux_btn_menu_aux, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_aux_btn_menu_aux, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_aux_btn_menu_aux, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_aux_btn_menu_aux, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_btn_menu_debug = lv_image_create(ui_aux_menu_container);
    lv_obj_set_width(ui_aux_btn_menu_debug, 74);
    lv_obj_set_height(ui_aux_btn_menu_debug, 59);
    lv_obj_set_x(ui_aux_btn_menu_debug, 5);
    lv_obj_set_y(ui_aux_btn_menu_debug, -12);
    lv_obj_set_align(ui_aux_btn_menu_debug, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_aux_btn_menu_debug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_aux_btn_menu_debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_aux_btn_menu_debug, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_aux_btn_menu_debug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_buttons_container = lv_obj_create(ui_aux_screen);
    lv_obj_remove_style_all(ui_aux_buttons_container);
    lv_obj_set_width(ui_aux_buttons_container, 684);
    lv_obj_set_height(ui_aux_buttons_container, 65);
    lv_obj_set_x(ui_aux_buttons_container, 32);
    lv_obj_set_y(ui_aux_buttons_container, 185);
    lv_obj_set_align(ui_aux_buttons_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_aux_buttons_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aux_btn_feed_pump = lv_imagebutton_create(ui_aux_buttons_container);
    lv_imagebutton_set_src(ui_aux_btn_feed_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_feed_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_aux_btn_feed_pump, 66);
    lv_obj_set_width(ui_aux_btn_feed_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_aux_btn_feed_pump, 7);
    lv_obj_set_y(ui_aux_btn_feed_pump, 0);
    lv_obj_set_align(ui_aux_btn_feed_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_aux_btn_feed_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_aux_btn_feed_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_aux_btn_feed_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_aux_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_aux_btn_feed_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_aux_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_aux_label_feed_pump = lv_label_create(ui_aux_btn_feed_pump);
    lv_obj_set_width(ui_aux_label_feed_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_label_feed_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aux_label_feed_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux_label_feed_pump, "FEED PUMP");
    lv_obj_set_style_text_align(ui_aux_label_feed_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_label_feed_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_btn_hp_pump = lv_imagebutton_create(ui_aux_buttons_container);
    lv_imagebutton_set_src(ui_aux_btn_hp_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_hp_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_aux_btn_hp_pump, 66);
    lv_obj_set_width(ui_aux_btn_hp_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_aux_btn_hp_pump, 176);
    lv_obj_set_y(ui_aux_btn_hp_pump, 0);
    lv_obj_set_align(ui_aux_btn_hp_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_aux_btn_hp_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_aux_btn_hp_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_aux_btn_hp_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_aux_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_aux_btn_hp_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_aux_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_aux_label_hp_pump = lv_label_create(ui_aux_btn_hp_pump);
    lv_obj_set_width(ui_aux_label_hp_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_label_hp_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aux_label_hp_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux_label_hp_pump, "H.P. PUMP");
    lv_obj_set_style_text_align(ui_aux_label_hp_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_label_hp_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_btn_flushing_cycle = lv_imagebutton_create(ui_aux_buttons_container);
    lv_imagebutton_set_src(ui_aux_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_aux_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_obj_set_height(ui_aux_btn_flushing_cycle, 66);
    lv_obj_set_width(ui_aux_btn_flushing_cycle, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_aux_btn_flushing_cycle, 351);
    lv_obj_set_y(ui_aux_btn_flushing_cycle, 0);
    lv_obj_set_align(ui_aux_btn_flushing_cycle, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_aux_btn_flushing_cycle, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_aux_btn_flushing_cycle, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_aux_btn_flushing_cycle, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_aux_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_aux_btn_flushing_cycle, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_aux_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_aux_label_flushing_cycle = lv_label_create(ui_aux_btn_flushing_cycle);
    lv_obj_set_width(ui_aux_label_flushing_cycle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_label_flushing_cycle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aux_label_flushing_cycle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux_label_flushing_cycle, "FLUSHING\nCYCLE");
    lv_obj_set_style_text_align(ui_aux_label_flushing_cycle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_label_flushing_cycle, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_btn_tank_test = lv_imagebutton_create(ui_aux_buttons_container);
    lv_imagebutton_set_src(ui_aux_btn_tank_test, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_tank_test, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_aux_btn_tank_test, 66);
    lv_obj_set_width(ui_aux_btn_tank_test, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_aux_btn_tank_test, 522);
    lv_obj_set_y(ui_aux_btn_tank_test, 0);
    lv_obj_set_align(ui_aux_btn_tank_test, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_aux_btn_tank_test, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_aux_btn_tank_test, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_aux_btn_tank_test, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_aux_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_aux_btn_tank_test, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_aux_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_aux_label_tank_test = lv_label_create(ui_aux_btn_tank_test);
    lv_obj_set_width(ui_aux_label_tank_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_label_tank_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aux_label_tank_test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux_label_tank_test, "WATER\nTO TANK");
    lv_obj_set_style_text_align(ui_aux_label_tank_test, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_label_tank_test, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_container_1 = lv_obj_create(ui_aux_screen);
    lv_obj_remove_style_all(ui_aux_screen_container_1);
    lv_obj_set_width(ui_aux_screen_container_1, 479);
    lv_obj_set_height(ui_aux_screen_container_1, 327);
    lv_obj_set_x(ui_aux_screen_container_1, -56);
    lv_obj_set_y(ui_aux_screen_container_1, -19);
    lv_obj_set_align(ui_aux_screen_container_1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_aux_screen_container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux_screen_container_1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux_screen_container_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux_screen_container_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_inputs = lv_label_create(ui_aux_screen_container_1);
    lv_obj_set_width(ui_aux_screen_label_inputs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_inputs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_inputs, -3);
    lv_obj_set_y(ui_aux_screen_label_inputs, 16);
    lv_obj_set_align(ui_aux_screen_label_inputs, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_aux_screen_label_inputs, "INPUTS & SENSORS");
    lv_obj_set_style_text_color(ui_aux_screen_label_inputs, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_inputs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aux_screen_label_inputs, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_inputs, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_container_2 = lv_obj_create(ui_aux_screen);
    lv_obj_remove_style_all(ui_aux_screen_container_2);
    lv_obj_set_width(ui_aux_screen_container_2, 183);
    lv_obj_set_height(ui_aux_screen_container_2, 327);
    lv_obj_set_x(ui_aux_screen_container_2, 285);
    lv_obj_set_y(ui_aux_screen_container_2, -19);
    lv_obj_set_align(ui_aux_screen_container_2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_aux_screen_container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux_screen_container_2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux_screen_container_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux_screen_container_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_outputs = lv_label_create(ui_aux_screen_container_2);
    lv_obj_set_width(ui_aux_screen_label_outputs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_outputs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_outputs, -3);
    lv_obj_set_y(ui_aux_screen_label_outputs, 16);
    lv_obj_set_align(ui_aux_screen_label_outputs, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_aux_screen_label_outputs, "AUX OUTPUTS");
    lv_obj_set_style_text_color(ui_aux_screen_label_outputs, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_outputs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aux_screen_label_outputs, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_outputs, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_btn_hp_fan = lv_imagebutton_create(ui_aux_screen);
    lv_imagebutton_set_src(ui_aux_screen_btn_hp_fan, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_aux_screen_btn_hp_fan, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_screen_btn_hp_fan, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_aux_screen_btn_hp_fan, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_obj_set_height(ui_aux_screen_btn_hp_fan, 66);
    lv_obj_set_width(ui_aux_screen_btn_hp_fan, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_aux_screen_btn_hp_fan, 607);
    lv_obj_set_y(ui_aux_screen_btn_hp_fan, -92);
    lv_obj_set_align(ui_aux_screen_btn_hp_fan, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_aux_screen_btn_hp_fan, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_aux_screen_btn_hp_fan, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_btn_hp_fan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_aux_screen_btn_hp_fan, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_aux_screen_btn_hp_fan, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_aux_screen_btn_hp_fan, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_aux_screen_btn_hp_fan, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_aux_screen_label_hp_fan = lv_label_create(ui_aux_screen_btn_hp_fan);
    lv_obj_set_width(ui_aux_screen_label_hp_fan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_hp_fan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aux_screen_label_hp_fan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux_screen_label_hp_fan, "H.P. PUMP\nFAN");
    lv_obj_set_style_text_align(ui_aux_screen_label_hp_fan, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_hp_fan, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_btn_aux = lv_imagebutton_create(ui_aux_screen);
    lv_imagebutton_set_src(ui_aux_screen_btn_aux, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_aux_screen_btn_aux, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_screen_btn_aux, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_aux_screen_btn_aux, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_obj_set_height(ui_aux_screen_btn_aux, 66);
    lv_obj_set_width(ui_aux_screen_btn_aux, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_aux_screen_btn_aux, 607);
    lv_obj_set_y(ui_aux_screen_btn_aux, -7);
    lv_obj_set_align(ui_aux_screen_btn_aux, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_aux_screen_btn_aux, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_aux_screen_btn_aux, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_btn_aux, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_aux_screen_btn_aux, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_aux_screen_btn_aux, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_aux_screen_btn_aux, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_aux_screen_btn_aux, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_aux_screen_label_aux = lv_label_create(ui_aux_screen_btn_aux);
    lv_obj_set_width(ui_aux_screen_label_aux, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_aux, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aux_screen_label_aux, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux_screen_label_aux, "AUXILIARY\nFAN");
    lv_obj_set_style_text_align(ui_aux_screen_label_aux, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_aux, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_btn_tank_diverting = lv_imagebutton_create(ui_aux_screen);
    lv_imagebutton_set_src(ui_aux_screen_btn_tank_diverting, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png,
                           NULL);
    lv_imagebutton_set_src(ui_aux_screen_btn_tank_diverting, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_aux_screen_btn_tank_diverting, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_aux_screen_btn_tank_diverting, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_aux_screen_btn_tank_diverting, 66);
    lv_obj_set_width(ui_aux_screen_btn_tank_diverting, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_aux_screen_btn_tank_diverting, 607);
    lv_obj_set_y(ui_aux_screen_btn_tank_diverting, 76);
    lv_obj_set_align(ui_aux_screen_btn_tank_diverting, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_aux_screen_btn_tank_diverting, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_aux_screen_btn_tank_diverting, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_btn_tank_diverting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_aux_screen_btn_tank_diverting, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_aux_screen_btn_tank_diverting, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_aux_screen_btn_tank_diverting, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_aux_screen_btn_tank_diverting, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_aux_screen_label__tank_diverting = lv_label_create(ui_aux_screen_btn_tank_diverting);
    lv_obj_set_width(ui_aux_screen_label__tank_diverting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label__tank_diverting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aux_screen_label__tank_diverting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux_screen_label__tank_diverting, "TANK 1");
    lv_obj_set_style_text_align(ui_aux_screen_label__tank_diverting, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label__tank_diverting, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_input_4 = lv_obj_create(ui_aux_screen);
    lv_obj_set_width(ui_aux_screen_input_4, 176);
    lv_obj_set_height(ui_aux_screen_input_4, 79);
    lv_obj_set_x(ui_aux_screen_input_4, -496);
    lv_obj_set_y(ui_aux_screen_input_4, 106);
    lv_obj_set_align(ui_aux_screen_input_4, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_aux_screen_input_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_aux_screen_input_4, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux_screen_input_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_aux_screen_input_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_aux_screen_input_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aux_screen_input_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aux_screen_input_4, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_aux_screen_input_4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_aux_screen_input_4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_aux_screen_input_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_aux_screen_input_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_aux_screen_input_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_aux_screen_input_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_aux_screen_input_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_4 = lv_label_create(ui_aux_screen_input_4);
    lv_obj_set_width(ui_aux_screen_label_input_4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_input_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_4, 0);
    lv_obj_set_y(ui_aux_screen_label_input_4, 8);
    lv_obj_set_align(ui_aux_screen_label_input_4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_aux_screen_label_input_4, "FEED WATER TEMP");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_4, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_4, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_4_value = lv_label_create(ui_aux_screen_input_4);
    lv_obj_set_width(ui_aux_screen_label_input_4_value, 169);
    lv_obj_set_height(ui_aux_screen_label_input_4_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_4_value, 3);
    lv_obj_set_y(ui_aux_screen_label_input_4_value, 12);
    lv_obj_set_align(ui_aux_screen_label_input_4_value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_aux_screen_label_input_4_value, "19 °C");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_4_value, lv_color_hex(0x3A72EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_4_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aux_screen_label_input_4_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_4_value, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_input_5 = lv_obj_create(ui_aux_screen);
    lv_obj_set_width(ui_aux_screen_input_5, 176);
    lv_obj_set_height(ui_aux_screen_input_5, 79);
    lv_obj_set_x(ui_aux_screen_input_5, -496);
    lv_obj_set_y(ui_aux_screen_input_5, 201);
    lv_obj_set_align(ui_aux_screen_input_5, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_aux_screen_input_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_aux_screen_input_5, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux_screen_input_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_aux_screen_input_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_aux_screen_input_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aux_screen_input_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aux_screen_input_5, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_aux_screen_input_5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_aux_screen_input_5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_aux_screen_input_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_aux_screen_input_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_aux_screen_input_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_aux_screen_input_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_aux_screen_input_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_5 = lv_label_create(ui_aux_screen_input_5);
    lv_obj_set_width(ui_aux_screen_label_input_5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_input_5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_5, 0);
    lv_obj_set_y(ui_aux_screen_label_input_5, 8);
    lv_obj_set_align(ui_aux_screen_label_input_5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_aux_screen_label_input_5, "H.P. PUMP TEMP");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_5, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_5, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_5_value = lv_label_create(ui_aux_screen_input_5);
    lv_obj_set_width(ui_aux_screen_label_input_5_value, 169);
    lv_obj_set_height(ui_aux_screen_label_input_5_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_5_value, 3);
    lv_obj_set_y(ui_aux_screen_label_input_5_value, 12);
    lv_obj_set_align(ui_aux_screen_label_input_5_value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_aux_screen_label_input_5_value, "78 °C");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_5_value, lv_color_hex(0x3A72EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_5_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aux_screen_label_input_5_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_5_value, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_input_6 = lv_obj_create(ui_aux_screen);
    lv_obj_set_width(ui_aux_screen_input_6, 176);
    lv_obj_set_height(ui_aux_screen_input_6, 79);
    lv_obj_set_x(ui_aux_screen_input_6, -496);
    lv_obj_set_y(ui_aux_screen_input_6, 295);
    lv_obj_set_align(ui_aux_screen_input_6, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_aux_screen_input_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_aux_screen_input_6, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux_screen_input_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_aux_screen_input_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_aux_screen_input_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aux_screen_input_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aux_screen_input_6, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_aux_screen_input_6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_aux_screen_input_6, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_aux_screen_input_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_aux_screen_input_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_aux_screen_input_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_aux_screen_input_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_aux_screen_input_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_6 = lv_label_create(ui_aux_screen_input_6);
    lv_obj_set_width(ui_aux_screen_label_input_6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_input_6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_6, 0);
    lv_obj_set_y(ui_aux_screen_label_input_6, 8);
    lv_obj_set_align(ui_aux_screen_label_input_6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_aux_screen_label_input_6, "FEED PUMP TEMP");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_6, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_6, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_6_value = lv_label_create(ui_aux_screen_input_6);
    lv_obj_set_width(ui_aux_screen_label_input_6_value, 169);
    lv_obj_set_height(ui_aux_screen_label_input_6_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_6_value, 3);
    lv_obj_set_y(ui_aux_screen_label_input_6_value, 12);
    lv_obj_set_align(ui_aux_screen_label_input_6_value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_aux_screen_label_input_6_value, "53 °C");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_6_value, lv_color_hex(0x3A72EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_6_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aux_screen_label_input_6_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_6_value, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_input_7 = lv_obj_create(ui_aux_screen);
    lv_obj_set_width(ui_aux_screen_input_7, 176);
    lv_obj_set_height(ui_aux_screen_input_7, 79);
    lv_obj_set_x(ui_aux_screen_input_7, -250);
    lv_obj_set_y(ui_aux_screen_input_7, 106);
    lv_obj_set_align(ui_aux_screen_input_7, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_aux_screen_input_7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_aux_screen_input_7, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux_screen_input_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_aux_screen_input_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_aux_screen_input_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aux_screen_input_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aux_screen_input_7, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_aux_screen_input_7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_aux_screen_input_7, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_aux_screen_input_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_aux_screen_input_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_aux_screen_input_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_aux_screen_input_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_aux_screen_input_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_7 = lv_label_create(ui_aux_screen_input_7);
    lv_obj_set_width(ui_aux_screen_label_input_7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_input_7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_7, 0);
    lv_obj_set_y(ui_aux_screen_label_input_7, 8);
    lv_obj_set_align(ui_aux_screen_label_input_7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_aux_screen_label_input_7, "H.P. RELAY TEMP");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_7, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_7, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_7_value = lv_label_create(ui_aux_screen_input_7);
    lv_obj_set_width(ui_aux_screen_label_input_7_value, 169);
    lv_obj_set_height(ui_aux_screen_label_input_7_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_7_value, 3);
    lv_obj_set_y(ui_aux_screen_label_input_7_value, 12);
    lv_obj_set_align(ui_aux_screen_label_input_7_value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_aux_screen_label_input_7_value, "42 °C");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_7_value, lv_color_hex(0x3A72EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_7_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aux_screen_label_input_7_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_7_value, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_input_8 = lv_obj_create(ui_aux_screen);
    lv_obj_set_width(ui_aux_screen_input_8, 176);
    lv_obj_set_height(ui_aux_screen_input_8, 79);
    lv_obj_set_x(ui_aux_screen_input_8, -250);
    lv_obj_set_y(ui_aux_screen_input_8, 201);
    lv_obj_set_align(ui_aux_screen_input_8, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_aux_screen_input_8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_aux_screen_input_8, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux_screen_input_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_aux_screen_input_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_aux_screen_input_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aux_screen_input_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aux_screen_input_8, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_aux_screen_input_8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_aux_screen_input_8, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_aux_screen_input_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_aux_screen_input_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_aux_screen_input_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_aux_screen_input_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_aux_screen_input_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_8 = lv_label_create(ui_aux_screen_input_8);
    lv_obj_set_width(ui_aux_screen_label_input_8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_input_8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_8, 0);
    lv_obj_set_y(ui_aux_screen_label_input_8, 8);
    lv_obj_set_align(ui_aux_screen_label_input_8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_aux_screen_label_input_8, "RELAYS BOX TEMP");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_8, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_8, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_8_value = lv_label_create(ui_aux_screen_input_8);
    lv_obj_set_width(ui_aux_screen_label_input_8_value, 169);
    lv_obj_set_height(ui_aux_screen_label_input_8_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_8_value, 3);
    lv_obj_set_y(ui_aux_screen_label_input_8_value, 12);
    lv_obj_set_align(ui_aux_screen_label_input_8_value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_aux_screen_label_input_8_value, "32 °C");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_8_value, lv_color_hex(0x3A72EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_8_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aux_screen_label_input_8_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_8_value, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_input_9 = lv_obj_create(ui_aux_screen);
    lv_obj_set_width(ui_aux_screen_input_9, 176);
    lv_obj_set_height(ui_aux_screen_input_9, 79);
    lv_obj_set_x(ui_aux_screen_input_9, -250);
    lv_obj_set_y(ui_aux_screen_input_9, 295);
    lv_obj_set_align(ui_aux_screen_input_9, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_aux_screen_input_9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_aux_screen_input_9, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux_screen_input_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_aux_screen_input_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_aux_screen_input_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aux_screen_input_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aux_screen_input_9, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_aux_screen_input_9, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_aux_screen_input_9, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_aux_screen_input_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_aux_screen_input_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_aux_screen_input_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_aux_screen_input_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_aux_screen_input_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_9 = lv_label_create(ui_aux_screen_input_9);
    lv_obj_set_width(ui_aux_screen_label_input_9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux_screen_label_input_9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_9, 0);
    lv_obj_set_y(ui_aux_screen_label_input_9, 8);
    lv_obj_set_align(ui_aux_screen_label_input_9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_aux_screen_label_input_9, "--- ---");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_9, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_9, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux_screen_label_input_9_value = lv_label_create(ui_aux_screen_input_9);
    lv_obj_set_width(ui_aux_screen_label_input_9_value, 169);
    lv_obj_set_height(ui_aux_screen_label_input_9_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux_screen_label_input_9_value, 3);
    lv_obj_set_y(ui_aux_screen_label_input_9_value, 12);
    lv_obj_set_align(ui_aux_screen_label_input_9_value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_aux_screen_label_input_9_value, "--- ---");
    lv_obj_set_style_text_color(ui_aux_screen_label_input_9_value, lv_color_hex(0x3A72EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aux_screen_label_input_9_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aux_screen_label_input_9_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aux_screen_label_input_9_value, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_aux_btn_menu_aux, ui_event_btn_menu_aux, LV_EVENT_ALL, NULL);

}

void ui_aux_screen_screen_destroy(void)
{
    if(ui_aux_screen) lv_obj_del(ui_aux_screen);

    // NULL screen variables
    ui_aux_screen = NULL;
    ui_aux_top_bar = NULL;
    ui_aux_image_ce = NULL;
    ui_aux_menu_bar = NULL;
    ui_aux_screen_btn_img_aux = NULL;
    ui_aux_menu_container = NULL;
    ui_aux_btn_menu_home = NULL;
    ui_aux_btn_menu_main = NULL;
    ui_aux_btn_menu_settings = NULL;
    ui_aux_btn_menu_autom = NULL;
    ui_aux_btn_menu_log = NULL;
    ui_aux_btn_menu_aux = NULL;
    ui_aux_btn_menu_debug = NULL;
    ui_aux_buttons_container = NULL;
    ui_aux_btn_feed_pump = NULL;
    ui_aux_label_feed_pump = NULL;
    ui_aux_btn_hp_pump = NULL;
    ui_aux_label_hp_pump = NULL;
    ui_aux_btn_flushing_cycle = NULL;
    ui_aux_label_flushing_cycle = NULL;
    ui_aux_btn_tank_test = NULL;
    ui_aux_label_tank_test = NULL;
    ui_aux_screen_container_1 = NULL;
    ui_aux_screen_label_inputs = NULL;
    ui_aux_screen_container_2 = NULL;
    ui_aux_screen_label_outputs = NULL;
    ui_aux_screen_btn_hp_fan = NULL;
    ui_aux_screen_label_hp_fan = NULL;
    ui_aux_screen_btn_aux = NULL;
    ui_aux_screen_label_aux = NULL;
    ui_aux_screen_btn_tank_diverting = NULL;
    ui_aux_screen_label__tank_diverting = NULL;
    ui_aux_screen_input_4 = NULL;
    ui_aux_screen_label_input_4 = NULL;
    ui_aux_screen_label_input_4_value = NULL;
    ui_aux_screen_input_5 = NULL;
    ui_aux_screen_label_input_5 = NULL;
    ui_aux_screen_label_input_5_value = NULL;
    ui_aux_screen_input_6 = NULL;
    ui_aux_screen_label_input_6 = NULL;
    ui_aux_screen_label_input_6_value = NULL;
    ui_aux_screen_input_7 = NULL;
    ui_aux_screen_label_input_7 = NULL;
    ui_aux_screen_label_input_7_value = NULL;
    ui_aux_screen_input_8 = NULL;
    ui_aux_screen_label_input_8 = NULL;
    ui_aux_screen_label_input_8_value = NULL;
    ui_aux_screen_input_9 = NULL;
    ui_aux_screen_label_input_9 = NULL;
    ui_aux_screen_label_input_9_value = NULL;

}
