// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 07 - Debug Screen

#include "../ui.h"

lv_obj_t * ui_debug_screen = NULL;
lv_obj_t * ui_debug_top_bar = NULL;
lv_obj_t * ui_debug_image_ce = NULL;
lv_obj_t * ui_debug_menu_bar = NULL;
lv_obj_t * ui_debug_screen_btn_img_debug = NULL;
lv_obj_t * ui_debug_menu_container = NULL;
lv_obj_t * ui_debug_btn_menu_home = NULL;
lv_obj_t * ui_debug_btn_menu_main = NULL;
lv_obj_t * ui_debug_btn_menu_settings = NULL;
lv_obj_t * ui_debug_btn_menu_autom = NULL;
lv_obj_t * ui_debug_btn_menu_log = NULL;
lv_obj_t * ui_debug_btn_menu_aux = NULL;
lv_obj_t * ui_debug_btn_menu_debug = NULL;
lv_obj_t * ui_debug_screen_container_1 = NULL;
lv_obj_t * ui_debug_screen_label_1 = NULL;
lv_obj_t * ui_debug_screen_textarea_1 = NULL;
lv_obj_t * ui_debug_screen_container_2 = NULL;
lv_obj_t * ui_debug_screen_label_2 = NULL;
lv_obj_t * ui_debug_screen_textarea_2 = NULL;
// event funtions
void ui_event_btn_menu_debug(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_debug_screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_debug_screen_screen_init);
    }
}

// build funtions

void ui_debug_screen_screen_init(void)
{
    ui_debug_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_debug_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_debug_screen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_debug_screen, lv_color_hex(0x596684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debug_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_top_bar = lv_image_create(ui_debug_screen);
    lv_image_set_src(ui_debug_top_bar, &ui_img_top_bar_png);
    lv_obj_set_width(ui_debug_top_bar, LV_SIZE_CONTENT);   /// 681
    lv_obj_set_height(ui_debug_top_bar, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_debug_top_bar, 37);
    lv_obj_set_y(ui_debug_top_bar, -218);
    lv_obj_set_align(ui_debug_top_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_debug_top_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_debug_top_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_debug_image_ce = lv_image_create(ui_debug_screen);
    lv_image_set_src(ui_debug_image_ce, &ui_img_625624875);
    lv_obj_set_width(ui_debug_image_ce, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_debug_image_ce, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_debug_image_ce, 350);
    lv_obj_set_y(ui_debug_image_ce, -221);
    lv_obj_set_align(ui_debug_image_ce, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_debug_image_ce, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_debug_image_ce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_debug_menu_bar = lv_image_create(ui_debug_screen);
    lv_image_set_src(ui_debug_menu_bar, &ui_img_menu_bar_png);
    lv_obj_set_width(ui_debug_menu_bar, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_debug_menu_bar, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_debug_menu_bar, -363);
    lv_obj_set_y(ui_debug_menu_bar, 0);
    lv_obj_set_align(ui_debug_menu_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_debug_menu_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_debug_menu_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_debug_screen_btn_img_debug = lv_image_create(ui_debug_screen);
    lv_image_set_src(ui_debug_screen_btn_img_debug, &ui_img_btn_debug_png);
    lv_obj_set_width(ui_debug_screen_btn_img_debug, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_debug_screen_btn_img_debug, LV_SIZE_CONTENT);    /// 66
    lv_obj_set_x(ui_debug_screen_btn_img_debug, -360);
    lv_obj_set_y(ui_debug_screen_btn_img_debug, 207);
    lv_obj_set_align(ui_debug_screen_btn_img_debug, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_debug_screen_btn_img_debug, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_debug_screen_btn_img_debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_debug_menu_container = lv_obj_create(ui_debug_screen);
    lv_obj_remove_style_all(ui_debug_menu_container);
    lv_obj_set_width(ui_debug_menu_container, 83);
    lv_obj_set_height(ui_debug_menu_container, 488);
    lv_obj_set_x(ui_debug_menu_container, -2);
    lv_obj_set_y(ui_debug_menu_container, -2);
    lv_obj_remove_flag(ui_debug_menu_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_debug_btn_menu_home = lv_image_create(ui_debug_menu_container);
    lv_obj_set_width(ui_debug_btn_menu_home, 74);
    lv_obj_set_height(ui_debug_btn_menu_home, 65);
    lv_obj_set_x(ui_debug_btn_menu_home, 5);
    lv_obj_set_y(ui_debug_btn_menu_home, -412);
    lv_obj_set_align(ui_debug_btn_menu_home, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_debug_btn_menu_home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_debug_btn_menu_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_debug_btn_menu_home, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_debug_btn_menu_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_btn_menu_main = lv_image_create(ui_debug_menu_container);
    lv_obj_set_width(ui_debug_btn_menu_main, 74);
    lv_obj_set_height(ui_debug_btn_menu_main, 59);
    lv_obj_set_x(ui_debug_btn_menu_main, 5);
    lv_obj_set_y(ui_debug_btn_menu_main, -345);
    lv_obj_set_align(ui_debug_btn_menu_main, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_debug_btn_menu_main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_debug_btn_menu_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_debug_btn_menu_main, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_debug_btn_menu_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_btn_menu_settings = lv_image_create(ui_debug_menu_container);
    lv_obj_set_width(ui_debug_btn_menu_settings, 74);
    lv_obj_set_height(ui_debug_btn_menu_settings, 59);
    lv_obj_set_x(ui_debug_btn_menu_settings, 5);
    lv_obj_set_y(ui_debug_btn_menu_settings, -278);
    lv_obj_set_align(ui_debug_btn_menu_settings, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_debug_btn_menu_settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_debug_btn_menu_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_debug_btn_menu_settings, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_debug_btn_menu_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_btn_menu_autom = lv_image_create(ui_debug_menu_container);
    lv_obj_set_width(ui_debug_btn_menu_autom, 74);
    lv_obj_set_height(ui_debug_btn_menu_autom, 59);
    lv_obj_set_x(ui_debug_btn_menu_autom, 5);
    lv_obj_set_y(ui_debug_btn_menu_autom, -212);
    lv_obj_set_align(ui_debug_btn_menu_autom, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_debug_btn_menu_autom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_debug_btn_menu_autom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_debug_btn_menu_autom, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_debug_btn_menu_autom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_btn_menu_log = lv_image_create(ui_debug_menu_container);
    lv_obj_set_width(ui_debug_btn_menu_log, 74);
    lv_obj_set_height(ui_debug_btn_menu_log, 59);
    lv_obj_set_x(ui_debug_btn_menu_log, 5);
    lv_obj_set_y(ui_debug_btn_menu_log, -146);
    lv_obj_set_align(ui_debug_btn_menu_log, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_debug_btn_menu_log, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_debug_btn_menu_log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_debug_btn_menu_log, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_debug_btn_menu_log, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_btn_menu_aux = lv_image_create(ui_debug_menu_container);
    lv_obj_set_width(ui_debug_btn_menu_aux, 74);
    lv_obj_set_height(ui_debug_btn_menu_aux, 59);
    lv_obj_set_x(ui_debug_btn_menu_aux, 5);
    lv_obj_set_y(ui_debug_btn_menu_aux, -80);
    lv_obj_set_align(ui_debug_btn_menu_aux, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_debug_btn_menu_aux, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_debug_btn_menu_aux, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_debug_btn_menu_aux, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_debug_btn_menu_aux, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_btn_menu_debug = lv_image_create(ui_debug_menu_container);
    lv_obj_set_width(ui_debug_btn_menu_debug, 74);
    lv_obj_set_height(ui_debug_btn_menu_debug, 59);
    lv_obj_set_x(ui_debug_btn_menu_debug, 5);
    lv_obj_set_y(ui_debug_btn_menu_debug, -12);
    lv_obj_set_align(ui_debug_btn_menu_debug, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_debug_btn_menu_debug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_debug_btn_menu_debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_debug_btn_menu_debug, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_debug_btn_menu_debug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_screen_container_1 = lv_obj_create(ui_debug_screen);
    lv_obj_remove_style_all(ui_debug_screen_container_1);
    lv_obj_set_width(ui_debug_screen_container_1, 304);
    lv_obj_set_height(ui_debug_screen_container_1, 391);
    lv_obj_set_x(ui_debug_screen_container_1, -140);
    lv_obj_set_y(ui_debug_screen_container_1, 15);
    lv_obj_set_align(ui_debug_screen_container_1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_debug_screen_container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_debug_screen_container_1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_debug_screen_container_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debug_screen_container_1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_screen_label_1 = lv_label_create(ui_debug_screen_container_1);
    lv_obj_set_width(ui_debug_screen_label_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_debug_screen_label_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_debug_screen_label_1, -3);
    lv_obj_set_y(ui_debug_screen_label_1, 16);
    lv_obj_set_align(ui_debug_screen_label_1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_debug_screen_label_1, "SYSTEM");
    lv_obj_set_style_text_color(ui_debug_screen_label_1, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_debug_screen_label_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_debug_screen_label_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_debug_screen_label_1, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_screen_textarea_1 = lv_textarea_create(ui_debug_screen_container_1);
    lv_obj_set_width(ui_debug_screen_textarea_1, 261);
    lv_obj_set_height(ui_debug_screen_textarea_1, 302);
    lv_obj_set_x(ui_debug_screen_textarea_1, 20);
    lv_obj_set_y(ui_debug_screen_textarea_1, 62);
    lv_textarea_set_text(ui_debug_screen_textarea_1, "TEXT");
    lv_textarea_set_placeholder_text(ui_debug_screen_textarea_1, "Placeholder...");
    lv_obj_set_style_text_color(ui_debug_screen_textarea_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_debug_screen_textarea_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_debug_screen_textarea_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debug_screen_textarea_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_screen_container_2 = lv_obj_create(ui_debug_screen);
    lv_obj_remove_style_all(ui_debug_screen_container_2);
    lv_obj_set_width(ui_debug_screen_container_2, 304);
    lv_obj_set_height(ui_debug_screen_container_2, 391);
    lv_obj_set_x(ui_debug_screen_container_2, 206);
    lv_obj_set_y(ui_debug_screen_container_2, 15);
    lv_obj_set_align(ui_debug_screen_container_2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_debug_screen_container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_debug_screen_container_2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_debug_screen_container_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debug_screen_container_2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_screen_label_2 = lv_label_create(ui_debug_screen_container_2);
    lv_obj_set_width(ui_debug_screen_label_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_debug_screen_label_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_debug_screen_label_2, -3);
    lv_obj_set_y(ui_debug_screen_label_2, 16);
    lv_obj_set_align(ui_debug_screen_label_2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_debug_screen_label_2, "BOOT");
    lv_obj_set_style_text_color(ui_debug_screen_label_2, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_debug_screen_label_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_debug_screen_label_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_debug_screen_label_2, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_screen_textarea_2 = lv_textarea_create(ui_debug_screen_container_2);
    lv_obj_set_width(ui_debug_screen_textarea_2, 261);
    lv_obj_set_height(ui_debug_screen_textarea_2, 302);
    lv_obj_set_x(ui_debug_screen_textarea_2, 20);
    lv_obj_set_y(ui_debug_screen_textarea_2, 62);
    lv_textarea_set_text(ui_debug_screen_textarea_2, "TEXT");
    lv_textarea_set_placeholder_text(ui_debug_screen_textarea_2, "Placeholder...");
    lv_obj_set_style_text_color(ui_debug_screen_textarea_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_debug_screen_textarea_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_debug_screen_textarea_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debug_screen_textarea_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_debug_btn_menu_debug, ui_event_btn_menu_debug, LV_EVENT_ALL, NULL);

}

void ui_debug_screen_screen_destroy(void)
{
    if(ui_debug_screen) lv_obj_del(ui_debug_screen);

    // NULL screen variables
    ui_debug_screen = NULL;
    ui_debug_top_bar = NULL;
    ui_debug_image_ce = NULL;
    ui_debug_menu_bar = NULL;
    ui_debug_screen_btn_img_debug = NULL;
    ui_debug_menu_container = NULL;
    ui_debug_btn_menu_home = NULL;
    ui_debug_btn_menu_main = NULL;
    ui_debug_btn_menu_settings = NULL;
    ui_debug_btn_menu_autom = NULL;
    ui_debug_btn_menu_log = NULL;
    ui_debug_btn_menu_aux = NULL;
    ui_debug_btn_menu_debug = NULL;
    ui_debug_screen_container_1 = NULL;
    ui_debug_screen_label_1 = NULL;
    ui_debug_screen_textarea_1 = NULL;
    ui_debug_screen_container_2 = NULL;
    ui_debug_screen_label_2 = NULL;
    ui_debug_screen_textarea_2 = NULL;

}
