// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 02 - Main Screen

#ifndef UI_MAIN_SCREEN_H
#define UI_MAIN_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main_screen
extern void ui_main_screen_screen_init(void);
extern void ui_main_screen_screen_destroy(void);
extern lv_obj_t * ui_main_screen;
extern lv_obj_t * ui_main_top_bar;
extern lv_obj_t * ui_main_image_ce;
extern lv_obj_t * ui_main_menu_bar;
extern lv_obj_t * ui_main_screen_btn_img_main;
extern lv_obj_t * ui_main_menu_container;
extern lv_obj_t * ui_main_btn_menu_home;
extern void ui_event_btn_menu_main(lv_event_t * e);
extern lv_obj_t * ui_main_btn_menu_main;
extern lv_obj_t * ui_main_btn_menu_settings;
extern lv_obj_t * ui_main_btn_menu_autom;
extern lv_obj_t * ui_main_btn_menu_log;
extern lv_obj_t * ui_main_btn_menu_aux;
extern lv_obj_t * ui_main_btn_menu_debug;
extern lv_obj_t * ui_main_buttons_container;
extern lv_obj_t * ui_main_btn_feed_pump;
extern lv_obj_t * ui_main_label_feed_pump;
extern lv_obj_t * ui_main_btn_hp_pump;
extern lv_obj_t * ui_main_label_hp_pump;
extern lv_obj_t * ui_main_btn_flushing_cycle;
extern lv_obj_t * ui_main_label_flushing_cycle;
extern lv_obj_t * ui_main_btn_tank_test;
extern lv_obj_t * ui_main_label_tank_test;
extern lv_obj_t * ui_main_screen_image_bar_selector_bottom;
extern void ui_event_main_screen_glow_3(lv_event_t * e);
extern lv_obj_t * ui_main_screen_glow_3;
extern void ui_event_main_screen_glow_4(lv_event_t * e);
extern lv_obj_t * ui_main_screen_glow_4;
extern lv_obj_t * ui_main_screen_image_bar_selector_top;
extern lv_obj_t * ui_main_screen_label_bar_selector;
extern lv_obj_t * ui_main_screen_image_bar_selector_arrow_up;
extern lv_obj_t * ui_main_screen_image_bar_selector_arrow_down;
extern lv_obj_t * ui_main_screen_label_bar_selector_plus;
extern lv_obj_t * ui_main_screen_label_bar_selector_minus;
extern lv_obj_t * ui_main_screen_label_bar_gauge_pressure;
extern lv_obj_t * ui_main_screen_image_bar_gauge;
extern lv_obj_t * ui_main_screen_label_bar_gauge_bar;
extern lv_obj_t * ui_main_screen_label_bar_gauge_psi;
extern lv_obj_t * ui_main_screen_label_tds_gauge_tds;
extern lv_obj_t * ui_main_screen_image_bar_tds;
extern lv_obj_t * ui_main_screen_label_tds_gauge_center;
extern lv_obj_t * ui_main_screen_label_tds_gauge_upper;
extern lv_obj_t * ui_main_screen_label_tds_gauge_lower;
extern lv_obj_t * ui_main_screen_label_lph_gauge_production;
extern lv_obj_t * ui_main_screen_image_lph_gauge;
extern lv_obj_t * ui_main_screen_label_lph_gauge_lph;
extern lv_obj_t * ui_main_screen_label_lph_gauge_gpd;
extern lv_obj_t * ui_main_screen_panel_bar_preset_and_valve;
extern lv_obj_t * ui_main_screen_panel_bar_preset;
extern lv_obj_t * ui_main_screen_label_bar_psi_title;
extern lv_obj_t * ui_main_screen_label_bar_preset;
extern lv_obj_t * ui_main_screen_label_psi_preset;
extern lv_obj_t * ui_main_screen_panel_divider;
extern lv_obj_t * ui_main_screen_panel_valve_position;
extern lv_obj_t * ui_main_screen_label_valve_position_title;
extern lv_obj_t * ui_main_screen_label_valve_position_turns;
extern lv_obj_t * ui_main_screen_label_valve_position_total;
extern lv_obj_t * ui_main_screen_image_valve_closing;
extern lv_obj_t * ui_main_screen_image_valve_opening;
extern lv_obj_t * ui_main_screen_switch_auto_pressure;
extern lv_obj_t * ui_main_screen_label_auto_pressure;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

