// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 01 - Splash Screen

#ifndef UI_SPLASH_SCREEN_H
#define UI_SPLASH_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_splash_screen
extern void ui_splash_screen_screen_init(void);
extern void ui_splash_screen_screen_destroy(void);
extern lv_obj_t * ui_splash_screen;
extern lv_obj_t * ui_splash_top_bar;
extern lv_obj_t * ui_splash_image_ce;
extern lv_obj_t * ui_splash_menu_bar;
extern lv_obj_t * ui_splash_screen_btn_img_home;
extern lv_obj_t * ui_splash_menu_container;
extern void ui_event_btn_menu_home(lv_event_t * e);
extern lv_obj_t * ui_splash_btn_menu_home;
extern lv_obj_t * ui_splash_btn_menu_main;
extern lv_obj_t * ui_splash_btn_menu_settings;
extern lv_obj_t * ui_splash_btn_menu_autom;
extern lv_obj_t * ui_splash_btn_menu_log;
extern lv_obj_t * ui_splash_btn_menu_aux;
extern lv_obj_t * ui_splash_btn_menu_debug;
extern lv_obj_t * ui_splash_screen_text_warning;
extern lv_obj_t * ui_splash_screen_image_qr_code;
extern lv_obj_t * ui_splash_screen_text_created_by;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

