// Merged N.E.R.D. Gen2 UI
// Generated by ChatGPT from 7 SquareLine Studio single-screen exports
// Source LVGL version: 9.2.2

#ifndef NERD_UI_MERGED_H
#define NERD_UI_MERGED_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_splash_screen.h"
#include "screens/ui_main_screen.h"
#include "screens/ui_settings_screen.h"
#include "screens/ui_autom_screen.h"
#include "screens/ui_log_screen.h"
#include "screens/ui_aux_screen.h"
#include "screens/ui_debug_screen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * OpaOn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * OpaOff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ScreenIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MenuIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MenuOut_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ScreenOut_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS / INITIAL ACTIONS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1530556444);
LV_IMG_DECLARE(ui_img_625624875);
LV_IMG_DECLARE(ui_img_arrow_down_png);
LV_IMG_DECLARE(ui_img_arrow_up_png);
LV_IMG_DECLARE(ui_img_btn_autom_png);
LV_IMG_DECLARE(ui_img_btn_aux_png);
LV_IMG_DECLARE(ui_img_btn_debug_png);
LV_IMG_DECLARE(ui_img_btn_home_png);
LV_IMG_DECLARE(ui_img_btn_log_png);
LV_IMG_DECLARE(ui_img_btn_main_off_png);
LV_IMG_DECLARE(ui_img_btn_main_on_png);
LV_IMG_DECLARE(ui_img_btn_main_png);
LV_IMG_DECLARE(ui_img_btn_settings_png);
LV_IMG_DECLARE(ui_img_btn_z_botton_png);
LV_IMG_DECLARE(ui_img_btn_z_top_png);
LV_IMG_DECLARE(ui_img_icn_head_png);
LV_IMG_DECLARE(ui_img_icn_time_1_png);
LV_IMG_DECLARE(ui_img_icn_time_2_png);
LV_IMG_DECLARE(ui_img_logo_negativo_traspsrente_130_px_png);
LV_IMG_DECLARE(ui_img_menu_bar_png);
LV_IMG_DECLARE(ui_img_roller_bg_png);
LV_IMG_DECLARE(ui_img_top_bar_png);

// FONTS
LV_FONT_DECLARE(ui_font_Small_Font);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
