// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 07 - Debug Screen

#ifndef UI_DEBUG_SCREEN_H
#define UI_DEBUG_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_debug_screen
extern void ui_debug_screen_screen_init(void);
extern void ui_debug_screen_screen_destroy(void);
extern lv_obj_t * ui_debug_screen;
extern lv_obj_t * ui_debug_top_bar;
extern lv_obj_t * ui_debug_image_ce;
extern lv_obj_t * ui_debug_menu_bar;
extern lv_obj_t * ui_debug_screen_btn_img_debug;
extern lv_obj_t * ui_debug_menu_container;
extern lv_obj_t * ui_debug_btn_menu_home;
extern lv_obj_t * ui_debug_btn_menu_main;
extern lv_obj_t * ui_debug_btn_menu_settings;
extern lv_obj_t * ui_debug_btn_menu_autom;
extern lv_obj_t * ui_debug_btn_menu_log;
extern lv_obj_t * ui_debug_btn_menu_aux;
extern void ui_event_btn_menu_debug(lv_event_t * e);
extern lv_obj_t * ui_debug_btn_menu_debug;
extern lv_obj_t * ui_debug_screen_container_1;
extern lv_obj_t * ui_debug_screen_label_1;
extern lv_obj_t * ui_debug_screen_textarea_1;

extern lv_obj_t * ui_debug_screen_valve_container;
extern lv_obj_t * ui_debug_screen_label_valve_title;
extern lv_obj_t * ui_debug_screen_label_valve_status;
extern lv_obj_t * ui_debug_screen_label_valve_position;

extern lv_obj_t * ui_debug_screen_btn_valve_open;
extern lv_obj_t * ui_debug_screen_label_valve_open;
extern lv_obj_t * ui_debug_screen_btn_valve_close;
extern lv_obj_t * ui_debug_screen_label_valve_close;

extern lv_obj_t * ui_debug_screen_btn_valve_zero_open;
extern lv_obj_t * ui_debug_screen_label_valve_zero_open;
extern lv_obj_t * ui_debug_screen_btn_valve_zero_closed;
extern lv_obj_t * ui_debug_screen_label_valve_zero_closed;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
