// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 05 - Log Screen

#include "../ui.h"

lv_obj_t * ui_log_screen = NULL;
lv_obj_t * ui_log_top_bar = NULL;
lv_obj_t * ui_log_image_ce = NULL;
lv_obj_t * ui_log_menu_bar = NULL;
lv_obj_t * ui_log_screen_btn_img_log = NULL;
lv_obj_t * ui_log_menu_container = NULL;
lv_obj_t * ui_log_btn_menu_home = NULL;
lv_obj_t * ui_log_btn_menu_main = NULL;
lv_obj_t * ui_log_btn_menu_settings = NULL;
lv_obj_t * ui_log_btn_menu_autom = NULL;
lv_obj_t * ui_log_btn_menu_log = NULL;
lv_obj_t * ui_log_btn_menu_aux = NULL;
lv_obj_t * ui_log_btn_menu_debug = NULL;
lv_obj_t * ui_log_buttons_container = NULL;
lv_obj_t * ui_log_btn_feed_pump = NULL;
lv_obj_t * ui_log_label_feed_pump = NULL;
lv_obj_t * ui_log_btn_hp_pump = NULL;
lv_obj_t * ui_log_label_hp_pump = NULL;
lv_obj_t * ui_log_btn_flushing_cycle = NULL;
lv_obj_t * ui_log_label_flushing_cycle = NULL;
lv_obj_t * ui_log_btn_tank_test = NULL;
lv_obj_t * ui_log_label_tank_test = NULL;
lv_obj_t * ui_log_screen_container_system_totals = NULL;
lv_obj_t * ui_log_screen_label_system_totals = NULL;
lv_obj_t * ui_log_screen_panel_hp_pump = NULL;
lv_obj_t * ui_log_screen_label_hp_pump = NULL;
lv_obj_t * ui_log_screen_label_hp_pump_hours = NULL;
lv_obj_t * ui_log_screen_label_hp_pump_minutes = NULL;
lv_obj_t * ui_log_screen_panel_water_produced = NULL;
lv_obj_t * ui_log_screen_label_water_produced = NULL;
lv_obj_t * ui_log_screen_label_water_produced_liters = NULL;
lv_obj_t * ui_log_screen_panel_average_prod = NULL;
lv_obj_t * ui_log_screen_label_average_prod = NULL;
lv_obj_t * ui_log_screen_label_average_prod_lh = NULL;
lv_obj_t * ui_log_screen_container_system_partials = NULL;
lv_obj_t * ui_log_screen_label_system_partials = NULL;
lv_obj_t * ui_log_screen_panel_hp_pump_partial = NULL;
lv_obj_t * ui_log_screen_label_hp_pump_partial = NULL;
lv_obj_t * ui_log_screen_label_hp_pump_hours_partial = NULL;
lv_obj_t * ui_log_screen_label_hp_pump_minutes_partial = NULL;
lv_obj_t * ui_log_screen_panel_water_produced_partial = NULL;
lv_obj_t * ui_log_screen_label_water_produced_partial = NULL;
lv_obj_t * ui_log_screen_label_water_produced_liters_partial = NULL;
lv_obj_t * ui_log_screen_panel_filters_hours = NULL;
lv_obj_t * ui_log_screen_label_filters_hours = NULL;
lv_obj_t * ui_log_screen_label_filters_hours_count = NULL;
lv_obj_t * ui_log_screen_btn_reset_hours = NULL;
lv_obj_t * ui_log_screen_label_reset_hours = NULL;
lv_obj_t * ui_log_screen_btn_reset_liters = NULL;
lv_obj_t * ui_log_screen_label_reset_liters = NULL;
lv_obj_t * ui_log_screen_btn_reset_filters = NULL;
lv_obj_t * ui_log_screen_label_reset_filters = NULL;
// event funtions
void ui_event_btn_menu_log(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_log_screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_log_screen_screen_init);
    }
}

// build funtions

void ui_log_screen_screen_init(void)
{
    ui_log_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_log_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_log_screen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_log_screen, lv_color_hex(0x596684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_log_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_top_bar = lv_image_create(ui_log_screen);
    lv_image_set_src(ui_log_top_bar, &ui_img_top_bar_png);
    lv_obj_set_width(ui_log_top_bar, LV_SIZE_CONTENT);   /// 681
    lv_obj_set_height(ui_log_top_bar, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_log_top_bar, 37);
    lv_obj_set_y(ui_log_top_bar, -218);
    lv_obj_set_align(ui_log_top_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_log_top_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_log_top_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_log_image_ce = lv_image_create(ui_log_screen);
    lv_image_set_src(ui_log_image_ce, &ui_img_625624875);
    lv_obj_set_width(ui_log_image_ce, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_log_image_ce, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_log_image_ce, 350);
    lv_obj_set_y(ui_log_image_ce, -221);
    lv_obj_set_align(ui_log_image_ce, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_log_image_ce, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_log_image_ce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_log_menu_bar = lv_image_create(ui_log_screen);
    lv_image_set_src(ui_log_menu_bar, &ui_img_menu_bar_png);
    lv_obj_set_width(ui_log_menu_bar, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_log_menu_bar, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_log_menu_bar, -363);
    lv_obj_set_y(ui_log_menu_bar, 0);
    lv_obj_set_align(ui_log_menu_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_log_menu_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_log_menu_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_log_screen_btn_img_log = lv_image_create(ui_log_screen);
    lv_image_set_src(ui_log_screen_btn_img_log, &ui_img_btn_log_png);
    lv_obj_set_width(ui_log_screen_btn_img_log, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_log_screen_btn_img_log, LV_SIZE_CONTENT);    /// 66
    lv_obj_set_x(ui_log_screen_btn_img_log, -360);
    lv_obj_set_y(ui_log_screen_btn_img_log, 72);
    lv_obj_set_align(ui_log_screen_btn_img_log, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_log_screen_btn_img_log, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_log_screen_btn_img_log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_log_menu_container = lv_obj_create(ui_log_screen);
    lv_obj_remove_style_all(ui_log_menu_container);
    lv_obj_set_width(ui_log_menu_container, 83);
    lv_obj_set_height(ui_log_menu_container, 488);
    lv_obj_set_x(ui_log_menu_container, -2);
    lv_obj_set_y(ui_log_menu_container, -2);
    lv_obj_remove_flag(ui_log_menu_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_log_btn_menu_home = lv_image_create(ui_log_menu_container);
    lv_obj_set_width(ui_log_btn_menu_home, 74);
    lv_obj_set_height(ui_log_btn_menu_home, 65);
    lv_obj_set_x(ui_log_btn_menu_home, 5);
    lv_obj_set_y(ui_log_btn_menu_home, -412);
    lv_obj_set_align(ui_log_btn_menu_home, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_log_btn_menu_home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_log_btn_menu_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_log_btn_menu_home, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_log_btn_menu_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_btn_menu_main = lv_image_create(ui_log_menu_container);
    lv_obj_set_width(ui_log_btn_menu_main, 74);
    lv_obj_set_height(ui_log_btn_menu_main, 59);
    lv_obj_set_x(ui_log_btn_menu_main, 5);
    lv_obj_set_y(ui_log_btn_menu_main, -345);
    lv_obj_set_align(ui_log_btn_menu_main, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_log_btn_menu_main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_log_btn_menu_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_log_btn_menu_main, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_log_btn_menu_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_btn_menu_settings = lv_image_create(ui_log_menu_container);
    lv_obj_set_width(ui_log_btn_menu_settings, 74);
    lv_obj_set_height(ui_log_btn_menu_settings, 59);
    lv_obj_set_x(ui_log_btn_menu_settings, 5);
    lv_obj_set_y(ui_log_btn_menu_settings, -278);
    lv_obj_set_align(ui_log_btn_menu_settings, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_log_btn_menu_settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_log_btn_menu_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_log_btn_menu_settings, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_log_btn_menu_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_btn_menu_autom = lv_image_create(ui_log_menu_container);
    lv_obj_set_width(ui_log_btn_menu_autom, 74);
    lv_obj_set_height(ui_log_btn_menu_autom, 59);
    lv_obj_set_x(ui_log_btn_menu_autom, 5);
    lv_obj_set_y(ui_log_btn_menu_autom, -212);
    lv_obj_set_align(ui_log_btn_menu_autom, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_log_btn_menu_autom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_log_btn_menu_autom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_log_btn_menu_autom, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_log_btn_menu_autom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_btn_menu_log = lv_image_create(ui_log_menu_container);
    lv_obj_set_width(ui_log_btn_menu_log, 74);
    lv_obj_set_height(ui_log_btn_menu_log, 59);
    lv_obj_set_x(ui_log_btn_menu_log, 5);
    lv_obj_set_y(ui_log_btn_menu_log, -146);
    lv_obj_set_align(ui_log_btn_menu_log, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_log_btn_menu_log, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_log_btn_menu_log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_log_btn_menu_log, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_log_btn_menu_log, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_btn_menu_aux = lv_image_create(ui_log_menu_container);
    lv_obj_set_width(ui_log_btn_menu_aux, 74);
    lv_obj_set_height(ui_log_btn_menu_aux, 59);
    lv_obj_set_x(ui_log_btn_menu_aux, 5);
    lv_obj_set_y(ui_log_btn_menu_aux, -80);
    lv_obj_set_align(ui_log_btn_menu_aux, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_log_btn_menu_aux, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_log_btn_menu_aux, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_log_btn_menu_aux, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_log_btn_menu_aux, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_btn_menu_debug = lv_image_create(ui_log_menu_container);
    lv_obj_set_width(ui_log_btn_menu_debug, 74);
    lv_obj_set_height(ui_log_btn_menu_debug, 59);
    lv_obj_set_x(ui_log_btn_menu_debug, 5);
    lv_obj_set_y(ui_log_btn_menu_debug, -12);
    lv_obj_set_align(ui_log_btn_menu_debug, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_log_btn_menu_debug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_log_btn_menu_debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_log_btn_menu_debug, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_log_btn_menu_debug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_buttons_container = lv_obj_create(ui_log_screen);
    lv_obj_remove_style_all(ui_log_buttons_container);
    lv_obj_set_width(ui_log_buttons_container, 684);
    lv_obj_set_height(ui_log_buttons_container, 65);
    lv_obj_set_x(ui_log_buttons_container, 32);
    lv_obj_set_y(ui_log_buttons_container, 185);
    lv_obj_set_align(ui_log_buttons_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_log_buttons_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_log_btn_feed_pump = lv_imagebutton_create(ui_log_buttons_container);
    lv_imagebutton_set_src(ui_log_btn_feed_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_feed_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_log_btn_feed_pump, 66);
    lv_obj_set_width(ui_log_btn_feed_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_log_btn_feed_pump, 7);
    lv_obj_set_y(ui_log_btn_feed_pump, 0);
    lv_obj_set_align(ui_log_btn_feed_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_log_btn_feed_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_log_btn_feed_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_log_btn_feed_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_log_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_log_btn_feed_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_log_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_log_label_feed_pump = lv_label_create(ui_log_btn_feed_pump);
    lv_obj_set_width(ui_log_label_feed_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_label_feed_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_log_label_feed_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_log_label_feed_pump, "FEED PUMP");
    lv_obj_set_style_text_align(ui_log_label_feed_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_label_feed_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_btn_hp_pump = lv_imagebutton_create(ui_log_buttons_container);
    lv_imagebutton_set_src(ui_log_btn_hp_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_hp_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_log_btn_hp_pump, 66);
    lv_obj_set_width(ui_log_btn_hp_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_log_btn_hp_pump, 176);
    lv_obj_set_y(ui_log_btn_hp_pump, 0);
    lv_obj_set_align(ui_log_btn_hp_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_log_btn_hp_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_log_btn_hp_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_log_btn_hp_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_log_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_log_btn_hp_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_log_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_log_label_hp_pump = lv_label_create(ui_log_btn_hp_pump);
    lv_obj_set_width(ui_log_label_hp_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_label_hp_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_log_label_hp_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_log_label_hp_pump, "H.P. PUMP");
    lv_obj_set_style_text_align(ui_log_label_hp_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_label_hp_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_btn_flushing_cycle = lv_imagebutton_create(ui_log_buttons_container);
    lv_imagebutton_set_src(ui_log_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_log_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_obj_set_height(ui_log_btn_flushing_cycle, 66);
    lv_obj_set_width(ui_log_btn_flushing_cycle, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_log_btn_flushing_cycle, 351);
    lv_obj_set_y(ui_log_btn_flushing_cycle, 0);
    lv_obj_set_align(ui_log_btn_flushing_cycle, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_log_btn_flushing_cycle, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_log_btn_flushing_cycle, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_log_btn_flushing_cycle, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_log_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_log_btn_flushing_cycle, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_log_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_log_label_flushing_cycle = lv_label_create(ui_log_btn_flushing_cycle);
    lv_obj_set_width(ui_log_label_flushing_cycle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_label_flushing_cycle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_log_label_flushing_cycle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_log_label_flushing_cycle, "FLUSHING\nCYCLE");
    lv_obj_set_style_text_align(ui_log_label_flushing_cycle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_label_flushing_cycle, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_btn_tank_test = lv_imagebutton_create(ui_log_buttons_container);
    lv_imagebutton_set_src(ui_log_btn_tank_test, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_tank_test, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_log_btn_tank_test, 66);
    lv_obj_set_width(ui_log_btn_tank_test, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_log_btn_tank_test, 522);
    lv_obj_set_y(ui_log_btn_tank_test, 0);
    lv_obj_set_align(ui_log_btn_tank_test, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_log_btn_tank_test, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_log_btn_tank_test, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_log_btn_tank_test, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_log_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_log_btn_tank_test, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_log_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_log_label_tank_test = lv_label_create(ui_log_btn_tank_test);
    lv_obj_set_width(ui_log_label_tank_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_label_tank_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_log_label_tank_test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_log_label_tank_test, "WATER\nTO TANK");
    lv_obj_set_style_text_align(ui_log_label_tank_test, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_label_tank_test, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_container_system_totals = lv_obj_create(ui_log_screen);
    lv_obj_remove_style_all(ui_log_screen_container_system_totals);
    lv_obj_set_width(ui_log_screen_container_system_totals, 207);
    lv_obj_set_height(ui_log_screen_container_system_totals, 327);
    lv_obj_set_x(ui_log_screen_container_system_totals, -199);
    lv_obj_set_y(ui_log_screen_container_system_totals, -18);
    lv_obj_set_align(ui_log_screen_container_system_totals, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_log_screen_container_system_totals,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_log_screen_container_system_totals, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_log_screen_container_system_totals, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_log_screen_container_system_totals, 18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_system_totals = lv_label_create(ui_log_screen_container_system_totals);
    lv_obj_set_width(ui_log_screen_label_system_totals, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_system_totals, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_system_totals, -3);
    lv_obj_set_y(ui_log_screen_label_system_totals, 16);
    lv_obj_set_align(ui_log_screen_label_system_totals, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_log_screen_label_system_totals, "SYSTEM TOTALS");
    lv_obj_set_style_text_color(ui_log_screen_label_system_totals, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_system_totals, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_system_totals, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_system_totals, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_panel_hp_pump = lv_obj_create(ui_log_screen);
    lv_obj_set_width(ui_log_screen_panel_hp_pump, 176);
    lv_obj_set_height(ui_log_screen_panel_hp_pump, 79);
    lv_obj_set_x(ui_log_screen_panel_hp_pump, -512);
    lv_obj_set_y(ui_log_screen_panel_hp_pump, 106);
    lv_obj_set_align(ui_log_screen_panel_hp_pump, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_log_screen_panel_hp_pump, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_log_screen_panel_hp_pump, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_log_screen_panel_hp_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_log_screen_panel_hp_pump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_log_screen_panel_hp_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_log_screen_panel_hp_pump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_log_screen_panel_hp_pump, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_log_screen_panel_hp_pump, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_log_screen_panel_hp_pump, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_log_screen_panel_hp_pump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_log_screen_panel_hp_pump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_log_screen_panel_hp_pump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_log_screen_panel_hp_pump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_log_screen_panel_hp_pump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_hp_pump = lv_label_create(ui_log_screen_panel_hp_pump);
    lv_obj_set_width(ui_log_screen_label_hp_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_hp_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_hp_pump, -1);
    lv_obj_set_y(ui_log_screen_label_hp_pump, 8);
    lv_obj_set_align(ui_log_screen_label_hp_pump, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_log_screen_label_hp_pump, "HOURS RUNNING");
    lv_obj_set_style_text_color(ui_log_screen_label_hp_pump, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_hp_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_hp_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_hp_pump_hours = lv_label_create(ui_log_screen_panel_hp_pump);
    lv_obj_set_width(ui_log_screen_label_hp_pump_hours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_hp_pump_hours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_hp_pump_hours, 14);
    lv_obj_set_y(ui_log_screen_label_hp_pump_hours, 10);
    lv_obj_set_align(ui_log_screen_label_hp_pump_hours, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_log_screen_label_hp_pump_hours, "129 h");
    lv_obj_set_style_text_color(ui_log_screen_label_hp_pump_hours, lv_color_hex(0x3A72EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_hp_pump_hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_hp_pump_hours, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_hp_pump_hours, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_hp_pump_minutes = lv_label_create(ui_log_screen_panel_hp_pump);
    lv_obj_set_width(ui_log_screen_label_hp_pump_minutes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_hp_pump_minutes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_hp_pump_minutes, 101);
    lv_obj_set_y(ui_log_screen_label_hp_pump_minutes, 10);
    lv_obj_set_align(ui_log_screen_label_hp_pump_minutes, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_log_screen_label_hp_pump_minutes, "58 m");
    lv_obj_set_style_text_color(ui_log_screen_label_hp_pump_minutes, lv_color_hex(0x3A72EF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_hp_pump_minutes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_hp_pump_minutes, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_hp_pump_minutes, &lv_font_montserrat_26,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_panel_water_produced = lv_obj_create(ui_log_screen);
    lv_obj_set_width(ui_log_screen_panel_water_produced, 176);
    lv_obj_set_height(ui_log_screen_panel_water_produced, 79);
    lv_obj_set_x(ui_log_screen_panel_water_produced, -512);
    lv_obj_set_y(ui_log_screen_panel_water_produced, 201);
    lv_obj_set_align(ui_log_screen_panel_water_produced, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_log_screen_panel_water_produced, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_log_screen_panel_water_produced, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_log_screen_panel_water_produced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_log_screen_panel_water_produced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_log_screen_panel_water_produced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_log_screen_panel_water_produced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_log_screen_panel_water_produced, lv_color_hex(0x414B62),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_log_screen_panel_water_produced, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_log_screen_panel_water_produced, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_log_screen_panel_water_produced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_log_screen_panel_water_produced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_log_screen_panel_water_produced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_log_screen_panel_water_produced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_log_screen_panel_water_produced, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_water_produced = lv_label_create(ui_log_screen_panel_water_produced);
    lv_obj_set_width(ui_log_screen_label_water_produced, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_water_produced, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_water_produced, 0);
    lv_obj_set_y(ui_log_screen_label_water_produced, 8);
    lv_obj_set_align(ui_log_screen_label_water_produced, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_log_screen_label_water_produced, "WATER PRODUCED");
    lv_obj_set_style_text_color(ui_log_screen_label_water_produced, lv_color_hex(0x9098AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_water_produced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_water_produced, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_water_produced_liters = lv_label_create(ui_log_screen_panel_water_produced);
    lv_obj_set_width(ui_log_screen_label_water_produced_liters, 169);
    lv_obj_set_height(ui_log_screen_label_water_produced_liters, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_water_produced_liters, 3);
    lv_obj_set_y(ui_log_screen_label_water_produced_liters, 12);
    lv_obj_set_align(ui_log_screen_label_water_produced_liters, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_log_screen_label_water_produced_liters, "99739 Liters");
    lv_obj_set_style_text_color(ui_log_screen_label_water_produced_liters, lv_color_hex(0x3A72EF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_water_produced_liters, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_water_produced_liters, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_water_produced_liters, &lv_font_montserrat_26,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_panel_average_prod = lv_obj_create(ui_log_screen);
    lv_obj_set_width(ui_log_screen_panel_average_prod, 176);
    lv_obj_set_height(ui_log_screen_panel_average_prod, 79);
    lv_obj_set_x(ui_log_screen_panel_average_prod, -512);
    lv_obj_set_y(ui_log_screen_panel_average_prod, 295);
    lv_obj_set_align(ui_log_screen_panel_average_prod, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_log_screen_panel_average_prod, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_log_screen_panel_average_prod, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_log_screen_panel_average_prod, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_log_screen_panel_average_prod, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_log_screen_panel_average_prod, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_log_screen_panel_average_prod, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_log_screen_panel_average_prod, lv_color_hex(0x414B62),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_log_screen_panel_average_prod, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_log_screen_panel_average_prod, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_log_screen_panel_average_prod, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_log_screen_panel_average_prod, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_log_screen_panel_average_prod, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_log_screen_panel_average_prod, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_log_screen_panel_average_prod, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_average_prod = lv_label_create(ui_log_screen_panel_average_prod);
    lv_obj_set_width(ui_log_screen_label_average_prod, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_average_prod, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_average_prod, 0);
    lv_obj_set_y(ui_log_screen_label_average_prod, 8);
    lv_obj_set_align(ui_log_screen_label_average_prod, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_log_screen_label_average_prod, "AVERAGE PROD.");
    lv_obj_set_style_text_color(ui_log_screen_label_average_prod, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_average_prod, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_average_prod, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_average_prod_lh = lv_label_create(ui_log_screen_panel_average_prod);
    lv_obj_set_width(ui_log_screen_label_average_prod_lh, 169);
    lv_obj_set_height(ui_log_screen_label_average_prod_lh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_average_prod_lh, 3);
    lv_obj_set_y(ui_log_screen_label_average_prod_lh, 12);
    lv_obj_set_align(ui_log_screen_label_average_prod_lh, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_log_screen_label_average_prod_lh, "123 L/h");
    lv_obj_set_style_text_color(ui_log_screen_label_average_prod_lh, lv_color_hex(0x3A72EF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_average_prod_lh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_average_prod_lh, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_average_prod_lh, &lv_font_montserrat_26,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_container_system_partials = lv_obj_create(ui_log_screen);
    lv_obj_remove_style_all(ui_log_screen_container_system_partials);
    lv_obj_set_width(ui_log_screen_container_system_partials, 430);
    lv_obj_set_height(ui_log_screen_container_system_partials, 327);
    lv_obj_set_x(ui_log_screen_container_system_partials, 153);
    lv_obj_set_y(ui_log_screen_container_system_partials, -18);
    lv_obj_set_align(ui_log_screen_container_system_partials, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_log_screen_container_system_partials,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_log_screen_container_system_partials, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_log_screen_container_system_partials, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_log_screen_container_system_partials, 18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_system_partials = lv_label_create(ui_log_screen_container_system_partials);
    lv_obj_set_width(ui_log_screen_label_system_partials, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_system_partials, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_system_partials, -3);
    lv_obj_set_y(ui_log_screen_label_system_partials, 16);
    lv_obj_set_align(ui_log_screen_label_system_partials, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_log_screen_label_system_partials, "SYSTEM PARTIALS");
    lv_obj_set_style_text_color(ui_log_screen_label_system_partials, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_system_partials, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_system_partials, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_system_partials, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_panel_hp_pump_partial = lv_obj_create(ui_log_screen);
    lv_obj_set_width(ui_log_screen_panel_hp_pump_partial, 176);
    lv_obj_set_height(ui_log_screen_panel_hp_pump_partial, 79);
    lv_obj_set_x(ui_log_screen_panel_hp_pump_partial, -270);
    lv_obj_set_y(ui_log_screen_panel_hp_pump_partial, 106);
    lv_obj_set_align(ui_log_screen_panel_hp_pump_partial, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_log_screen_panel_hp_pump_partial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_log_screen_panel_hp_pump_partial, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_log_screen_panel_hp_pump_partial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_log_screen_panel_hp_pump_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_log_screen_panel_hp_pump_partial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_log_screen_panel_hp_pump_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_log_screen_panel_hp_pump_partial, lv_color_hex(0x414B62),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_log_screen_panel_hp_pump_partial, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_log_screen_panel_hp_pump_partial, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_log_screen_panel_hp_pump_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_log_screen_panel_hp_pump_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_log_screen_panel_hp_pump_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_log_screen_panel_hp_pump_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_log_screen_panel_hp_pump_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_hp_pump_partial = lv_label_create(ui_log_screen_panel_hp_pump_partial);
    lv_obj_set_width(ui_log_screen_label_hp_pump_partial, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_hp_pump_partial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_hp_pump_partial, -1);
    lv_obj_set_y(ui_log_screen_label_hp_pump_partial, 8);
    lv_obj_set_align(ui_log_screen_label_hp_pump_partial, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_log_screen_label_hp_pump_partial, "HOURS RUNNING");
    lv_obj_set_style_text_color(ui_log_screen_label_hp_pump_partial, lv_color_hex(0x9098AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_hp_pump_partial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_hp_pump_partial, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_hp_pump_hours_partial = lv_label_create(ui_log_screen_panel_hp_pump_partial);
    lv_obj_set_width(ui_log_screen_label_hp_pump_hours_partial, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_hp_pump_hours_partial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_hp_pump_hours_partial, 32);
    lv_obj_set_y(ui_log_screen_label_hp_pump_hours_partial, 10);
    lv_obj_set_align(ui_log_screen_label_hp_pump_hours_partial, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_log_screen_label_hp_pump_hours_partial, "53 h");
    lv_obj_set_style_text_color(ui_log_screen_label_hp_pump_hours_partial, lv_color_hex(0x3A72EF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_hp_pump_hours_partial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_hp_pump_hours_partial, LV_TEXT_ALIGN_LEFT,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_hp_pump_hours_partial, &lv_font_montserrat_26,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_hp_pump_minutes_partial = lv_label_create(ui_log_screen_panel_hp_pump_partial);
    lv_obj_set_width(ui_log_screen_label_hp_pump_minutes_partial, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_hp_pump_minutes_partial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_hp_pump_minutes_partial, 101);
    lv_obj_set_y(ui_log_screen_label_hp_pump_minutes_partial, 10);
    lv_obj_set_align(ui_log_screen_label_hp_pump_minutes_partial, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_log_screen_label_hp_pump_minutes_partial, "18 m");
    lv_obj_set_style_text_color(ui_log_screen_label_hp_pump_minutes_partial, lv_color_hex(0x3A72EF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_hp_pump_minutes_partial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_hp_pump_minutes_partial, LV_TEXT_ALIGN_RIGHT,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_hp_pump_minutes_partial, &lv_font_montserrat_26,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_panel_water_produced_partial = lv_obj_create(ui_log_screen);
    lv_obj_set_width(ui_log_screen_panel_water_produced_partial, 176);
    lv_obj_set_height(ui_log_screen_panel_water_produced_partial, 79);
    lv_obj_set_x(ui_log_screen_panel_water_produced_partial, -270);
    lv_obj_set_y(ui_log_screen_panel_water_produced_partial, 201);
    lv_obj_set_align(ui_log_screen_panel_water_produced_partial, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_log_screen_panel_water_produced_partial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_log_screen_panel_water_produced_partial, lv_color_hex(0x191D26),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_log_screen_panel_water_produced_partial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_log_screen_panel_water_produced_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_log_screen_panel_water_produced_partial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_log_screen_panel_water_produced_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_log_screen_panel_water_produced_partial, lv_color_hex(0x414B62),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_log_screen_panel_water_produced_partial, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_log_screen_panel_water_produced_partial, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_log_screen_panel_water_produced_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_log_screen_panel_water_produced_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_log_screen_panel_water_produced_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_log_screen_panel_water_produced_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_log_screen_panel_water_produced_partial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_water_produced_partial = lv_label_create(ui_log_screen_panel_water_produced_partial);
    lv_obj_set_width(ui_log_screen_label_water_produced_partial, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_water_produced_partial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_water_produced_partial, 0);
    lv_obj_set_y(ui_log_screen_label_water_produced_partial, 8);
    lv_obj_set_align(ui_log_screen_label_water_produced_partial, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_log_screen_label_water_produced_partial, "WATER PRODUCED");
    lv_obj_set_style_text_color(ui_log_screen_label_water_produced_partial, lv_color_hex(0x9098AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_water_produced_partial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_water_produced_partial, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_water_produced_liters_partial = lv_label_create(ui_log_screen_panel_water_produced_partial);
    lv_obj_set_width(ui_log_screen_label_water_produced_liters_partial, 169);
    lv_obj_set_height(ui_log_screen_label_water_produced_liters_partial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_water_produced_liters_partial, 3);
    lv_obj_set_y(ui_log_screen_label_water_produced_liters_partial, 12);
    lv_obj_set_align(ui_log_screen_label_water_produced_liters_partial, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_log_screen_label_water_produced_liters_partial, "99739 Liters");
    lv_obj_set_style_text_color(ui_log_screen_label_water_produced_liters_partial, lv_color_hex(0x3A72EF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_water_produced_liters_partial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_water_produced_liters_partial, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_water_produced_liters_partial, &lv_font_montserrat_26,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_panel_filters_hours = lv_obj_create(ui_log_screen);
    lv_obj_set_width(ui_log_screen_panel_filters_hours, 176);
    lv_obj_set_height(ui_log_screen_panel_filters_hours, 79);
    lv_obj_set_x(ui_log_screen_panel_filters_hours, -270);
    lv_obj_set_y(ui_log_screen_panel_filters_hours, 295);
    lv_obj_set_align(ui_log_screen_panel_filters_hours, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_log_screen_panel_filters_hours, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_log_screen_panel_filters_hours, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_log_screen_panel_filters_hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_log_screen_panel_filters_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_log_screen_panel_filters_hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_log_screen_panel_filters_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_log_screen_panel_filters_hours, lv_color_hex(0x414B62),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_log_screen_panel_filters_hours, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_log_screen_panel_filters_hours, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_log_screen_panel_filters_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_log_screen_panel_filters_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_log_screen_panel_filters_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_log_screen_panel_filters_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_log_screen_panel_filters_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_filters_hours = lv_label_create(ui_log_screen_panel_filters_hours);
    lv_obj_set_width(ui_log_screen_label_filters_hours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_filters_hours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_filters_hours, 0);
    lv_obj_set_y(ui_log_screen_label_filters_hours, 8);
    lv_obj_set_align(ui_log_screen_label_filters_hours, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_log_screen_label_filters_hours, "FILTERS HOURS");
    lv_obj_set_style_text_color(ui_log_screen_label_filters_hours, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_filters_hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_filters_hours, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_label_filters_hours_count = lv_label_create(ui_log_screen_panel_filters_hours);
    lv_obj_set_width(ui_log_screen_label_filters_hours_count, 169);
    lv_obj_set_height(ui_log_screen_label_filters_hours_count, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_filters_hours_count, 3);
    lv_obj_set_y(ui_log_screen_label_filters_hours_count, 12);
    lv_obj_set_align(ui_log_screen_label_filters_hours_count, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_log_screen_label_filters_hours_count, "123 Hours");
    lv_obj_set_style_text_color(ui_log_screen_label_filters_hours_count, lv_color_hex(0x3A72EF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_label_filters_hours_count, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_log_screen_label_filters_hours_count, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_filters_hours_count, &lv_font_montserrat_26,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_btn_reset_hours = lv_imagebutton_create(ui_log_screen);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_hours, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png,
                           NULL);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_hours, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_hours, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_hours, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_log_screen_btn_reset_hours, 66);
    lv_obj_set_width(ui_log_screen_btn_reset_hours, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_log_screen_btn_reset_hours, -71);
    lv_obj_set_y(ui_log_screen_btn_reset_hours, 114);
    lv_obj_set_align(ui_log_screen_btn_reset_hours, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_log_screen_btn_reset_hours, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_btn_reset_hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_log_screen_btn_reset_hours, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_log_screen_btn_reset_hours, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_log_screen_btn_reset_hours, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_log_screen_btn_reset_hours, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_log_screen_label_reset_hours = lv_label_create(ui_log_screen_btn_reset_hours);
    lv_obj_set_width(ui_log_screen_label_reset_hours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_reset_hours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_reset_hours, -3);
    lv_obj_set_y(ui_log_screen_label_reset_hours, 0);
    lv_obj_set_align(ui_log_screen_label_reset_hours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_log_screen_label_reset_hours, "RESET");
    lv_obj_set_style_text_align(ui_log_screen_label_reset_hours, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_reset_hours, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_btn_reset_liters = lv_imagebutton_create(ui_log_screen);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_liters, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png,
                           NULL);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_liters, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_liters, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_liters, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_log_screen_btn_reset_liters, 66);
    lv_obj_set_width(ui_log_screen_btn_reset_liters, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_log_screen_btn_reset_liters, -71);
    lv_obj_set_y(ui_log_screen_btn_reset_liters, 209);
    lv_obj_set_align(ui_log_screen_btn_reset_liters, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_log_screen_btn_reset_liters, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_btn_reset_liters, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_log_screen_btn_reset_liters, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_log_screen_btn_reset_liters, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_log_screen_btn_reset_liters, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_log_screen_btn_reset_liters, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_log_screen_label_reset_liters = lv_label_create(ui_log_screen_btn_reset_liters);
    lv_obj_set_width(ui_log_screen_label_reset_liters, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_reset_liters, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_reset_liters, -3);
    lv_obj_set_y(ui_log_screen_label_reset_liters, 0);
    lv_obj_set_align(ui_log_screen_label_reset_liters, LV_ALIGN_CENTER);
    lv_label_set_text(ui_log_screen_label_reset_liters, "RESET");
    lv_obj_set_style_text_align(ui_log_screen_label_reset_liters, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_reset_liters, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_log_screen_btn_reset_filters = lv_imagebutton_create(ui_log_screen);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_filters, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png,
                           NULL);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_filters, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_filters, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_log_screen_btn_reset_filters, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_log_screen_btn_reset_filters, 66);
    lv_obj_set_width(ui_log_screen_btn_reset_filters, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_log_screen_btn_reset_filters, -71);
    lv_obj_set_y(ui_log_screen_btn_reset_filters, 303);
    lv_obj_set_align(ui_log_screen_btn_reset_filters, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_log_screen_btn_reset_filters, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_log_screen_btn_reset_filters, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_log_screen_btn_reset_filters, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_log_screen_btn_reset_filters, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_log_screen_btn_reset_filters, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_log_screen_btn_reset_filters, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_log_screen_label_reset_filters = lv_label_create(ui_log_screen_btn_reset_filters);
    lv_obj_set_width(ui_log_screen_label_reset_filters, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_log_screen_label_reset_filters, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_log_screen_label_reset_filters, -3);
    lv_obj_set_y(ui_log_screen_label_reset_filters, 0);
    lv_obj_set_align(ui_log_screen_label_reset_filters, LV_ALIGN_CENTER);
    lv_label_set_text(ui_log_screen_label_reset_filters, "RESET");
    lv_obj_set_style_text_align(ui_log_screen_label_reset_filters, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_log_screen_label_reset_filters, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_log_btn_menu_log, ui_event_btn_menu_log, LV_EVENT_ALL, NULL);

}

void ui_log_screen_screen_destroy(void)
{
    if(ui_log_screen) lv_obj_del(ui_log_screen);

    // NULL screen variables
    ui_log_screen = NULL;
    ui_log_top_bar = NULL;
    ui_log_image_ce = NULL;
    ui_log_menu_bar = NULL;
    ui_log_screen_btn_img_log = NULL;
    ui_log_menu_container = NULL;
    ui_log_btn_menu_home = NULL;
    ui_log_btn_menu_main = NULL;
    ui_log_btn_menu_settings = NULL;
    ui_log_btn_menu_autom = NULL;
    ui_log_btn_menu_log = NULL;
    ui_log_btn_menu_aux = NULL;
    ui_log_btn_menu_debug = NULL;
    ui_log_buttons_container = NULL;
    ui_log_btn_feed_pump = NULL;
    ui_log_label_feed_pump = NULL;
    ui_log_btn_hp_pump = NULL;
    ui_log_label_hp_pump = NULL;
    ui_log_btn_flushing_cycle = NULL;
    ui_log_label_flushing_cycle = NULL;
    ui_log_btn_tank_test = NULL;
    ui_log_label_tank_test = NULL;
    ui_log_screen_container_system_totals = NULL;
    ui_log_screen_label_system_totals = NULL;
    ui_log_screen_panel_hp_pump = NULL;
    ui_log_screen_label_hp_pump = NULL;
    ui_log_screen_label_hp_pump_hours = NULL;
    ui_log_screen_label_hp_pump_minutes = NULL;
    ui_log_screen_panel_water_produced = NULL;
    ui_log_screen_label_water_produced = NULL;
    ui_log_screen_label_water_produced_liters = NULL;
    ui_log_screen_panel_average_prod = NULL;
    ui_log_screen_label_average_prod = NULL;
    ui_log_screen_label_average_prod_lh = NULL;
    ui_log_screen_container_system_partials = NULL;
    ui_log_screen_label_system_partials = NULL;
    ui_log_screen_panel_hp_pump_partial = NULL;
    ui_log_screen_label_hp_pump_partial = NULL;
    ui_log_screen_label_hp_pump_hours_partial = NULL;
    ui_log_screen_label_hp_pump_minutes_partial = NULL;
    ui_log_screen_panel_water_produced_partial = NULL;
    ui_log_screen_label_water_produced_partial = NULL;
    ui_log_screen_label_water_produced_liters_partial = NULL;
    ui_log_screen_panel_filters_hours = NULL;
    ui_log_screen_label_filters_hours = NULL;
    ui_log_screen_label_filters_hours_count = NULL;
    ui_log_screen_btn_reset_hours = NULL;
    ui_log_screen_label_reset_hours = NULL;
    ui_log_screen_btn_reset_liters = NULL;
    ui_log_screen_label_reset_liters = NULL;
    ui_log_screen_btn_reset_filters = NULL;
    ui_log_screen_label_reset_filters = NULL;

}
