// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 05 - Log Screen

#ifndef UI_LOG_SCREEN_H
#define UI_LOG_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_log_screen
extern void ui_log_screen_screen_init(void);
extern void ui_log_screen_screen_destroy(void);
extern lv_obj_t * ui_log_screen;
extern lv_obj_t * ui_log_top_bar;
extern lv_obj_t * ui_log_image_ce;
extern lv_obj_t * ui_log_menu_bar;
extern lv_obj_t * ui_log_screen_btn_img_log;
extern lv_obj_t * ui_log_menu_container;
extern lv_obj_t * ui_log_btn_menu_home;
extern lv_obj_t * ui_log_btn_menu_main;
extern lv_obj_t * ui_log_btn_menu_settings;
extern lv_obj_t * ui_log_btn_menu_autom;
extern void ui_event_btn_menu_log(lv_event_t * e);
extern lv_obj_t * ui_log_btn_menu_log;
extern lv_obj_t * ui_log_btn_menu_aux;
extern lv_obj_t * ui_log_btn_menu_debug;
extern lv_obj_t * ui_log_buttons_container;
extern lv_obj_t * ui_log_btn_feed_pump;
extern lv_obj_t * ui_log_label_feed_pump;
extern lv_obj_t * ui_log_btn_hp_pump;
extern lv_obj_t * ui_log_label_hp_pump;
extern lv_obj_t * ui_log_btn_flushing_cycle;
extern lv_obj_t * ui_log_label_flushing_cycle;
extern lv_obj_t * ui_log_btn_tank_test;
extern lv_obj_t * ui_log_label_tank_test;
extern lv_obj_t * ui_log_screen_container_system_totals;
extern lv_obj_t * ui_log_screen_label_system_totals;
extern lv_obj_t * ui_log_screen_panel_hp_pump;
extern lv_obj_t * ui_log_screen_label_hp_pump;
extern lv_obj_t * ui_log_screen_label_hp_pump_hours;
extern lv_obj_t * ui_log_screen_label_hp_pump_minutes;
extern lv_obj_t * ui_log_screen_panel_water_produced;
extern lv_obj_t * ui_log_screen_label_water_produced;
extern lv_obj_t * ui_log_screen_label_water_produced_liters;
extern lv_obj_t * ui_log_screen_panel_average_prod;
extern lv_obj_t * ui_log_screen_label_average_prod;
extern lv_obj_t * ui_log_screen_label_average_prod_lh;
extern lv_obj_t * ui_log_screen_container_system_partials;
extern lv_obj_t * ui_log_screen_label_system_partials;
extern lv_obj_t * ui_log_screen_panel_hp_pump_partial;
extern lv_obj_t * ui_log_screen_label_hp_pump_partial;
extern lv_obj_t * ui_log_screen_label_hp_pump_hours_partial;
extern lv_obj_t * ui_log_screen_label_hp_pump_minutes_partial;
extern lv_obj_t * ui_log_screen_panel_water_produced_partial;
extern lv_obj_t * ui_log_screen_label_water_produced_partial;
extern lv_obj_t * ui_log_screen_label_water_produced_liters_partial;
extern lv_obj_t * ui_log_screen_panel_filters_hours;
extern lv_obj_t * ui_log_screen_label_filters_hours;
extern lv_obj_t * ui_log_screen_label_filters_hours_count;
extern lv_obj_t * ui_log_screen_btn_reset_hours;
extern lv_obj_t * ui_log_screen_label_reset_hours;
extern lv_obj_t * ui_log_screen_btn_reset_liters;
extern lv_obj_t * ui_log_screen_label_reset_liters;
extern lv_obj_t * ui_log_screen_btn_reset_filters;
extern lv_obj_t * ui_log_screen_label_reset_filters;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

