// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 02 - Main Screen

#include "../ui.h"

lv_obj_t * ui_main_screen = NULL;
lv_obj_t * ui_main_top_bar = NULL;
lv_obj_t * ui_main_image_ce = NULL;
lv_obj_t * ui_main_menu_bar = NULL;
lv_obj_t * ui_main_screen_btn_img_main = NULL;
lv_obj_t * ui_main_menu_container = NULL;
lv_obj_t * ui_main_btn_menu_home = NULL;
lv_obj_t * ui_main_btn_menu_main = NULL;
lv_obj_t * ui_main_btn_menu_settings = NULL;
lv_obj_t * ui_main_btn_menu_autom = NULL;
lv_obj_t * ui_main_btn_menu_log = NULL;
lv_obj_t * ui_main_btn_menu_aux = NULL;
lv_obj_t * ui_main_btn_menu_debug = NULL;
lv_obj_t * ui_main_buttons_container = NULL;
lv_obj_t * ui_main_btn_feed_pump = NULL;
lv_obj_t * ui_main_label_feed_pump = NULL;
lv_obj_t * ui_main_btn_hp_pump = NULL;
lv_obj_t * ui_main_label_hp_pump = NULL;
lv_obj_t * ui_main_btn_flushing_cycle = NULL;
lv_obj_t * ui_main_label_flushing_cycle = NULL;
lv_obj_t * ui_main_btn_tank_test = NULL;
lv_obj_t * ui_main_label_tank_test = NULL;
lv_obj_t * ui_main_screen_image_bar_selector_bottom = NULL;
lv_obj_t * ui_main_screen_glow_3 = NULL;
lv_obj_t * ui_main_screen_glow_4 = NULL;
lv_obj_t * ui_main_screen_image_bar_selector_top = NULL;
lv_obj_t * ui_main_screen_label_bar_selector = NULL;
lv_obj_t * ui_main_screen_image_bar_selector_arrow_up = NULL;
lv_obj_t * ui_main_screen_image_bar_selector_arrow_down = NULL;
lv_obj_t * ui_main_screen_label_bar_selector_plus = NULL;
lv_obj_t * ui_main_screen_label_bar_selector_minus = NULL;
lv_obj_t * ui_main_screen_label_bar_gauge_pressure = NULL;
lv_obj_t * ui_main_screen_image_bar_gauge = NULL;
lv_obj_t * ui_main_screen_label_bar_gauge_bar = NULL;
lv_obj_t * ui_main_screen_label_bar_gauge_psi = NULL;
lv_obj_t * ui_main_screen_label_tds_gauge_tds = NULL;
lv_obj_t * ui_main_screen_image_bar_tds = NULL;
lv_obj_t * ui_main_screen_label_tds_gauge_center = NULL;
lv_obj_t * ui_main_screen_label_tds_gauge_upper = NULL;
lv_obj_t * ui_main_screen_label_tds_gauge_lower = NULL;
lv_obj_t * ui_main_screen_label_lph_gauge_production = NULL;
lv_obj_t * ui_main_screen_image_lph_gauge = NULL;
lv_obj_t * ui_main_screen_label_lph_gauge_lph = NULL;
lv_obj_t * ui_main_screen_label_lph_gauge_gpd = NULL;
lv_obj_t * ui_main_screen_panel_bar_preset_and_valve = NULL;
lv_obj_t * ui_main_screen_panel_bar_preset = NULL;
lv_obj_t * ui_main_screen_label_bar_psi_title = NULL;
lv_obj_t * ui_main_screen_label_bar_preset = NULL;
lv_obj_t * ui_main_screen_label_psi_preset = NULL;
lv_obj_t * ui_main_screen_panel_divider = NULL;
lv_obj_t * ui_main_screen_panel_valve_position = NULL;
lv_obj_t * ui_main_screen_label_valve_position_title = NULL;
lv_obj_t * ui_main_screen_label_valve_position_turns = NULL;
lv_obj_t * ui_main_screen_label_valve_position_total = NULL;
lv_obj_t * ui_main_screen_image_valve_closing = NULL;
lv_obj_t * ui_main_screen_image_valve_opening = NULL;
lv_obj_t * ui_main_screen_btn_auto_stop = NULL;
lv_obj_t * ui_main_screen_label_auto_stop = NULL;
lv_obj_t * ui_main_screen_switch_auto_pressure = NULL;
lv_obj_t * ui_main_screen_label_auto_pressure = NULL;
// event funtions
void ui_event_btn_menu_main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_main_screen_screen_init);
    }
}

void ui_event_main_screen_glow_3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        OpaOn_Animation(ui_main_screen_glow_3, 0);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OpaOff_Animation(ui_main_screen_glow_3, 0);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OpaOff_Animation(ui_main_screen_glow_3, 0);
    }
}

void ui_event_main_screen_glow_4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        OpaOn_Animation(ui_main_screen_glow_4, 0);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OpaOff_Animation(ui_main_screen_glow_4, 0);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OpaOff_Animation(ui_main_screen_glow_4, 0);
    }
}

// build funtions

void ui_main_screen_screen_init(void)
{
    ui_main_screen = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(ui_main_screen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_main_screen, lv_color_hex(0x596684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_top_bar = lv_image_create(ui_main_screen);
    lv_image_set_src(ui_main_top_bar, &ui_img_top_bar_png);
    lv_obj_set_width(ui_main_top_bar, LV_SIZE_CONTENT);   /// 681
    lv_obj_set_height(ui_main_top_bar, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_main_top_bar, 37);
    lv_obj_set_y(ui_main_top_bar, -218);
    lv_obj_set_align(ui_main_top_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_main_top_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_main_top_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_main_image_ce = lv_image_create(ui_main_screen);
    lv_image_set_src(ui_main_image_ce, &ui_img_625624875);
    lv_obj_set_width(ui_main_image_ce, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_main_image_ce, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_main_image_ce, 350);
    lv_obj_set_y(ui_main_image_ce, -221);
    lv_obj_set_align(ui_main_image_ce, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_main_image_ce, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_main_image_ce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_main_menu_bar = lv_image_create(ui_main_screen);
    lv_image_set_src(ui_main_menu_bar, &ui_img_menu_bar_png);
    lv_obj_set_width(ui_main_menu_bar, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_main_menu_bar, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_main_menu_bar, -363);
    lv_obj_set_y(ui_main_menu_bar, 0);
    lv_obj_set_align(ui_main_menu_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_main_menu_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_main_menu_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_main_screen_btn_img_main = lv_image_create(ui_main_screen);
    lv_image_set_src(ui_main_screen_btn_img_main, &ui_img_btn_main_png);
    lv_obj_set_width(ui_main_screen_btn_img_main, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_main_screen_btn_img_main, LV_SIZE_CONTENT);    /// 66
    lv_obj_set_x(ui_main_screen_btn_img_main, -360);
    lv_obj_set_y(ui_main_screen_btn_img_main, -133);
    lv_obj_set_align(ui_main_screen_btn_img_main, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_main_screen_btn_img_main, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_main_screen_btn_img_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_main_menu_container = lv_obj_create(ui_main_screen);
    lv_obj_remove_style_all(ui_main_menu_container);
    lv_obj_set_width(ui_main_menu_container, 83);
    lv_obj_set_height(ui_main_menu_container, 488);
    lv_obj_set_x(ui_main_menu_container, -2);
    lv_obj_set_y(ui_main_menu_container, -2);
    lv_obj_remove_flag(ui_main_menu_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_main_btn_menu_home = lv_image_create(ui_main_menu_container);
    lv_obj_set_width(ui_main_btn_menu_home, 74);
    lv_obj_set_height(ui_main_btn_menu_home, 65);
    lv_obj_set_x(ui_main_btn_menu_home, 5);
    lv_obj_set_y(ui_main_btn_menu_home, -412);
    lv_obj_set_align(ui_main_btn_menu_home, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_main_btn_menu_home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_main_btn_menu_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_main_btn_menu_home, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_main_btn_menu_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_btn_menu_main = lv_image_create(ui_main_menu_container);
    lv_obj_set_width(ui_main_btn_menu_main, 74);
    lv_obj_set_height(ui_main_btn_menu_main, 59);
    lv_obj_set_x(ui_main_btn_menu_main, 5);
    lv_obj_set_y(ui_main_btn_menu_main, -345);
    lv_obj_set_align(ui_main_btn_menu_main, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_main_btn_menu_main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_main_btn_menu_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_main_btn_menu_main, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_main_btn_menu_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_btn_menu_settings = lv_image_create(ui_main_menu_container);
    lv_obj_set_width(ui_main_btn_menu_settings, 74);
    lv_obj_set_height(ui_main_btn_menu_settings, 59);
    lv_obj_set_x(ui_main_btn_menu_settings, 5);
    lv_obj_set_y(ui_main_btn_menu_settings, -278);
    lv_obj_set_align(ui_main_btn_menu_settings, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_main_btn_menu_settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_main_btn_menu_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_main_btn_menu_settings, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_main_btn_menu_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_btn_menu_autom = lv_image_create(ui_main_menu_container);
    lv_obj_set_width(ui_main_btn_menu_autom, 74);
    lv_obj_set_height(ui_main_btn_menu_autom, 59);
    lv_obj_set_x(ui_main_btn_menu_autom, 5);
    lv_obj_set_y(ui_main_btn_menu_autom, -212);
    lv_obj_set_align(ui_main_btn_menu_autom, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_main_btn_menu_autom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_main_btn_menu_autom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_main_btn_menu_autom, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_main_btn_menu_autom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_btn_menu_log = lv_image_create(ui_main_menu_container);
    lv_obj_set_width(ui_main_btn_menu_log, 74);
    lv_obj_set_height(ui_main_btn_menu_log, 59);
    lv_obj_set_x(ui_main_btn_menu_log, 5);
    lv_obj_set_y(ui_main_btn_menu_log, -146);
    lv_obj_set_align(ui_main_btn_menu_log, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_main_btn_menu_log, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_main_btn_menu_log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_main_btn_menu_log, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_main_btn_menu_log, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_btn_menu_aux = lv_image_create(ui_main_menu_container);
    lv_obj_set_width(ui_main_btn_menu_aux, 74);
    lv_obj_set_height(ui_main_btn_menu_aux, 59);
    lv_obj_set_x(ui_main_btn_menu_aux, 5);
    lv_obj_set_y(ui_main_btn_menu_aux, -80);
    lv_obj_set_align(ui_main_btn_menu_aux, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_main_btn_menu_aux, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_main_btn_menu_aux, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_main_btn_menu_aux, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_main_btn_menu_aux, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_btn_menu_debug = lv_image_create(ui_main_menu_container);
    lv_obj_set_width(ui_main_btn_menu_debug, 74);
    lv_obj_set_height(ui_main_btn_menu_debug, 59);
    lv_obj_set_x(ui_main_btn_menu_debug, 5);
    lv_obj_set_y(ui_main_btn_menu_debug, -12);
    lv_obj_set_align(ui_main_btn_menu_debug, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_main_btn_menu_debug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_main_btn_menu_debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_main_btn_menu_debug, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_main_btn_menu_debug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_buttons_container = lv_obj_create(ui_main_screen);
    lv_obj_remove_style_all(ui_main_buttons_container);
    lv_obj_set_width(ui_main_buttons_container, 684);
    lv_obj_set_height(ui_main_buttons_container, 65);
    lv_obj_set_x(ui_main_buttons_container, 32);
    lv_obj_set_y(ui_main_buttons_container, 185);
    lv_obj_set_align(ui_main_buttons_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_main_buttons_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_main_btn_feed_pump = lv_imagebutton_create(ui_main_buttons_container);
    lv_imagebutton_set_src(ui_main_btn_feed_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_feed_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_main_btn_feed_pump, 66);
    lv_obj_set_width(ui_main_btn_feed_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_main_btn_feed_pump, 7);
    lv_obj_set_y(ui_main_btn_feed_pump, 0);
    lv_obj_set_align(ui_main_btn_feed_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_main_btn_feed_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_main_btn_feed_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_main_btn_feed_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_main_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_main_btn_feed_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_main_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_main_label_feed_pump = lv_label_create(ui_main_btn_feed_pump);
    lv_obj_set_width(ui_main_label_feed_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_label_feed_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_main_label_feed_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_label_feed_pump, "FEED PUMP");
    lv_obj_set_style_text_align(ui_main_label_feed_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_label_feed_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_btn_hp_pump = lv_imagebutton_create(ui_main_buttons_container);
    lv_imagebutton_set_src(ui_main_btn_hp_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_hp_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_main_btn_hp_pump, 66);
    lv_obj_set_width(ui_main_btn_hp_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_main_btn_hp_pump, 176);
    lv_obj_set_y(ui_main_btn_hp_pump, 0);
    lv_obj_set_align(ui_main_btn_hp_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_main_btn_hp_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_main_btn_hp_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_main_btn_hp_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_main_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_main_btn_hp_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_main_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_main_label_hp_pump = lv_label_create(ui_main_btn_hp_pump);
    lv_obj_set_width(ui_main_label_hp_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_label_hp_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_main_label_hp_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_label_hp_pump, "H.P. PUMP");
    lv_obj_set_style_text_align(ui_main_label_hp_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_label_hp_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_btn_flushing_cycle = lv_imagebutton_create(ui_main_buttons_container);
    lv_imagebutton_set_src(ui_main_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_main_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_obj_set_height(ui_main_btn_flushing_cycle, 66);
    lv_obj_set_width(ui_main_btn_flushing_cycle, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_main_btn_flushing_cycle, 351);
    lv_obj_set_y(ui_main_btn_flushing_cycle, 0);
    lv_obj_set_align(ui_main_btn_flushing_cycle, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_main_btn_flushing_cycle, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_main_btn_flushing_cycle, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_main_btn_flushing_cycle, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_main_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_main_btn_flushing_cycle, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_main_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_main_label_flushing_cycle = lv_label_create(ui_main_btn_flushing_cycle);
    lv_obj_set_width(ui_main_label_flushing_cycle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_label_flushing_cycle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_main_label_flushing_cycle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_label_flushing_cycle, "FLUSHING\nCYCLE");
    lv_obj_set_style_text_align(ui_main_label_flushing_cycle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_label_flushing_cycle, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_btn_tank_test = lv_imagebutton_create(ui_main_buttons_container);
    lv_imagebutton_set_src(ui_main_btn_tank_test, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_tank_test, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_main_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_main_btn_tank_test, 66);
    lv_obj_set_width(ui_main_btn_tank_test, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_main_btn_tank_test, 522);
    lv_obj_set_y(ui_main_btn_tank_test, 0);
    lv_obj_set_align(ui_main_btn_tank_test, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_main_btn_tank_test, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_main_btn_tank_test, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_main_btn_tank_test, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_main_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_main_btn_tank_test, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_main_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_main_label_tank_test = lv_label_create(ui_main_btn_tank_test);
    lv_obj_set_width(ui_main_label_tank_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_label_tank_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_main_label_tank_test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_label_tank_test, "WATER\nTO TANK");
    lv_obj_set_style_text_align(ui_main_label_tank_test, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_label_tank_test, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_image_bar_selector_bottom = lv_image_create(ui_main_screen);
    lv_image_set_src(ui_main_screen_image_bar_selector_bottom, &ui_img_btn_z_botton_png);
    lv_obj_set_width(ui_main_screen_image_bar_selector_bottom, 140);
    lv_obj_set_height(ui_main_screen_image_bar_selector_bottom, 312);
    lv_obj_set_x(ui_main_screen_image_bar_selector_bottom, -232);
    lv_obj_set_y(ui_main_screen_image_bar_selector_bottom, -24);
    lv_obj_set_align(ui_main_screen_image_bar_selector_bottom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_main_screen_image_bar_selector_bottom, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_image_set_inner_align(ui_main_screen_image_bar_selector_bottom, LV_IMAGE_ALIGN_TILE);

    ui_main_screen_glow_3 = lv_obj_create(ui_main_screen_image_bar_selector_bottom);
    lv_obj_set_width(ui_main_screen_glow_3, 75);
    lv_obj_set_height(ui_main_screen_glow_3, 70);
    lv_obj_set_x(ui_main_screen_glow_3, 0);
    lv_obj_set_y(ui_main_screen_glow_3, 34);
    lv_obj_set_align(ui_main_screen_glow_3, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_main_screen_glow_3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_main_screen_glow_3, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_glow_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_main_screen_glow_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_main_screen_glow_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_main_screen_glow_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_main_screen_glow_3, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_main_screen_glow_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_main_screen_glow_3, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_main_screen_glow_3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_main_screen_glow_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_glow_4 = lv_obj_create(ui_main_screen_image_bar_selector_bottom);
    lv_obj_set_width(ui_main_screen_glow_4, 75);
    lv_obj_set_height(ui_main_screen_glow_4, 70);
    lv_obj_set_x(ui_main_screen_glow_4, 0);
    lv_obj_set_y(ui_main_screen_glow_4, 211);
    lv_obj_set_align(ui_main_screen_glow_4, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_main_screen_glow_4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_main_screen_glow_4, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_glow_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_main_screen_glow_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_main_screen_glow_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_main_screen_glow_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_main_screen_glow_4, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_main_screen_glow_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_main_screen_glow_4, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_main_screen_glow_4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_main_screen_glow_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_image_bar_selector_top = lv_image_create(ui_main_screen_image_bar_selector_bottom);
    lv_image_set_src(ui_main_screen_image_bar_selector_top, &ui_img_btn_z_top_png);
    lv_obj_set_width(ui_main_screen_image_bar_selector_top, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_main_screen_image_bar_selector_top, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_main_screen_image_bar_selector_top, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_main_screen_image_bar_selector_top, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_main_screen_label_bar_selector = lv_label_create(ui_main_screen_image_bar_selector_bottom);
    lv_obj_set_width(ui_main_screen_label_bar_selector, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_bar_selector, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_main_screen_label_bar_selector, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_bar_selector, "BAR\n-\nPSI");
    lv_obj_set_style_text_color(ui_main_screen_label_bar_selector, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_bar_selector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_bar_selector, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_bar_selector, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_image_bar_selector_arrow_up = lv_image_create(ui_main_screen_image_bar_selector_bottom);
    lv_image_set_src(ui_main_screen_image_bar_selector_arrow_up, &ui_img_arrow_up_png);
    lv_obj_set_width(ui_main_screen_image_bar_selector_arrow_up, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_main_screen_image_bar_selector_arrow_up, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_main_screen_image_bar_selector_arrow_up, 0);
    lv_obj_set_y(ui_main_screen_image_bar_selector_arrow_up, 44);
    lv_obj_set_align(ui_main_screen_image_bar_selector_arrow_up, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_main_screen_image_bar_selector_arrow_up,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_image_recolor(ui_main_screen_image_bar_selector_arrow_up, lv_color_hex(0xABC1ED),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_main_screen_image_bar_selector_arrow_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(ui_main_screen_image_bar_selector_arrow_up, lv_color_hex(0x00D1FF),
                                   LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_image_recolor_opa(ui_main_screen_image_bar_selector_arrow_up, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_image_recolor(ui_main_screen_image_bar_selector_arrow_up, lv_color_hex(0x00D1FF),
                                   LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_main_screen_image_bar_selector_arrow_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_main_screen_image_bar_selector_arrow_down = lv_image_create(ui_main_screen_image_bar_selector_bottom);
    lv_image_set_src(ui_main_screen_image_bar_selector_arrow_down, &ui_img_arrow_down_png);
    lv_obj_set_width(ui_main_screen_image_bar_selector_arrow_down, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_main_screen_image_bar_selector_arrow_down, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_main_screen_image_bar_selector_arrow_down, 0);
    lv_obj_set_y(ui_main_screen_image_bar_selector_arrow_down, -44);
    lv_obj_set_align(ui_main_screen_image_bar_selector_arrow_down, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_main_screen_image_bar_selector_arrow_down, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_image_recolor(ui_main_screen_image_bar_selector_arrow_down, lv_color_hex(0xABC1ED),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_main_screen_image_bar_selector_arrow_down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(ui_main_screen_image_bar_selector_arrow_down, lv_color_hex(0x00D2FF),
                                   LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_image_recolor_opa(ui_main_screen_image_bar_selector_arrow_down, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_main_screen_label_bar_selector_plus = lv_label_create(ui_main_screen_image_bar_selector_bottom);
    lv_obj_set_width(ui_main_screen_label_bar_selector_plus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_bar_selector_plus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_main_screen_label_bar_selector_plus, -1);
    lv_obj_set_y(ui_main_screen_label_bar_selector_plus, -73);
    lv_obj_set_align(ui_main_screen_label_bar_selector_plus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_bar_selector_plus, "+");
    lv_obj_set_style_text_color(ui_main_screen_label_bar_selector_plus, lv_color_hex(0xABC1ED),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_bar_selector_plus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_bar_selector_plus, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_bar_selector_plus, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_bar_selector_minus = lv_label_create(ui_main_screen_image_bar_selector_bottom);
    lv_obj_set_width(ui_main_screen_label_bar_selector_minus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_bar_selector_minus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_main_screen_label_bar_selector_minus, 0);
    lv_obj_set_y(ui_main_screen_label_bar_selector_minus, 71);
    lv_obj_set_align(ui_main_screen_label_bar_selector_minus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_bar_selector_minus, "-");
    lv_obj_set_style_text_color(ui_main_screen_label_bar_selector_minus, lv_color_hex(0xABC1ED),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_bar_selector_minus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_bar_selector_minus, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_bar_selector_minus, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_bar_gauge_pressure = lv_label_create(ui_main_screen);
    lv_obj_set_width(ui_main_screen_label_bar_gauge_pressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_bar_gauge_pressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_main_screen_label_bar_gauge_pressure, -84);
    lv_obj_set_y(ui_main_screen_label_bar_gauge_pressure, 250);
    lv_obj_set_align(ui_main_screen_label_bar_gauge_pressure, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_main_screen_label_bar_gauge_pressure, "PRESSURE");
    lv_obj_set_style_text_color(ui_main_screen_label_bar_gauge_pressure, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_bar_gauge_pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_bar_gauge_pressure, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_bar_gauge_pressure, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_image_bar_gauge = lv_image_create(ui_main_screen);
    lv_image_set_src(ui_main_screen_image_bar_gauge, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_main_screen_image_bar_gauge, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_main_screen_image_bar_gauge, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_main_screen_image_bar_gauge, -82);
    lv_obj_set_y(ui_main_screen_image_bar_gauge, -78);
    lv_obj_set_align(ui_main_screen_image_bar_gauge, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_main_screen_image_bar_gauge,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_main_screen_label_bar_gauge_bar = lv_label_create(ui_main_screen_image_bar_gauge);
    lv_obj_set_width(ui_main_screen_label_bar_gauge_bar, 130);
    lv_obj_set_height(ui_main_screen_label_bar_gauge_bar, 40);
    lv_obj_set_x(ui_main_screen_label_bar_gauge_bar, 0);
    lv_obj_set_y(ui_main_screen_label_bar_gauge_bar, -23);
    lv_obj_set_align(ui_main_screen_label_bar_gauge_bar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_bar_gauge_bar, "55 bar");
    lv_obj_set_style_text_color(ui_main_screen_label_bar_gauge_bar, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_bar_gauge_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_bar_gauge_bar, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_bar_gauge_bar, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_main_screen_label_bar_gauge_bar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_main_screen_label_bar_gauge_bar, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_label_bar_gauge_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_screen_label_bar_gauge_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_screen_label_bar_gauge_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_screen_label_bar_gauge_bar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_screen_label_bar_gauge_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_bar_gauge_psi = lv_label_create(ui_main_screen_image_bar_gauge);
    lv_obj_set_width(ui_main_screen_label_bar_gauge_psi, 130);
    lv_obj_set_height(ui_main_screen_label_bar_gauge_psi, 40);
    lv_obj_set_x(ui_main_screen_label_bar_gauge_psi, 0);
    lv_obj_set_y(ui_main_screen_label_bar_gauge_psi, 20);
    lv_obj_set_align(ui_main_screen_label_bar_gauge_psi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_bar_gauge_psi, "350 psi");
    lv_obj_set_style_text_color(ui_main_screen_label_bar_gauge_psi, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_bar_gauge_psi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_bar_gauge_psi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_bar_gauge_psi, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_main_screen_label_bar_gauge_psi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_main_screen_label_bar_gauge_psi, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_label_bar_gauge_psi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_screen_label_bar_gauge_psi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_screen_label_bar_gauge_psi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_screen_label_bar_gauge_psi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_screen_label_bar_gauge_psi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_tds_gauge_tds = lv_label_create(ui_main_screen);
    lv_obj_set_width(ui_main_screen_label_tds_gauge_tds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_tds_gauge_tds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_main_screen_label_tds_gauge_tds, 98);
    lv_obj_set_y(ui_main_screen_label_tds_gauge_tds, 250);
    lv_obj_set_align(ui_main_screen_label_tds_gauge_tds, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_main_screen_label_tds_gauge_tds, "TDS");
    lv_obj_set_style_text_color(ui_main_screen_label_tds_gauge_tds, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_tds_gauge_tds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_tds_gauge_tds, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_tds_gauge_tds, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_image_bar_tds = lv_image_create(ui_main_screen);
    lv_image_set_src(ui_main_screen_image_bar_tds, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_main_screen_image_bar_tds, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_main_screen_image_bar_tds, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_main_screen_image_bar_tds, 101);
    lv_obj_set_y(ui_main_screen_image_bar_tds, -78);
    lv_obj_set_align(ui_main_screen_image_bar_tds, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_main_screen_image_bar_tds, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_main_screen_label_tds_gauge_center = lv_label_create(ui_main_screen_image_bar_tds);
    lv_obj_set_width(ui_main_screen_label_tds_gauge_center, 131);
    lv_obj_set_height(ui_main_screen_label_tds_gauge_center, 40);
    lv_obj_set_x(ui_main_screen_label_tds_gauge_center, 0);
    lv_obj_set_y(ui_main_screen_label_tds_gauge_center, -1);
    lv_obj_set_align(ui_main_screen_label_tds_gauge_center, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_tds_gauge_center, "155");
    lv_obj_set_style_text_color(ui_main_screen_label_tds_gauge_center, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_tds_gauge_center, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_tds_gauge_center, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_tds_gauge_center, &lv_font_montserrat_28,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_main_screen_label_tds_gauge_center, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_main_screen_label_tds_gauge_center, lv_color_hex(0x3F475E),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_label_tds_gauge_center, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_screen_label_tds_gauge_center, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_screen_label_tds_gauge_center, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_screen_label_tds_gauge_center, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_screen_label_tds_gauge_center, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_tds_gauge_upper = lv_label_create(ui_main_screen_image_bar_tds);
    lv_obj_set_width(ui_main_screen_label_tds_gauge_upper, 131);
    lv_obj_set_height(ui_main_screen_label_tds_gauge_upper, 30);
    lv_obj_set_x(ui_main_screen_label_tds_gauge_upper, 3);
    lv_obj_set_y(ui_main_screen_label_tds_gauge_upper, -36);
    lv_obj_set_align(ui_main_screen_label_tds_gauge_upper, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_tds_gauge_upper, "154");
    lv_obj_set_style_text_color(ui_main_screen_label_tds_gauge_upper, lv_color_hex(0x3F475E),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_tds_gauge_upper, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_tds_gauge_upper, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_tds_gauge_upper, &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_tds_gauge_lower = lv_label_create(ui_main_screen_image_bar_tds);
    lv_obj_set_width(ui_main_screen_label_tds_gauge_lower, 131);
    lv_obj_set_height(ui_main_screen_label_tds_gauge_lower, 30);
    lv_obj_set_x(ui_main_screen_label_tds_gauge_lower, 3);
    lv_obj_set_y(ui_main_screen_label_tds_gauge_lower, 45);
    lv_obj_set_align(ui_main_screen_label_tds_gauge_lower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_tds_gauge_lower, "156");
    lv_obj_set_style_text_color(ui_main_screen_label_tds_gauge_lower, lv_color_hex(0x3F475E),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_tds_gauge_lower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_tds_gauge_lower, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_tds_gauge_lower, &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_lph_gauge_production = lv_label_create(ui_main_screen);
    lv_obj_set_width(ui_main_screen_label_lph_gauge_production, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_lph_gauge_production, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_main_screen_label_lph_gauge_production, 290);
    lv_obj_set_y(ui_main_screen_label_lph_gauge_production, 250);
    lv_obj_set_align(ui_main_screen_label_lph_gauge_production, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_main_screen_label_lph_gauge_production, "PRODUCTION");
    lv_obj_set_style_text_color(ui_main_screen_label_lph_gauge_production, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_lph_gauge_production, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_lph_gauge_production, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_lph_gauge_production, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_image_lph_gauge = lv_image_create(ui_main_screen);
    lv_image_set_src(ui_main_screen_image_lph_gauge, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_main_screen_image_lph_gauge, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_main_screen_image_lph_gauge, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_main_screen_image_lph_gauge, 291);
    lv_obj_set_y(ui_main_screen_image_lph_gauge, -78);
    lv_obj_set_align(ui_main_screen_image_lph_gauge, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_main_screen_image_lph_gauge,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_main_screen_label_lph_gauge_lph = lv_label_create(ui_main_screen_image_lph_gauge);
    lv_obj_set_width(ui_main_screen_label_lph_gauge_lph, 130);
    lv_obj_set_height(ui_main_screen_label_lph_gauge_lph, 40);
    lv_obj_set_x(ui_main_screen_label_lph_gauge_lph, 0);
    lv_obj_set_y(ui_main_screen_label_lph_gauge_lph, -23);
    lv_obj_set_align(ui_main_screen_label_lph_gauge_lph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_lph_gauge_lph, "120 l/h");
    lv_obj_set_style_text_color(ui_main_screen_label_lph_gauge_lph, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_lph_gauge_lph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_lph_gauge_lph, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_lph_gauge_lph, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_main_screen_label_lph_gauge_lph, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_main_screen_label_lph_gauge_lph, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_label_lph_gauge_lph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_screen_label_lph_gauge_lph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_screen_label_lph_gauge_lph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_screen_label_lph_gauge_lph, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_screen_label_lph_gauge_lph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_lph_gauge_gpd = lv_label_create(ui_main_screen_image_lph_gauge);
    lv_obj_set_width(ui_main_screen_label_lph_gauge_gpd, 130);
    lv_obj_set_height(ui_main_screen_label_lph_gauge_gpd, 40);
    lv_obj_set_x(ui_main_screen_label_lph_gauge_gpd, 0);
    lv_obj_set_y(ui_main_screen_label_lph_gauge_gpd, 20);
    lv_obj_set_align(ui_main_screen_label_lph_gauge_gpd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_lph_gauge_gpd, "350 gpd");
    lv_obj_set_style_text_color(ui_main_screen_label_lph_gauge_gpd, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_lph_gauge_gpd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_lph_gauge_gpd, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_lph_gauge_gpd, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_main_screen_label_lph_gauge_gpd, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_main_screen_label_lph_gauge_gpd, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_label_lph_gauge_gpd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_screen_label_lph_gauge_gpd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_screen_label_lph_gauge_gpd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_screen_label_lph_gauge_gpd, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_screen_label_lph_gauge_gpd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_panel_bar_preset_and_valve = lv_obj_create(ui_main_screen);
    lv_obj_set_width(ui_main_screen_panel_bar_preset_and_valve, 350);
    lv_obj_set_height(ui_main_screen_panel_bar_preset_and_valve, 79);
    lv_obj_set_x(ui_main_screen_panel_bar_preset_and_valve, -37);
    lv_obj_set_y(ui_main_screen_panel_bar_preset_and_valve, 288);
    lv_obj_set_align(ui_main_screen_panel_bar_preset_and_valve, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_main_screen_panel_bar_preset_and_valve, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main_screen_panel_bar_preset_and_valve, lv_color_hex(0x191D26),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_panel_bar_preset_and_valve, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_main_screen_panel_bar_preset_and_valve, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_main_screen_panel_bar_preset_and_valve, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_main_screen_panel_bar_preset_and_valve, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_main_screen_panel_bar_preset_and_valve, lv_color_hex(0x414B62),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_main_screen_panel_bar_preset_and_valve, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_main_screen_panel_bar_preset_and_valve, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_main_screen_panel_bar_preset_and_valve, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_screen_panel_bar_preset_and_valve, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_screen_panel_bar_preset_and_valve, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_screen_panel_bar_preset_and_valve, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_screen_panel_bar_preset_and_valve, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_panel_bar_preset = lv_obj_create(ui_main_screen_panel_bar_preset_and_valve);
    lv_obj_set_width(ui_main_screen_panel_bar_preset, lv_pct(50));
    lv_obj_set_height(ui_main_screen_panel_bar_preset, lv_pct(100));
    lv_obj_set_align(ui_main_screen_panel_bar_preset, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_main_screen_panel_bar_preset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main_screen_panel_bar_preset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_panel_bar_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_main_screen_panel_bar_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_main_screen_panel_bar_preset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_main_screen_panel_bar_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_screen_panel_bar_preset, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_screen_panel_bar_preset, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_screen_panel_bar_preset, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_screen_panel_bar_preset, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_bar_psi_title = lv_label_create(ui_main_screen_panel_bar_preset);
    lv_obj_set_width(ui_main_screen_label_bar_psi_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_bar_psi_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_main_screen_label_bar_psi_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_main_screen_label_bar_psi_title, "Preset BAR - PSI");
    lv_obj_set_style_text_color(ui_main_screen_label_bar_psi_title, lv_color_hex(0x9098AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_bar_psi_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_bar_psi_title, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_bar_preset = lv_label_create(ui_main_screen_panel_bar_preset);
    lv_obj_set_width(ui_main_screen_label_bar_preset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_bar_preset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_main_screen_label_bar_preset, 44);
    lv_obj_set_y(ui_main_screen_label_bar_preset, 10);
    lv_obj_set_align(ui_main_screen_label_bar_preset, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_main_screen_label_bar_preset, "58");
    lv_obj_set_style_text_color(ui_main_screen_label_bar_preset, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_bar_preset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_bar_preset, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_bar_preset, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_label_psi_preset = lv_label_create(ui_main_screen_panel_bar_preset);
    lv_obj_set_width(ui_main_screen_label_psi_preset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_psi_preset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_main_screen_label_psi_preset, 85);
    lv_obj_set_y(ui_main_screen_label_psi_preset, 13);
    lv_obj_set_align(ui_main_screen_label_psi_preset, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_main_screen_label_psi_preset, "- 785");
    lv_obj_set_style_text_color(ui_main_screen_label_psi_preset, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_psi_preset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_psi_preset, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_panel_divider = lv_obj_create(ui_main_screen_panel_bar_preset_and_valve);
    lv_obj_set_width(ui_main_screen_panel_divider, 2);
    lv_obj_set_height(ui_main_screen_panel_divider, 50);
    lv_obj_set_align(ui_main_screen_panel_divider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_main_screen_panel_divider, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_panel_divider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_main_screen_panel_divider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_main_screen_panel_divider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_main_screen_panel_divider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*
     * AUTO STOP command button.
     *
     * First-stage UI only:
     * - no machine logic is attached yet;
     * - normal image is OFF;
     * - while pressed it uses the existing illuminated ON image;
     * - CHECKED images are already configured for the later state-machine stage,
     *   when the glow must remain active throughout AUTO STOP.
     */
    ui_main_screen_btn_auto_stop = lv_imagebutton_create(ui_main_screen_panel_bar_preset_and_valve);
    lv_imagebutton_set_src(ui_main_screen_btn_auto_stop, LV_IMAGEBUTTON_STATE_RELEASED,
                           NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_main_screen_btn_auto_stop, LV_IMAGEBUTTON_STATE_PRESSED,
                           NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_main_screen_btn_auto_stop, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED,
                           NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_main_screen_btn_auto_stop, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED,
                           NULL, &ui_img_btn_main_on_png, NULL);
    //lv_obj_set_width(ui_main_screen_btn_auto_stop, 100);
    //lv_obj_set_height(ui_main_screen_btn_auto_stop, 66);
	lv_obj_set_height(ui_main_screen_btn_auto_stop, 66);
	lv_obj_set_width(ui_main_screen_btn_auto_stop, LV_SIZE_CONTENT);
    //lv_obj_set_x(ui_main_screen_btn_auto_stop, 87);
    //lv_obj_set_y(ui_main_screen_btn_auto_stop, 0);
    //lv_obj_set_align(ui_main_screen_btn_auto_stop, LV_ALIGN_CENTER);
	lv_obj_set_align(ui_main_screen_btn_auto_stop, LV_ALIGN_RIGHT_MID);
	lv_obj_set_x(ui_main_screen_btn_auto_stop, -10);
	lv_obj_set_y(ui_main_screen_btn_auto_stop, 0);
    lv_obj_remove_flag(ui_main_screen_btn_auto_stop, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_text_color(ui_main_screen_btn_auto_stop, lv_color_hex(0xABC1ED),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_btn_auto_stop, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_main_screen_btn_auto_stop, lv_color_hex(0x00B9FF),
                                LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_main_screen_btn_auto_stop, 255,
                              LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_main_screen_btn_auto_stop, lv_color_hex(0x06CEFB),
                                LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_main_screen_btn_auto_stop, 255,
                              LV_PART_MAIN | LV_STATE_PRESSED);

    ui_main_screen_label_auto_stop = lv_label_create(ui_main_screen_btn_auto_stop);
    lv_obj_set_width(ui_main_screen_label_auto_stop, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_main_screen_label_auto_stop, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_main_screen_label_auto_stop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_screen_label_auto_stop, "AUTO\nSTOP");
    lv_obj_set_style_text_align(ui_main_screen_label_auto_stop, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_auto_stop, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_screen_switch_auto_pressure = lv_switch_create(ui_main_screen);
    lv_obj_set_width(ui_main_screen_switch_auto_pressure, 90);
    lv_obj_set_height(ui_main_screen_switch_auto_pressure, 40);
    lv_obj_set_x(ui_main_screen_switch_auto_pressure, -86);
    lv_obj_set_y(ui_main_screen_switch_auto_pressure, 65);
    lv_obj_set_align(ui_main_screen_switch_auto_pressure, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_main_screen_switch_auto_pressure, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_switch_auto_pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_main_screen_switch_auto_pressure, lv_color_hex(0x191D26),
                                  LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_main_screen_switch_auto_pressure, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_main_screen_switch_auto_pressure, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_main_screen_switch_auto_pressure, LV_BORDER_SIDE_FULL,
                                 LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_main_screen_switch_auto_pressure, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen_switch_auto_pressure, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_main_screen_switch_auto_pressure, lv_color_hex(0x536483),
                                   LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_main_screen_switch_auto_pressure, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_main_screen_switch_auto_pressure, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_main_screen_switch_auto_pressure, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_screen_switch_auto_pressure, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_screen_switch_auto_pressure, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_screen_switch_auto_pressure, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_screen_switch_auto_pressure, -5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_main_screen_label_auto_pressure = lv_label_create(ui_main_screen);
    lv_obj_set_width(ui_main_screen_label_auto_pressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_screen_label_auto_pressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_main_screen_label_auto_pressure, -88);
    lv_obj_set_y(ui_main_screen_label_auto_pressure, 336);
    lv_obj_set_align(ui_main_screen_label_auto_pressure, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_main_screen_label_auto_pressure, "AUTOMATIC\nPRESSURE");
    lv_obj_set_style_text_color(ui_main_screen_label_auto_pressure, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_screen_label_auto_pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_screen_label_auto_pressure, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_screen_label_auto_pressure, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_main_btn_menu_main, ui_event_btn_menu_main, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_main_screen_glow_3, ui_event_main_screen_glow_3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_main_screen_glow_4, ui_event_main_screen_glow_4, LV_EVENT_ALL, NULL);

}

void ui_main_screen_screen_destroy(void)
{
    if(ui_main_screen) lv_obj_del(ui_main_screen);

    // NULL screen variables
    ui_main_screen = NULL;
    ui_main_top_bar = NULL;
    ui_main_image_ce = NULL;
    ui_main_menu_bar = NULL;
    ui_main_screen_btn_img_main = NULL;
    ui_main_menu_container = NULL;
    ui_main_btn_menu_home = NULL;
    ui_main_btn_menu_main = NULL;
    ui_main_btn_menu_settings = NULL;
    ui_main_btn_menu_autom = NULL;
    ui_main_btn_menu_log = NULL;
    ui_main_btn_menu_aux = NULL;
    ui_main_btn_menu_debug = NULL;
    ui_main_buttons_container = NULL;
    ui_main_btn_feed_pump = NULL;
    ui_main_label_feed_pump = NULL;
    ui_main_btn_hp_pump = NULL;
    ui_main_label_hp_pump = NULL;
    ui_main_btn_flushing_cycle = NULL;
    ui_main_label_flushing_cycle = NULL;
    ui_main_btn_tank_test = NULL;
    ui_main_label_tank_test = NULL;
    ui_main_screen_image_bar_selector_bottom = NULL;
    ui_main_screen_glow_3 = NULL;
    ui_main_screen_glow_4 = NULL;
    ui_main_screen_image_bar_selector_top = NULL;
    ui_main_screen_label_bar_selector = NULL;
    ui_main_screen_image_bar_selector_arrow_up = NULL;
    ui_main_screen_image_bar_selector_arrow_down = NULL;
    ui_main_screen_label_bar_selector_plus = NULL;
    ui_main_screen_label_bar_selector_minus = NULL;
    ui_main_screen_label_bar_gauge_pressure = NULL;
    ui_main_screen_image_bar_gauge = NULL;
    ui_main_screen_label_bar_gauge_bar = NULL;
    ui_main_screen_label_bar_gauge_psi = NULL;
    ui_main_screen_label_tds_gauge_tds = NULL;
    ui_main_screen_image_bar_tds = NULL;
    ui_main_screen_label_tds_gauge_center = NULL;
    ui_main_screen_label_tds_gauge_upper = NULL;
    ui_main_screen_label_tds_gauge_lower = NULL;
    ui_main_screen_label_lph_gauge_production = NULL;
    ui_main_screen_image_lph_gauge = NULL;
    ui_main_screen_label_lph_gauge_lph = NULL;
    ui_main_screen_label_lph_gauge_gpd = NULL;
    ui_main_screen_panel_bar_preset_and_valve = NULL;
    ui_main_screen_panel_bar_preset = NULL;
    ui_main_screen_label_bar_psi_title = NULL;
    ui_main_screen_label_bar_preset = NULL;
    ui_main_screen_label_psi_preset = NULL;
    ui_main_screen_panel_divider = NULL;
    ui_main_screen_panel_valve_position = NULL;
    ui_main_screen_label_valve_position_title = NULL;
    ui_main_screen_label_valve_position_turns = NULL;
    ui_main_screen_label_valve_position_total = NULL;
    ui_main_screen_image_valve_closing = NULL;
    ui_main_screen_image_valve_opening = NULL;
    ui_main_screen_btn_auto_stop = NULL;
    ui_main_screen_label_auto_stop = NULL;
    ui_main_screen_switch_auto_pressure = NULL;
    ui_main_screen_label_auto_pressure = NULL;

}
