// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 03 - Settings Screen

#include "../ui.h"

lv_obj_t * ui_settings_screen = NULL;
lv_obj_t * ui_settings_top_bar = NULL;
lv_obj_t * ui_settings_image_ce = NULL;
lv_obj_t * ui_settings_menu_bar = NULL;
lv_obj_t * ui_settings_screen_btn_img_settings = NULL;
lv_obj_t * ui_settings_menu_container = NULL;
lv_obj_t * ui_settings_btn_menu_home = NULL;
lv_obj_t * ui_settings_btn_menu_main = NULL;
lv_obj_t * ui_settings_btn_menu_settings = NULL;
lv_obj_t * ui_settings_btn_menu_autom = NULL;
lv_obj_t * ui_settings_btn_menu_log = NULL;
lv_obj_t * ui_settings_btn_menu_aux = NULL;
lv_obj_t * ui_settings_btn_menu_debug = NULL;
lv_obj_t * ui_settings_buttons_container = NULL;
lv_obj_t * ui_settings_btn_feed_pump = NULL;
lv_obj_t * ui_settings_label_feed_pump = NULL;
lv_obj_t * ui_settings_btn_hp_pump = NULL;
lv_obj_t * ui_settings_label_hp_pump = NULL;
lv_obj_t * ui_settings_btn_flushing_cycle = NULL;
lv_obj_t * ui_settings_label_flushing_cycle = NULL;
lv_obj_t * ui_settings_btn_tank_test = NULL;
lv_obj_t * ui_settings_label_tank_test = NULL;
lv_obj_t * ui_settings_screen_panel_flush_preset = NULL;
lv_obj_t * ui_settings_screen_image_flush_preset = NULL;
lv_obj_t * ui_settings_screen_roller_flush_preset = NULL;
lv_obj_t * ui_settings_screen_panel_flow_fine_tuning = NULL;
lv_obj_t * ui_settings_screen_image_flow_fine_tuning = NULL;
lv_obj_t * ui_settings_screen_roller_flow_fine_tuning = NULL;
lv_obj_t * ui_settings_screen_panel_flow_sens_selector = NULL;
lv_obj_t * ui_settings_screen_image_flow_sens_selector = NULL;
lv_obj_t * ui_settings_screen_roller_flow_sens_selector = NULL;
lv_obj_t * ui_settings_screen_panel_pulses_x_liter = NULL;
lv_obj_t * ui_settings_screen_image_step_speed = NULL;
lv_obj_t * ui_settings_screen_roller_step_speed = NULL;
lv_obj_t * ui_settings_screen_label_flush_preset = NULL;
lv_obj_t * ui_settings_screen_label_flow_fine_tuning = NULL;
lv_obj_t * ui_settings_screen_label_flow_sens_selector = NULL;
lv_obj_t * ui_settings_screen_label_step_speed = NULL;
lv_obj_t * ui_settings_screen_panel_flushing_ttg = NULL;
lv_obj_t * ui_settings_screen_panel_divider_ttg = NULL;
lv_obj_t * ui_settings_screen_label_ttg_time = NULL;
lv_obj_t * ui_settings_screen_img_ttg_clock = NULL;
lv_obj_t * ui_settings_screen_label_ttg_text = NULL;
lv_obj_t * ui_settings_screen_label_ttg_flushing_text = NULL;
lv_obj_t * ui_settings_screen_btn_save = NULL;
lv_obj_t * ui_settings_screen_label_save = NULL;
lv_obj_t * ui_settings_screen_image_cobram = NULL;
// event funtions
void ui_event_btn_menu_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings_screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_settings_screen_screen_init);
    }
}

// build funtions

void ui_settings_screen_screen_init(void)
{
    ui_settings_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_settings_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_settings_screen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_settings_screen, lv_color_hex(0x596684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_top_bar = lv_image_create(ui_settings_screen);
    lv_image_set_src(ui_settings_top_bar, &ui_img_top_bar_png);
    lv_obj_set_width(ui_settings_top_bar, LV_SIZE_CONTENT);   /// 681
    lv_obj_set_height(ui_settings_top_bar, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_settings_top_bar, 37);
    lv_obj_set_y(ui_settings_top_bar, -218);
    lv_obj_set_align(ui_settings_top_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_top_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_settings_top_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_image_ce = lv_image_create(ui_settings_screen);
    lv_image_set_src(ui_settings_image_ce, &ui_img_625624875);
    lv_obj_set_width(ui_settings_image_ce, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_settings_image_ce, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_settings_image_ce, 350);
    lv_obj_set_y(ui_settings_image_ce, -221);
    lv_obj_set_align(ui_settings_image_ce, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_image_ce, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_settings_image_ce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_menu_bar = lv_image_create(ui_settings_screen);
    lv_image_set_src(ui_settings_menu_bar, &ui_img_menu_bar_png);
    lv_obj_set_width(ui_settings_menu_bar, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_settings_menu_bar, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_settings_menu_bar, -363);
    lv_obj_set_y(ui_settings_menu_bar, 0);
    lv_obj_set_align(ui_settings_menu_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_menu_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_settings_menu_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_btn_img_settings = lv_image_create(ui_settings_screen);
    lv_image_set_src(ui_settings_screen_btn_img_settings, &ui_img_btn_settings_png);
    lv_obj_set_width(ui_settings_screen_btn_img_settings, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_settings_screen_btn_img_settings, LV_SIZE_CONTENT);    /// 66
    lv_obj_set_x(ui_settings_screen_btn_img_settings, -360);
    lv_obj_set_y(ui_settings_screen_btn_img_settings, -65);
    lv_obj_set_align(ui_settings_screen_btn_img_settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_screen_btn_img_settings, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_settings_screen_btn_img_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_menu_container = lv_obj_create(ui_settings_screen);
    lv_obj_remove_style_all(ui_settings_menu_container);
    lv_obj_set_width(ui_settings_menu_container, 83);
    lv_obj_set_height(ui_settings_menu_container, 488);
    lv_obj_set_x(ui_settings_menu_container, -2);
    lv_obj_set_y(ui_settings_menu_container, -2);
    lv_obj_remove_flag(ui_settings_menu_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_btn_menu_home = lv_image_create(ui_settings_menu_container);
    lv_obj_set_width(ui_settings_btn_menu_home, 74);
    lv_obj_set_height(ui_settings_btn_menu_home, 65);
    lv_obj_set_x(ui_settings_btn_menu_home, 5);
    lv_obj_set_y(ui_settings_btn_menu_home, -412);
    lv_obj_set_align(ui_settings_btn_menu_home, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_settings_btn_menu_home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings_btn_menu_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_settings_btn_menu_home, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_settings_btn_menu_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_btn_menu_main = lv_image_create(ui_settings_menu_container);
    lv_obj_set_width(ui_settings_btn_menu_main, 74);
    lv_obj_set_height(ui_settings_btn_menu_main, 59);
    lv_obj_set_x(ui_settings_btn_menu_main, 5);
    lv_obj_set_y(ui_settings_btn_menu_main, -345);
    lv_obj_set_align(ui_settings_btn_menu_main, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_settings_btn_menu_main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings_btn_menu_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_settings_btn_menu_main, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_settings_btn_menu_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_btn_menu_settings = lv_image_create(ui_settings_menu_container);
    lv_obj_set_width(ui_settings_btn_menu_settings, 74);
    lv_obj_set_height(ui_settings_btn_menu_settings, 59);
    lv_obj_set_x(ui_settings_btn_menu_settings, 5);
    lv_obj_set_y(ui_settings_btn_menu_settings, -278);
    lv_obj_set_align(ui_settings_btn_menu_settings, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_settings_btn_menu_settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings_btn_menu_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_settings_btn_menu_settings, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_settings_btn_menu_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_btn_menu_autom = lv_image_create(ui_settings_menu_container);
    lv_obj_set_width(ui_settings_btn_menu_autom, 74);
    lv_obj_set_height(ui_settings_btn_menu_autom, 59);
    lv_obj_set_x(ui_settings_btn_menu_autom, 5);
    lv_obj_set_y(ui_settings_btn_menu_autom, -212);
    lv_obj_set_align(ui_settings_btn_menu_autom, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_settings_btn_menu_autom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings_btn_menu_autom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_settings_btn_menu_autom, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_settings_btn_menu_autom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_btn_menu_log = lv_image_create(ui_settings_menu_container);
    lv_obj_set_width(ui_settings_btn_menu_log, 74);
    lv_obj_set_height(ui_settings_btn_menu_log, 59);
    lv_obj_set_x(ui_settings_btn_menu_log, 5);
    lv_obj_set_y(ui_settings_btn_menu_log, -146);
    lv_obj_set_align(ui_settings_btn_menu_log, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_settings_btn_menu_log, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings_btn_menu_log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_settings_btn_menu_log, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_settings_btn_menu_log, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_btn_menu_aux = lv_image_create(ui_settings_menu_container);
    lv_obj_set_width(ui_settings_btn_menu_aux, 74);
    lv_obj_set_height(ui_settings_btn_menu_aux, 59);
    lv_obj_set_x(ui_settings_btn_menu_aux, 5);
    lv_obj_set_y(ui_settings_btn_menu_aux, -80);
    lv_obj_set_align(ui_settings_btn_menu_aux, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_settings_btn_menu_aux, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings_btn_menu_aux, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_settings_btn_menu_aux, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_settings_btn_menu_aux, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_btn_menu_debug = lv_image_create(ui_settings_menu_container);
    lv_obj_set_width(ui_settings_btn_menu_debug, 74);
    lv_obj_set_height(ui_settings_btn_menu_debug, 59);
    lv_obj_set_x(ui_settings_btn_menu_debug, 5);
    lv_obj_set_y(ui_settings_btn_menu_debug, -12);
    lv_obj_set_align(ui_settings_btn_menu_debug, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_settings_btn_menu_debug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings_btn_menu_debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_settings_btn_menu_debug, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_settings_btn_menu_debug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_buttons_container = lv_obj_create(ui_settings_screen);
    lv_obj_remove_style_all(ui_settings_buttons_container);
    lv_obj_set_width(ui_settings_buttons_container, 684);
    lv_obj_set_height(ui_settings_buttons_container, 65);
    lv_obj_set_x(ui_settings_buttons_container, 32);
    lv_obj_set_y(ui_settings_buttons_container, 185);
    lv_obj_set_align(ui_settings_buttons_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_buttons_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_btn_feed_pump = lv_imagebutton_create(ui_settings_buttons_container);
    lv_imagebutton_set_src(ui_settings_btn_feed_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_feed_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_feed_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_settings_btn_feed_pump, 66);
    lv_obj_set_width(ui_settings_btn_feed_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_settings_btn_feed_pump, 7);
    lv_obj_set_y(ui_settings_btn_feed_pump, 0);
    lv_obj_set_align(ui_settings_btn_feed_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_settings_btn_feed_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_settings_btn_feed_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_settings_btn_feed_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_settings_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_settings_btn_feed_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_settings_btn_feed_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_settings_label_feed_pump = lv_label_create(ui_settings_btn_feed_pump);
    lv_obj_set_width(ui_settings_label_feed_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_label_feed_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_label_feed_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_label_feed_pump, "FEED PUMP");
    lv_obj_set_style_text_align(ui_settings_label_feed_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_label_feed_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_btn_hp_pump = lv_imagebutton_create(ui_settings_buttons_container);
    lv_imagebutton_set_src(ui_settings_btn_hp_pump, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_hp_pump, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_hp_pump, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_settings_btn_hp_pump, 66);
    lv_obj_set_width(ui_settings_btn_hp_pump, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_settings_btn_hp_pump, 176);
    lv_obj_set_y(ui_settings_btn_hp_pump, 0);
    lv_obj_set_align(ui_settings_btn_hp_pump, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_settings_btn_hp_pump, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_settings_btn_hp_pump, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_settings_btn_hp_pump, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_settings_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_settings_btn_hp_pump, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_settings_btn_hp_pump, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_settings_label_hp_pump = lv_label_create(ui_settings_btn_hp_pump);
    lv_obj_set_width(ui_settings_label_hp_pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_label_hp_pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_label_hp_pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_label_hp_pump, "H.P. PUMP");
    lv_obj_set_style_text_align(ui_settings_label_hp_pump, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_label_hp_pump, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_btn_flushing_cycle = lv_imagebutton_create(ui_settings_buttons_container);
    lv_imagebutton_set_src(ui_settings_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_settings_btn_flushing_cycle, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_obj_set_height(ui_settings_btn_flushing_cycle, 66);
    lv_obj_set_width(ui_settings_btn_flushing_cycle, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_settings_btn_flushing_cycle, 351);
    lv_obj_set_y(ui_settings_btn_flushing_cycle, 0);
    lv_obj_set_align(ui_settings_btn_flushing_cycle, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_settings_btn_flushing_cycle, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_settings_btn_flushing_cycle, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_settings_btn_flushing_cycle, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_settings_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_settings_btn_flushing_cycle, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_settings_btn_flushing_cycle, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_settings_label_flushing_cycle = lv_label_create(ui_settings_btn_flushing_cycle);
    lv_obj_set_width(ui_settings_label_flushing_cycle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_label_flushing_cycle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_label_flushing_cycle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_label_flushing_cycle, "FLUSHING\nCYCLE");
    lv_obj_set_style_text_align(ui_settings_label_flushing_cycle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_label_flushing_cycle, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_btn_tank_test = lv_imagebutton_create(ui_settings_buttons_container);
    lv_imagebutton_set_src(ui_settings_btn_tank_test, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_tank_test, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_settings_btn_tank_test, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_settings_btn_tank_test, 66);
    lv_obj_set_width(ui_settings_btn_tank_test, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_settings_btn_tank_test, 522);
    lv_obj_set_y(ui_settings_btn_tank_test, 0);
    lv_obj_set_align(ui_settings_btn_tank_test, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_settings_btn_tank_test, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_settings_btn_tank_test, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_settings_btn_tank_test, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_settings_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_settings_btn_tank_test, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_settings_btn_tank_test, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_settings_label_tank_test = lv_label_create(ui_settings_btn_tank_test);
    lv_obj_set_width(ui_settings_label_tank_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_label_tank_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_label_tank_test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_label_tank_test, "WATER\nTO TANK");
    lv_obj_set_style_text_align(ui_settings_label_tank_test, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_label_tank_test, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_panel_flush_preset = lv_obj_create(ui_settings_screen);
    lv_obj_set_height(ui_settings_screen_panel_flush_preset, 215);
    lv_obj_set_width(ui_settings_screen_panel_flush_preset, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_settings_screen_panel_flush_preset, 86);
    lv_obj_set_y(ui_settings_screen_panel_flush_preset, 46);
    lv_obj_remove_flag(ui_settings_screen_panel_flush_preset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_screen_panel_flush_preset, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_panel_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_panel_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_panel_flush_preset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_panel_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_settings_screen_panel_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_settings_screen_panel_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_settings_screen_panel_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_settings_screen_panel_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_image_flush_preset = lv_image_create(ui_settings_screen_panel_flush_preset);
    lv_image_set_src(ui_settings_screen_image_flush_preset, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_settings_screen_image_flush_preset, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_settings_screen_image_flush_preset, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_settings_screen_image_flush_preset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_screen_image_flush_preset, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_settings_screen_roller_flush_preset = lv_roller_create(ui_settings_screen_panel_flush_preset);
    lv_roller_set_options(ui_settings_screen_roller_flush_preset,
                          "2 min.\n3 min.\n4 min.\n5 min.\n6 min.\n7 min.\n8 min.\n9 min.\n10 min.\n15 min.\n20 min.\n", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_settings_screen_roller_flush_preset, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_settings_screen_roller_flush_preset, 142);
    lv_obj_set_height(ui_settings_screen_roller_flush_preset, 131);
    lv_obj_set_align(ui_settings_screen_roller_flush_preset, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_settings_screen_roller_flush_preset, lv_color_hex(0x3F475E),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_roller_flush_preset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_roller_flush_preset, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_screen_roller_flush_preset, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_roller_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_roller_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_roller_flush_preset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_roller_flush_preset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_settings_screen_roller_flush_preset, lv_color_hex(0xDBE6FF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_roller_flush_preset, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_roller_flush_preset, &lv_font_montserrat_26,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_screen_roller_flush_preset, lv_color_hex(0x3A445C),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_roller_flush_preset, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_settings_screen_panel_flow_fine_tuning = lv_obj_create(ui_settings_screen);
    lv_obj_set_height(ui_settings_screen_panel_flow_fine_tuning, 215);
    lv_obj_set_width(ui_settings_screen_panel_flow_fine_tuning, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_settings_screen_panel_flow_fine_tuning, 260);
    lv_obj_set_y(ui_settings_screen_panel_flow_fine_tuning, 46);
    lv_obj_remove_flag(ui_settings_screen_panel_flow_fine_tuning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_screen_panel_flow_fine_tuning, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_panel_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_panel_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_panel_flow_fine_tuning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_panel_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_settings_screen_panel_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_settings_screen_panel_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_settings_screen_panel_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_settings_screen_panel_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_image_flow_fine_tuning = lv_image_create(ui_settings_screen_panel_flow_fine_tuning);
    lv_image_set_src(ui_settings_screen_image_flow_fine_tuning, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_settings_screen_image_flow_fine_tuning, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_settings_screen_image_flow_fine_tuning, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_settings_screen_image_flow_fine_tuning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_screen_image_flow_fine_tuning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_settings_screen_roller_flow_fine_tuning = lv_roller_create(ui_settings_screen_panel_flow_fine_tuning);
    lv_roller_set_options(ui_settings_screen_roller_flow_fine_tuning,
                      "-15 %\n-10 %\n-5 %\n0 %\n5 %\n10 %\n15 %",
                      LV_ROLLER_MODE_INFINITE);
lv_roller_set_selected(ui_settings_screen_roller_flow_fine_tuning, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_settings_screen_roller_flow_fine_tuning, 142);
    lv_obj_set_height(ui_settings_screen_roller_flow_fine_tuning, 131);
    lv_obj_set_align(ui_settings_screen_roller_flow_fine_tuning, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_settings_screen_roller_flow_fine_tuning, lv_color_hex(0x3F475E),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_roller_flow_fine_tuning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_roller_flow_fine_tuning, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_screen_roller_flow_fine_tuning, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_roller_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_roller_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_roller_flow_fine_tuning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_roller_flow_fine_tuning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_settings_screen_roller_flow_fine_tuning, lv_color_hex(0xDBE6FF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_roller_flow_fine_tuning, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_roller_flow_fine_tuning, &lv_font_montserrat_26,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_screen_roller_flow_fine_tuning, lv_color_hex(0x3A445C),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_roller_flow_fine_tuning, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_settings_screen_panel_flow_sens_selector = lv_obj_create(ui_settings_screen);
    lv_obj_set_height(ui_settings_screen_panel_flow_sens_selector, 215);
    lv_obj_set_width(ui_settings_screen_panel_flow_sens_selector, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_settings_screen_panel_flow_sens_selector, 427);
    lv_obj_set_y(ui_settings_screen_panel_flow_sens_selector, 46);
    lv_obj_remove_flag(ui_settings_screen_panel_flow_sens_selector, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_screen_panel_flow_sens_selector, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_panel_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_panel_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_panel_flow_sens_selector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_panel_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_settings_screen_panel_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_settings_screen_panel_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_settings_screen_panel_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_settings_screen_panel_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_image_flow_sens_selector = lv_image_create(ui_settings_screen_panel_flow_sens_selector);
    lv_image_set_src(ui_settings_screen_image_flow_sens_selector, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_settings_screen_image_flow_sens_selector, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_settings_screen_image_flow_sens_selector, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_settings_screen_image_flow_sens_selector, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_screen_image_flow_sens_selector, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_settings_screen_roller_flow_sens_selector = lv_roller_create(ui_settings_screen_panel_flow_sens_selector);
    lv_roller_set_options(ui_settings_screen_roller_flow_sens_selector, "Sensor A\nSensor B\nSensor C",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_settings_screen_roller_flow_sens_selector, 142);
    lv_obj_set_height(ui_settings_screen_roller_flow_sens_selector, 131);
    lv_obj_set_align(ui_settings_screen_roller_flow_sens_selector, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_settings_screen_roller_flow_sens_selector, lv_color_hex(0x3F475E),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_roller_flow_sens_selector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_roller_flow_sens_selector, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_screen_roller_flow_sens_selector, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_roller_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_roller_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_roller_flow_sens_selector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_roller_flow_sens_selector, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_settings_screen_roller_flow_sens_selector, lv_color_hex(0xDBE6FF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_roller_flow_sens_selector, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_roller_flow_sens_selector, &lv_font_montserrat_26,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_screen_roller_flow_sens_selector, lv_color_hex(0x3A445C),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_roller_flow_sens_selector, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_settings_screen_panel_pulses_x_liter = lv_obj_create(ui_settings_screen);
    lv_obj_set_height(ui_settings_screen_panel_pulses_x_liter, 215);
    lv_obj_set_width(ui_settings_screen_panel_pulses_x_liter, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_settings_screen_panel_pulses_x_liter, 593);
    lv_obj_set_y(ui_settings_screen_panel_pulses_x_liter, 46);
    lv_obj_remove_flag(ui_settings_screen_panel_pulses_x_liter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_screen_panel_pulses_x_liter, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_panel_pulses_x_liter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_panel_pulses_x_liter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_panel_pulses_x_liter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_panel_pulses_x_liter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_settings_screen_panel_pulses_x_liter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_settings_screen_panel_pulses_x_liter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_settings_screen_panel_pulses_x_liter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_settings_screen_panel_pulses_x_liter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_image_step_speed = lv_image_create(ui_settings_screen_panel_pulses_x_liter);
    lv_image_set_src(ui_settings_screen_image_step_speed, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_settings_screen_image_step_speed, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_settings_screen_image_step_speed, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_settings_screen_image_step_speed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_screen_image_step_speed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_settings_screen_roller_step_speed = lv_roller_create(ui_settings_screen_panel_pulses_x_liter);
    lv_roller_set_options(ui_settings_screen_roller_step_speed, "Slow\nMid\nHigh", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_settings_screen_roller_step_speed, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_settings_screen_roller_step_speed, 142);
    lv_obj_set_height(ui_settings_screen_roller_step_speed, 131);
    lv_obj_set_align(ui_settings_screen_roller_step_speed, LV_ALIGN_CENTER);
	//lv_obj_clear_flag(ui_settings_screen_roller_step_speed, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_text_color(ui_settings_screen_roller_step_speed, lv_color_hex(0x3F475E),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_roller_step_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_roller_step_speed, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_screen_roller_step_speed, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_roller_step_speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_roller_step_speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_roller_step_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_roller_step_speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_settings_screen_roller_step_speed, lv_color_hex(0xDBE6FF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_roller_step_speed, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_roller_step_speed, &lv_font_montserrat_26,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_screen_roller_step_speed, lv_color_hex(0x3A445C),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_roller_step_speed, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_settings_screen_label_flush_preset = lv_label_create(ui_settings_screen);
    lv_obj_set_width(ui_settings_screen_label_flush_preset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_flush_preset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settings_screen_label_flush_preset, -223);
    lv_obj_set_y(ui_settings_screen_label_flush_preset, 242);
    lv_obj_set_align(ui_settings_screen_label_flush_preset, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_settings_screen_label_flush_preset, "FLUSHING TIME\nPRESET");
    lv_obj_set_style_text_color(ui_settings_screen_label_flush_preset, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_label_flush_preset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_settings_screen_label_flush_preset, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_label_flush_preset, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_label_flow_fine_tuning = lv_label_create(ui_settings_screen);
    lv_obj_set_width(ui_settings_screen_label_flow_fine_tuning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_flow_fine_tuning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settings_screen_label_flow_fine_tuning, -50);
    lv_obj_set_y(ui_settings_screen_label_flow_fine_tuning, 242);
    lv_obj_set_align(ui_settings_screen_label_flow_fine_tuning, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_settings_screen_label_flow_fine_tuning, "FLOW FINE\nTUNING");
    lv_obj_set_style_text_color(ui_settings_screen_label_flow_fine_tuning, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_label_flow_fine_tuning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_settings_screen_label_flow_fine_tuning, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_label_flow_fine_tuning, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_label_flow_sens_selector = lv_label_create(ui_settings_screen);
    lv_obj_set_width(ui_settings_screen_label_flow_sens_selector, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_flow_sens_selector, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settings_screen_label_flow_sens_selector, 119);
    lv_obj_set_y(ui_settings_screen_label_flow_sens_selector, 242);
    lv_obj_set_align(ui_settings_screen_label_flow_sens_selector, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_settings_screen_label_flow_sens_selector, "FLOW SENSOR\nSELECTOR");
    lv_obj_set_style_text_color(ui_settings_screen_label_flow_sens_selector, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_label_flow_sens_selector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_settings_screen_label_flow_sens_selector, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_label_flow_sens_selector, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_label_step_speed = lv_label_create(ui_settings_screen);
    lv_obj_set_width(ui_settings_screen_label_step_speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_step_speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settings_screen_label_step_speed, 282);
    lv_obj_set_y(ui_settings_screen_label_step_speed, 242);
    lv_obj_set_align(ui_settings_screen_label_step_speed, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_settings_screen_label_step_speed, "NEEDLE VALVE\nSPEED");
    lv_obj_set_style_text_color(ui_settings_screen_label_step_speed, lv_color_hex(0xD2DCF2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_label_step_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_settings_screen_label_step_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_label_step_speed, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_panel_flushing_ttg = lv_obj_create(ui_settings_screen);
    lv_obj_set_width(ui_settings_screen_panel_flushing_ttg, 314);
    lv_obj_set_height(ui_settings_screen_panel_flushing_ttg, 74);
    lv_obj_set_x(ui_settings_screen_panel_flushing_ttg, -386);
    lv_obj_set_y(ui_settings_screen_panel_flushing_ttg, 305);
    lv_obj_set_align(ui_settings_screen_panel_flushing_ttg, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_settings_screen_panel_flushing_ttg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_screen_panel_flushing_ttg, lv_color_hex(0x191D26),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_panel_flushing_ttg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_panel_flushing_ttg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_panel_flushing_ttg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_panel_flushing_ttg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_settings_screen_panel_flushing_ttg, lv_color_hex(0x414B62),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_settings_screen_panel_flushing_ttg, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_settings_screen_panel_flushing_ttg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_settings_screen_panel_flushing_ttg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_settings_screen_panel_flushing_ttg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_settings_screen_panel_flushing_ttg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_settings_screen_panel_flushing_ttg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_settings_screen_panel_flushing_ttg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_panel_divider_ttg = lv_obj_create(ui_settings_screen_panel_flushing_ttg);
    lv_obj_set_width(ui_settings_screen_panel_divider_ttg, 2);
    lv_obj_set_height(ui_settings_screen_panel_divider_ttg, 50);
    lv_obj_set_x(ui_settings_screen_panel_divider_ttg, -27);
    lv_obj_set_y(ui_settings_screen_panel_divider_ttg, 0);
    lv_obj_set_align(ui_settings_screen_panel_divider_ttg, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_settings_screen_panel_divider_ttg, lv_color_hex(0x3A3F4B),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_screen_panel_divider_ttg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settings_screen_panel_divider_ttg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settings_screen_panel_divider_ttg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_screen_panel_divider_ttg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_label_ttg_time = lv_label_create(ui_settings_screen_panel_flushing_ttg);
    lv_obj_set_width(ui_settings_screen_label_ttg_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_ttg_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settings_screen_label_ttg_time, 190);
    lv_obj_set_y(ui_settings_screen_label_ttg_time, 14);
    lv_obj_set_align(ui_settings_screen_label_ttg_time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_ttg_time, "10:52");
    lv_obj_set_style_text_color(ui_settings_screen_label_ttg_time, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_label_ttg_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_label_ttg_time, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_img_ttg_clock = lv_image_create(ui_settings_screen_panel_flushing_ttg);
    lv_image_set_src(ui_settings_screen_img_ttg_clock, &ui_img_icn_time_1_png);
    lv_obj_set_width(ui_settings_screen_img_ttg_clock, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_settings_screen_img_ttg_clock, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_settings_screen_img_ttg_clock, 160);
    lv_obj_set_y(ui_settings_screen_img_ttg_clock, -19);
    lv_obj_set_align(ui_settings_screen_img_ttg_clock, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_settings_screen_img_ttg_clock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_settings_screen_label_ttg_text = lv_label_create(ui_settings_screen_panel_flushing_ttg);
    lv_obj_set_width(ui_settings_screen_label_ttg_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_ttg_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settings_screen_label_ttg_text, 81);
    lv_obj_set_y(ui_settings_screen_label_ttg_text, 10);
    lv_obj_set_align(ui_settings_screen_label_ttg_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_settings_screen_label_ttg_text, "Time To Go");
    lv_obj_set_style_text_color(ui_settings_screen_label_ttg_text, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_label_ttg_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_label_ttg_text, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_label_ttg_flushing_text = lv_label_create(ui_settings_screen_panel_flushing_ttg);
    lv_obj_set_width(ui_settings_screen_label_ttg_flushing_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_ttg_flushing_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settings_screen_label_ttg_flushing_text, -92);
    lv_obj_set_y(ui_settings_screen_label_ttg_flushing_text, 28);
    lv_obj_set_align(ui_settings_screen_label_ttg_flushing_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_settings_screen_label_ttg_flushing_text, "FLUSHING");
    lv_obj_set_style_text_color(ui_settings_screen_label_ttg_flushing_text, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_label_ttg_flushing_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_label_ttg_flushing_text, &ui_font_Small_Font,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_btn_save = lv_imagebutton_create(ui_settings_screen);
    lv_imagebutton_set_src(ui_settings_screen_btn_save, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png,
                           NULL);
    lv_imagebutton_set_src(ui_settings_screen_btn_save, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_settings_screen_btn_save, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_imagebutton_set_src(ui_settings_screen_btn_save, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL,
                           &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_settings_screen_btn_save, 66);
    lv_obj_set_width(ui_settings_screen_btn_save, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_settings_screen_btn_save, -200);
    lv_obj_set_y(ui_settings_screen_btn_save, 311);
    lv_obj_set_align(ui_settings_screen_btn_save, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_settings_screen_btn_save, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_screen_btn_save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_settings_screen_btn_save, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_settings_screen_btn_save, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_settings_screen_btn_save, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_settings_screen_btn_save, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_settings_screen_label_save = lv_label_create(ui_settings_screen_btn_save);
    lv_obj_set_width(ui_settings_screen_label_save, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_save, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_save, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_screen_label_save, "SAVE ALL\nSETTINGS");
    lv_obj_set_style_text_align(ui_settings_screen_label_save, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_label_save, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_image_cobram = lv_image_create(ui_settings_screen);
    lv_image_set_src(ui_settings_screen_image_cobram, &ui_img_logo_negativo_traspsrente_130_px_png);
    lv_obj_set_width(ui_settings_screen_image_cobram, LV_SIZE_CONTENT);   /// 130
    lv_obj_set_height(ui_settings_screen_image_cobram, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_settings_screen_image_cobram, 290);
    lv_obj_set_y(ui_settings_screen_image_cobram, 103);
    lv_obj_set_align(ui_settings_screen_image_cobram, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_screen_image_cobram, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_settings_screen_image_cobram, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_settings_btn_menu_settings, ui_event_btn_menu_settings, LV_EVENT_ALL, NULL);

}

void ui_settings_screen_screen_destroy(void)
{
    if(ui_settings_screen) lv_obj_del(ui_settings_screen);

    // NULL screen variables
    ui_settings_screen = NULL;
    ui_settings_top_bar = NULL;
    ui_settings_image_ce = NULL;
    ui_settings_menu_bar = NULL;
    ui_settings_screen_btn_img_settings = NULL;
    ui_settings_menu_container = NULL;
    ui_settings_btn_menu_home = NULL;
    ui_settings_btn_menu_main = NULL;
    ui_settings_btn_menu_settings = NULL;
    ui_settings_btn_menu_autom = NULL;
    ui_settings_btn_menu_log = NULL;
    ui_settings_btn_menu_aux = NULL;
    ui_settings_btn_menu_debug = NULL;
    ui_settings_buttons_container = NULL;
    ui_settings_btn_feed_pump = NULL;
    ui_settings_label_feed_pump = NULL;
    ui_settings_btn_hp_pump = NULL;
    ui_settings_label_hp_pump = NULL;
    ui_settings_btn_flushing_cycle = NULL;
    ui_settings_label_flushing_cycle = NULL;
    ui_settings_btn_tank_test = NULL;
    ui_settings_label_tank_test = NULL;
    ui_settings_screen_panel_flush_preset = NULL;
    ui_settings_screen_image_flush_preset = NULL;
    ui_settings_screen_roller_flush_preset = NULL;
    ui_settings_screen_panel_flow_fine_tuning = NULL;
    ui_settings_screen_image_flow_fine_tuning = NULL;
    ui_settings_screen_roller_flow_fine_tuning = NULL;
    ui_settings_screen_panel_flow_sens_selector = NULL;
    ui_settings_screen_image_flow_sens_selector = NULL;
    ui_settings_screen_roller_flow_sens_selector = NULL;
    ui_settings_screen_panel_pulses_x_liter = NULL;
    ui_settings_screen_image_step_speed = NULL;
    ui_settings_screen_roller_step_speed = NULL;
    ui_settings_screen_label_flush_preset = NULL;
    ui_settings_screen_label_flow_fine_tuning = NULL;
    ui_settings_screen_label_flow_sens_selector = NULL;
    ui_settings_screen_label_step_speed = NULL;
    ui_settings_screen_panel_flushing_ttg = NULL;
    ui_settings_screen_panel_divider_ttg = NULL;
    ui_settings_screen_label_ttg_time = NULL;
    ui_settings_screen_img_ttg_clock = NULL;
    ui_settings_screen_label_ttg_text = NULL;
    ui_settings_screen_label_ttg_flushing_text = NULL;
    ui_settings_screen_btn_save = NULL;
    ui_settings_screen_label_save = NULL;
    ui_settings_screen_image_cobram = NULL;

}
