// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 03 - Settings Screen

#ifndef UI_SETTINGS_SCREEN_H
#define UI_SETTINGS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings_screen
extern void ui_settings_screen_screen_init(void);
extern void ui_settings_screen_screen_destroy(void);
extern lv_obj_t * ui_settings_screen;
extern lv_obj_t * ui_settings_top_bar;
extern lv_obj_t * ui_settings_image_ce;
extern lv_obj_t * ui_settings_menu_bar;
extern lv_obj_t * ui_settings_screen_btn_img_settings;
extern lv_obj_t * ui_settings_menu_container;
extern lv_obj_t * ui_settings_btn_menu_home;
extern lv_obj_t * ui_settings_btn_menu_main;
extern void ui_event_btn_menu_settings(lv_event_t * e);
extern lv_obj_t * ui_settings_btn_menu_settings;
extern lv_obj_t * ui_settings_btn_menu_autom;
extern lv_obj_t * ui_settings_btn_menu_log;
extern lv_obj_t * ui_settings_btn_menu_aux;
extern lv_obj_t * ui_settings_btn_menu_debug;
extern lv_obj_t * ui_settings_buttons_container;
extern lv_obj_t * ui_settings_btn_feed_pump;
extern lv_obj_t * ui_settings_label_feed_pump;
extern lv_obj_t * ui_settings_btn_hp_pump;
extern lv_obj_t * ui_settings_label_hp_pump;
extern lv_obj_t * ui_settings_btn_flushing_cycle;
extern lv_obj_t * ui_settings_label_flushing_cycle;
extern lv_obj_t * ui_settings_btn_tank_test;
extern lv_obj_t * ui_settings_label_tank_test;
extern lv_obj_t * ui_settings_screen_panel_flush_preset;
extern lv_obj_t * ui_settings_screen_image_flush_preset;
extern lv_obj_t * ui_settings_screen_roller_flush_preset;
extern lv_obj_t * ui_settings_screen_panel_flow_fine_tuning;
extern lv_obj_t * ui_settings_screen_image_flow_fine_tuning;
extern lv_obj_t * ui_settings_screen_roller_flow_fine_tuning;
extern lv_obj_t * ui_settings_screen_panel_flow_sens_selector;
extern lv_obj_t * ui_settings_screen_image_flow_sens_selector;
extern lv_obj_t * ui_settings_screen_roller_flow_sens_selector;
extern lv_obj_t * ui_settings_screen_panel_pulses_x_liter;
extern lv_obj_t * ui_settings_screen_image_step_speed;
extern lv_obj_t * ui_settings_screen_roller_step_speed;
extern lv_obj_t * ui_settings_screen_label_flush_preset;
extern lv_obj_t * ui_settings_screen_label_flow_fine_tuning;
extern lv_obj_t * ui_settings_screen_label_flow_sens_selector;
extern lv_obj_t * ui_settings_screen_label_step_speed;
extern lv_obj_t * ui_settings_screen_panel_flushing_ttg;
extern lv_obj_t * ui_settings_screen_panel_divider_ttg;
extern lv_obj_t * ui_settings_screen_label_ttg_time;
extern lv_obj_t * ui_settings_screen_img_ttg_clock;
extern lv_obj_t * ui_settings_screen_label_ttg_text;
extern lv_obj_t * ui_settings_screen_label_ttg_flushing_text;
extern lv_obj_t * ui_settings_screen_btn_save;
extern lv_obj_t * ui_settings_screen_label_save;
extern lv_obj_t * ui_settings_screen_image_cobram;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

