// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: 01 - Splash Screen

#include "../ui.h"

lv_obj_t * ui_splash_screen = NULL;
lv_obj_t * ui_splash_top_bar = NULL;
lv_obj_t * ui_splash_image_ce = NULL;
lv_obj_t * ui_splash_menu_bar = NULL;
lv_obj_t * ui_splash_screen_btn_img_home = NULL;
lv_obj_t * ui_splash_menu_container = NULL;
lv_obj_t * ui_splash_btn_menu_home = NULL;
lv_obj_t * ui_splash_btn_menu_main = NULL;
lv_obj_t * ui_splash_btn_menu_settings = NULL;
lv_obj_t * ui_splash_btn_menu_autom = NULL;
lv_obj_t * ui_splash_btn_menu_log = NULL;
lv_obj_t * ui_splash_btn_menu_aux = NULL;
lv_obj_t * ui_splash_btn_menu_debug = NULL;
lv_obj_t * ui_splash_screen_text_warning = NULL;
lv_obj_t * ui_splash_screen_image_qr_code = NULL;
lv_obj_t * ui_splash_screen_text_created_by = NULL;
// event funtions
void ui_event_btn_menu_home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_splash_screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_splash_screen_screen_init);
    }
}

// build funtions

void ui_splash_screen_screen_init(void)
{
    ui_splash_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_splash_screen,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_bg_color(ui_splash_screen, lv_color_hex(0x596684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_splash_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_top_bar = lv_image_create(ui_splash_screen);
    lv_image_set_src(ui_splash_top_bar, &ui_img_top_bar_png);
    lv_obj_set_width(ui_splash_top_bar, LV_SIZE_CONTENT);   /// 681
    lv_obj_set_height(ui_splash_top_bar, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_splash_top_bar, 37);
    lv_obj_set_y(ui_splash_top_bar, -218);
    lv_obj_set_align(ui_splash_top_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_splash_top_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_splash_top_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splash_image_ce = lv_image_create(ui_splash_screen);
    lv_image_set_src(ui_splash_image_ce, &ui_img_625624875);
    lv_obj_set_width(ui_splash_image_ce, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_splash_image_ce, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_splash_image_ce, 350);
    lv_obj_set_y(ui_splash_image_ce, -221);
    lv_obj_set_align(ui_splash_image_ce, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_splash_image_ce, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_splash_image_ce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splash_menu_bar = lv_image_create(ui_splash_screen);
    lv_image_set_src(ui_splash_menu_bar, &ui_img_menu_bar_png);
    lv_obj_set_width(ui_splash_menu_bar, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_splash_menu_bar, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_splash_menu_bar, -363);
    lv_obj_set_y(ui_splash_menu_bar, 0);
    lv_obj_set_align(ui_splash_menu_bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_splash_menu_bar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_splash_menu_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splash_screen_btn_img_home = lv_image_create(ui_splash_screen);
    lv_image_set_src(ui_splash_screen_btn_img_home, &ui_img_btn_home_png);
    lv_obj_set_width(ui_splash_screen_btn_img_home, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_splash_screen_btn_img_home, LV_SIZE_CONTENT);    /// 66
    lv_obj_set_x(ui_splash_screen_btn_img_home, -361);
    lv_obj_set_y(ui_splash_screen_btn_img_home, -203);
    lv_obj_set_align(ui_splash_screen_btn_img_home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_splash_screen_btn_img_home, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_splash_screen_btn_img_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splash_menu_container = lv_obj_create(ui_splash_screen);
    lv_obj_remove_style_all(ui_splash_menu_container);
    lv_obj_set_width(ui_splash_menu_container, 83);
    lv_obj_set_height(ui_splash_menu_container, 488);
    lv_obj_set_x(ui_splash_menu_container, -2);
    lv_obj_set_y(ui_splash_menu_container, -2);
    lv_obj_remove_flag(ui_splash_menu_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splash_btn_menu_home = lv_image_create(ui_splash_menu_container);
    lv_obj_set_width(ui_splash_btn_menu_home, 74);
    lv_obj_set_height(ui_splash_btn_menu_home, 65);
    lv_obj_set_x(ui_splash_btn_menu_home, 5);
    lv_obj_set_y(ui_splash_btn_menu_home, -412);
    lv_obj_set_align(ui_splash_btn_menu_home, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_splash_btn_menu_home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_splash_btn_menu_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_splash_btn_menu_home, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_splash_btn_menu_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_btn_menu_main = lv_image_create(ui_splash_menu_container);
    lv_obj_set_width(ui_splash_btn_menu_main, 74);
    lv_obj_set_height(ui_splash_btn_menu_main, 59);
    lv_obj_set_x(ui_splash_btn_menu_main, 5);
    lv_obj_set_y(ui_splash_btn_menu_main, -345);
    lv_obj_set_align(ui_splash_btn_menu_main, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_splash_btn_menu_main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_splash_btn_menu_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_splash_btn_menu_main, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_splash_btn_menu_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_btn_menu_settings = lv_image_create(ui_splash_menu_container);
    lv_obj_set_width(ui_splash_btn_menu_settings, 74);
    lv_obj_set_height(ui_splash_btn_menu_settings, 59);
    lv_obj_set_x(ui_splash_btn_menu_settings, 5);
    lv_obj_set_y(ui_splash_btn_menu_settings, -278);
    lv_obj_set_align(ui_splash_btn_menu_settings, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_splash_btn_menu_settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_splash_btn_menu_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_splash_btn_menu_settings, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_splash_btn_menu_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_btn_menu_autom = lv_image_create(ui_splash_menu_container);
    lv_obj_set_width(ui_splash_btn_menu_autom, 74);
    lv_obj_set_height(ui_splash_btn_menu_autom, 59);
    lv_obj_set_x(ui_splash_btn_menu_autom, 5);
    lv_obj_set_y(ui_splash_btn_menu_autom, -212);
    lv_obj_set_align(ui_splash_btn_menu_autom, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_splash_btn_menu_autom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_splash_btn_menu_autom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_splash_btn_menu_autom, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_splash_btn_menu_autom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_btn_menu_log = lv_image_create(ui_splash_menu_container);
    lv_obj_set_width(ui_splash_btn_menu_log, 74);
    lv_obj_set_height(ui_splash_btn_menu_log, 59);
    lv_obj_set_x(ui_splash_btn_menu_log, 5);
    lv_obj_set_y(ui_splash_btn_menu_log, -146);
    lv_obj_set_align(ui_splash_btn_menu_log, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_splash_btn_menu_log, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_splash_btn_menu_log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_splash_btn_menu_log, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_splash_btn_menu_log, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_btn_menu_aux = lv_image_create(ui_splash_menu_container);
    lv_obj_set_width(ui_splash_btn_menu_aux, 74);
    lv_obj_set_height(ui_splash_btn_menu_aux, 59);
    lv_obj_set_x(ui_splash_btn_menu_aux, 5);
    lv_obj_set_y(ui_splash_btn_menu_aux, -80);
    lv_obj_set_align(ui_splash_btn_menu_aux, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_splash_btn_menu_aux, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_splash_btn_menu_aux, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_splash_btn_menu_aux, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_splash_btn_menu_aux, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_btn_menu_debug = lv_image_create(ui_splash_menu_container);
    lv_obj_set_width(ui_splash_btn_menu_debug, 74);
    lv_obj_set_height(ui_splash_btn_menu_debug, 59);
    lv_obj_set_x(ui_splash_btn_menu_debug, 5);
    lv_obj_set_y(ui_splash_btn_menu_debug, -12);
    lv_obj_set_align(ui_splash_btn_menu_debug, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_splash_btn_menu_debug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_splash_btn_menu_debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_splash_btn_menu_debug, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_splash_btn_menu_debug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_screen_text_warning = lv_textarea_create(ui_splash_screen);
    lv_obj_set_width(ui_splash_screen_text_warning, 545);
    lv_obj_set_height(ui_splash_screen_text_warning, 110);
    lv_obj_set_x(ui_splash_screen_text_warning, 96);
    lv_obj_set_y(ui_splash_screen_text_warning, -113);
    lv_obj_set_align(ui_splash_screen_text_warning, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_splash_screen_text_warning,
                         "Warning\nBefore using this system, read the user manual carefully.\nThe regulation valve must be fully open prior to starting the watermaker system.");
    lv_textarea_set_placeholder_text(ui_splash_screen_text_warning, "Placeholder...");
    lv_obj_set_style_text_color(ui_splash_screen_text_warning, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_splash_screen_text_warning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_splash_screen_text_warning, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_splash_screen_text_warning, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_splash_screen_text_warning, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_splash_screen_text_warning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_screen_image_qr_code = lv_image_create(ui_splash_screen);
    lv_image_set_src(ui_splash_screen_image_qr_code, &ui_img_1530556444);
    lv_obj_set_width(ui_splash_screen_image_qr_code, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_splash_screen_image_qr_code, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_splash_screen_image_qr_code, -239);
    lv_obj_set_y(ui_splash_screen_image_qr_code, -116);
    lv_obj_set_align(ui_splash_screen_image_qr_code, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_splash_screen_image_qr_code, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_splash_screen_image_qr_code, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splash_screen_text_created_by = lv_textarea_create(ui_splash_screen);
    lv_obj_set_width(ui_splash_screen_text_created_by, 662);
    lv_obj_set_height(ui_splash_screen_text_created_by, 261);
    lv_obj_set_x(ui_splash_screen_text_created_by, 105);
    lv_obj_set_y(ui_splash_screen_text_created_by, 205);
    lv_textarea_set_text(ui_splash_screen_text_created_by,
                         "Proudly created and developed in the European Union by CobrAm GmbH.\n\nThe N.E.R.D. Watermaker Controller project is continuously developed with the support and feedback of the sailing and maker community.\n\nSource code may be shared privately through our official GitHub repositories exclusively for personal, educational, testing, and non-commercial purposes for fellow NERD sailors interested in contributing to the project and its development.\n\nAny commercial use, redistribution, reproduction, modification, integration into commercial products, or use of the source code, firmware, graphics, or portions thereof without prior written authorization from CobrAm GmbH is strictly prohibited.\n\nAll intellectual property rights, including software architecture, interface design, graphics, branding, and associated materials, remain the exclusive property of CobrAm GmbH.");
    lv_textarea_set_placeholder_text(ui_splash_screen_text_created_by, "Placeholder...");
    lv_obj_set_style_text_color(ui_splash_screen_text_created_by, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_splash_screen_text_created_by, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_splash_screen_text_created_by, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_splash_screen_text_created_by, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_splash_screen_text_created_by, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_splash_btn_menu_home, ui_event_btn_menu_home, LV_EVENT_ALL, NULL);

}

void ui_splash_screen_screen_destroy(void)
{
    if(ui_splash_screen) lv_obj_del(ui_splash_screen);

    // NULL screen variables
    ui_splash_screen = NULL;
    ui_splash_top_bar = NULL;
    ui_splash_image_ce = NULL;
    ui_splash_menu_bar = NULL;
    ui_splash_screen_btn_img_home = NULL;
    ui_splash_menu_container = NULL;
    ui_splash_btn_menu_home = NULL;
    ui_splash_btn_menu_main = NULL;
    ui_splash_btn_menu_settings = NULL;
    ui_splash_btn_menu_autom = NULL;
    ui_splash_btn_menu_log = NULL;
    ui_splash_btn_menu_aux = NULL;
    ui_splash_btn_menu_debug = NULL;
    ui_splash_screen_text_warning = NULL;
    ui_splash_screen_image_qr_code = NULL;
    ui_splash_screen_text_created_by = NULL;

}
